module.exports = {
    elements: {
        breadcrumb: 'body > ul.breadcrumb',
        currentTab: 'body > form:nth-child(15) > ul > li:nth-child(1) > a',
        allTab: 'body > form:nth-child(15) > ul > li:nth-child(2) > a',
        barCodeLabel: 'body > form:nth-child(15) > ul > img',
        searchInput: 'body > form:nth-child(15) > ul > input.pull-right.se-font',
        searchBtn: 'body > form:nth-child(15) > ul > input.btn.btn-mini.btn-primary.pull-right',
        gradesSelect: 'body > form:nth-child(16) > table > tbody > tr > td > select:nth-child(2)',
        typesSelect: '#stype',
        categorySelect: 'body > form:nth-child(16) > table > tbody > tr > td > select:nth-child(4)',
        listAll: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(1) > a',
        a: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(2) > a',
        b: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(3) > a',
        c: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(4) > a',
        d: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(5) > a',
        e: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(6) > a',
        f: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(7) > a',
        g: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(8) > a',
        h: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(9) > a',
        i: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(10) > a',
        j: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(11) > a',
        k: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(12) > a',
        l: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(13) > a',
        m: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(14) > a',
        n: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(15) > a',
        o: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(16) > a',
        p: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(17) > a',
        q: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(18) > a',
        r: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(19) > a',
        s: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(20) > a',
        t: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(21) > a',
        u: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(22) > a',
        v: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(23) > a',
        w: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(24) > a',
        x: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(25) > a',
        y: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(26) > a',
        z: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(27) > a',
        studentCount: 'body > form:nth-child(17) > table > tbody > tr > td:nth-child(28)',
        studentCodeHeader: 'body > form:nth-child(17) > div > table > tbody > tr.se-bold.se-bg-gray > td:nth-child(2)',
        nameHeader: 'body > form:nth-child(17) > div > table > tbody > tr.se-bold.se-bg-gray > td:nth-child(3)',
        gradeHeader: 'body > form:nth-child(17) > div > table > tbody > tr.se-bold.se-bg-gray > td:nth-child(4)',
        locationHeader: 'body > form:nth-child(17) > div > table > tbody > tr.se-bold.se-bg-gray > td:nth-child(5)',
        testStudentCode: 'body > form:nth-child(17) > div > table > tbody > tr.se-bg-pink > td.se-bold > a',
        testStudentName: 'body > form:nth-child(17) > div > table > tbody > tr.se-bg-pink > td:nth-child(3)',
        testStudentGrade: 'body > form:nth-child(17) > div > table > tbody > tr.se-bg-pink > td:nth-child(4)'
    }
};
