module.exports = {
    elements: {
        breadcrumb: 'body > ul.breadcrumb',
        monthTab: 'body > form > ul:nth-child(4) > li:nth-child(1) > a',
        weekTab: 'body > form > ul:nth-child(4) > li:nth-child(2) > a',
        dayTab: 'body > form > ul:nth-child(4) > li:nth-child(3) > a',
        //Month Tab
        exportiCalBtn: 'body > form > ul:nth-child(4) > input[type="button"]:nth-child(4)',
        searchField: 'body > form > ul:nth-child(4) > input[type="text"]:nth-child(6)',
        searchBtn: 'body > form > ul:nth-child(4) > input[type="submit"]:nth-child(8)',
        printBtn: 'body > form > ul:nth-child(4) > input[type="button"]:nth-child(12)',
        meetingMakerBtn: 'body > form > ul:nth-child(4) > input[type="button"]:nth-child(10)',
        todayBtn: 'body > form > table > tbody > tr > td:nth-child(3) > input[type="button"]:nth-child(1)',
        leftArrowBtn: 'body > form > table > tbody > tr > td:nth-child(3) > input[type="button"]:nth-child(2)',
        rightArrowBtn: 'body > form > table > tbody > tr > td:nth-child(3) > input[type="button"]:nth-child(3)',
        monthSelector: '#thismonth',
        yearSelector: '#thisyear',
        monthYearHeader: 'body > form > table > tbody > tr > td:nth-child(4)',
        categoryLabel: 'body > form > table > tbody > tr > td:nth-child(5)',
        categorySelector: 'body > form > table > tbody > tr > td:nth-child(5) > b > select',
        janTab: 'body > form > ul:nth-child(6) > li:nth-child(1) > a',
        febTab: 'body > form > ul:nth-child(6) > li:nth-child(2) > a',
        marTab: 'body > form > ul:nth-child(6) > li:nth-child(3) > a',
        aprTab: 'body > form > ul:nth-child(6) > li:nth-child(4) > a',
        mayTab: 'body > form > ul:nth-child(6) > li:nth-child(5) > a',
        junTab: 'body > form > ul:nth-child(6) > li:nth-child(6) > a',
        julTab: 'body > form > ul:nth-child(6) > li:nth-child(7) > a',
        augTab: 'body > form > ul:nth-child(6) > li:nth-child(8) > a',
        sepTab: 'body > form > ul:nth-child(6) > li:nth-child(9) > a',
        octTab: 'body > form > ul:nth-child(6) > li:nth-child(10) > a',
        novTab: 'body > form > ul:nth-child(6) > li:nth-child(11) > a',
        decTab: 'body > form > ul:nth-child(6) > li:nth-child(12) > a',
        calendarBody: 'body > form > div > table:nth-child(1) > tbody',
        sun: 'body > form > div > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(2)',
        mon: 'body > form > div > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(3)',
        tue: 'body > form > div > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(4)',
        wed: 'body > form > div > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(5)',
        thu: 'body > form > div > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(6)',
        fri: 'body > form > div > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(7)',
        sat: 'body > form > div > table:nth-child(1) > tbody > tr:nth-child(1) > td:nth-child(8)',
        birthdayBtn: 'body > form > div > table:nth-child(2) > tbody > tr > td:nth-child(1) > a:nth-child(1)',
        listingBtn: 'body > form > div > table:nth-child(2) > tbody > tr > td:nth-child(1) > a:nth-child(2)'
    }
};
