module.exports = {
    url: function() {

        return this.api.launchUrl + '/schoolmenu.php';
    },
    elements: {
        home: {
            selector: 'ul.breadcrumb li.active a',
        },
        //School Menu
        school: '#menu > li:nth-child(1)',
        schoolNews: '#menu > li:nth-child(1) > ul > li:nth-child(1) > a',
        schoolCalendar: '#menu > li:nth-child(1) > ul > li:nth-child(2) > a',
        schoolDocuments: '#menu > li:nth-child(1) > ul > li:nth-child(3) > a',
        schoolPhotoAlbums: '#menu > li:nth-child(1) > ul > li:nth-child(4) > a',
        schoolMultimedia: '#menu > li:nth-child(1) > ul > li:nth-child(5) > a',
        schoolFarofites: '#menu > li:nth-child(1) > ul > li:nth-child(6) > a',
        //Front Desk Menu
        frontDesk: '#menu > li:nth-child(2) > a',
        frontDeskFamilyDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(1) > a',
        frontDeskEmployeeDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(2) > a',
        frontDeskClassroomDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(3) > a',
        frontDeskDepartments: '#menu > li:nth-child(2) > ul > li:nth-child(4) > a',
        frontDeskFacility: '#menu > li:nth-child(2) > ul > li:nth-child(5) > a',
        //Info Center Menu
        infoCenter: '#menu > li:nth-child(3)',
        infoCenterLibrary: '#menu > li:nth-child(3) > ul > li:nth-child(1) > a',
        infoCenterCafeteria: '#menu > li:nth-child(3) > ul > li:nth-child(2) > a',
        infoCenterOnlineAuctions: '#menu > li:nth-child(3) > ul > li:nth-child(3) > a',
        infoCenterDatabases: '#menu > li:nth-child(3) > ul > li:nth-child(4) > a',
        infoCenterOnlineForms: '#menu > li:nth-child(3) > ul > li:nth-child(5) > a',
        infoCenterEventRegistration: '#menu > li:nth-child(3) > ul > li:nth-child(6) > a',
        infoCenterKnowledgebase: '#menu > li:nth-child(3) > ul > li:nth-child(7) > a',
        //Comm Center Menu
        commCenter: '#menu > li:nth-child(4) > a',
        commCenterBlogs: '#menu > li:nth-child(4) > ul > li:nth-child(1) > a',
        commCenterDiscussions: '#menu > li:nth-child(4) > ul > li:nth-child(2) > a',
        //Address Book Menu
        addressBook: '#menu > li:nth-child(6)',
        addressBookByLastName: '#menu > li:nth-child(6) > ul > li:nth-child(1) > a',
        addressBookByCompany: '#menu > li:nth-child(6) > ul > li:nth-child(2) > a',
        addressBookCategories: '#menu > li:nth-child(6) > ul > li:nth-child(3) > a',
        addressBookAdditionalFields: '#menu > li:nth-child(6) > ul > li:nth-child(4) > a',
        addressBookReports: '#menu > li:nth-child(6) > ul > li:nth-child(5) > a',
        //Communication Menu
        communication: '#menu > li:nth-child(7) > a',
        //Communicaton Homepage
        communicationHomepage: '#menu > li:nth-child(7) > ul > a:nth-child(1)',
        communicationHomepagePolling: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        communicationHomepageFlashNews: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        communicationHomepageSponsorAds: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        communicationHomepageRequest: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        communicationHomepageMsgOfTheDay: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(5) > a',
        //Communication Batch Email
        communicationBatchEmail: '#menu > li:nth-child(7) > ul > a:nth-child(3)',
        communicationBatchEmailCompose: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        communicationBatchEmailDrafts: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        communicationBatchEmailScheduled: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        communicationBatchEmailSent: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        //Communication Text Messaging
        communicationTextMessaging: '#menu > li:nth-child(7) > ul > a:nth-child(5)',
        communicationTextMessagingBatchTextMessage: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        communicationTextMessagingMessageLogs: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        //Communication Menu Items
        communicationTemplates: '#menu > li:nth-child(7) > ul > li:nth-child(7) > a',
        communicationSafetyAlerts: '#menu > li:nth-child(7) > ul > li:nth-child(8) > a',
        communicationMemoMaker: '#menu > li:nth-child(7) > ul > li:nth-child(9) > a',
        communicationEVerification: '#menu > li:nth-child(7) > ul > li:nth-child(10) > a',
        communicationChecklist: '#menu > li:nth-child(7) > ul > li:nth-child(11) > a',
        communicationNotificationLists: '#menu > li:nth-child(7) > ul > li:nth-child(12) > a',
        communicationConfiguration: '#menu > li:nth-child(7) > ul > li:nth-child(13) > a',
        communicationReports: '#menu > li:nth-child(7) > ul > li:nth-child(14) > a',
        //Administrative Menu
        administrative: '#menu > li:nth-child(8) > a',
        //Administrative Back Office Mgr
        backOfficeMgr: '#menu > li:nth-child(8) > ul > a:nth-child(1)',
        //Back Office Mgr Students
        backOfficeMgrStudents: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > a:nth-child(1)',
        backOfficeMgrStudentsAll: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(1) > a',
        backOfficeMgrStudentsCurrent: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(2) > a',
        backOfficeMgrStudentsTypes: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(3) > a',
        backOfficeMgrStudentsAdditionalFields: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(4) > a',
        backOfficeMgrStudentsCategories: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(5) > a',
        backOfficeMgrStudentsActivites: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(6) > a',
        backOfficeMgrStudentsChecklists: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(7) > a',
        //Back Office Mgr Families
        backOfficeMgrFamilies: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > a:nth-child(3)',
        backOfficeMgrFamiliesAll: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(1) > a',
        backOfficeMgrFamiliesCurrent: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(2) > a',
        backOfficeMgrFamiliesAdditionalFields: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(3) > a',
        backOfficeMgrFamiliesNewFamily: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(4) > a',
        //Back Office Mgr Menu Items
        backOfficeReports: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > li > a',
        //Administrative Attendance
        attendance: '#menu > li:nth-child(8) > ul > a:nth-child(3)',
        //Attendance Menu Items
        attendanceHomeroom: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        attendanceByPeriods: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        attendanceByStudent: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        attendanceByClassroom: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        attendanceByEmployee: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(5) > a',
        attendanceDailyAbsences: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(6) > a',
        attendanceCheckInOut: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(7) > a',
        attendanceRecordTypes: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(8) > a',
        attendanceScale: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(9) > a',
        attendanceReports: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(10) > a',
        //Administrative Administration
        administration: '#menu > li:nth-child(8) > ul > a:nth-child(5)',
        administrationSchoolYears: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        administrationSchoolPeriods: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        administrationGradeLevels: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(3) > a',
        administrationCalendarOptions: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(4) > a',
        administrationReportTemplate: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(5) > a',
        administrationReportArchives: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(7) > a:nth-child(2)',
        //Administartive Human Resources
        humanReources: '#menu > li:nth-child(8) > ul > a:nth-child(7)',
        humanResourcesEmployees: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        humanResourcesSubstitutes: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        humanResourcesDepartments: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        humanResourcesPositions: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(4) > a',
        humanResourcesTypes: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(5) > a',
        humanResourcesCategories: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(6) > a',
        humanResourcesAdditionalFields: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(7) > a',
        humanResourcesReports: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(8) > a',
        //Academic Menu
        academic: '#menu > li:nth-child(9) > a',
        //Academic Grade Manager
        gradeMgr: '#menu > li:nth-child(9) > ul > a:nth-child(1)',
        gradeMgrReportCards: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        gradeMgrGradingScales: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        gradeMgrAttributesGrades: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        gradeMgrGradeComments: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        gradeMgrAdditionalFields: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(5) > a',
        gradeMgrGpaScales: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(6) > a',
        gradeMgrRequirements: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(7) > a',
        gradeMgrConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(8) > a',
        gradeMgrReports: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(9) > a',
        //Academic Classroom Manager
        classroomMgr: '#menu > li:nth-child(9) > ul > a:nth-child(3)',
        classroomMgrDayLong: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        classroomMgrPeriodLong: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        classroomMgrGeneral: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        classroomMgrAdditionalFields: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        classroomMgrConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(5) > a',
        classroomMgrReports: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(6) > a',
        //Academic Resource Manager
        resourceMgr: '#menu > li:nth-child(9) > ul > a:nth-child(5)',
        resourceMgrNews: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        resourceMgrPhotos: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        resourceMgrDocuments: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(3) > a',
        resourceMgrOnlineTests: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(4) > a',
        resourceMgrBlogs: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(5) > a',
        //Academic Transcript Manager
        transcriptMgr: '#menu > li:nth-child(9) > ul > a:nth-child(7)',
        transcriptMgrStudents: '#menu > li:nth-child(9) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        transcriptMgrTemplates: '#menu > li:nth-child(9) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        transcriptMgrConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        //Academic Curriculum Manager
        curriculumMgr: '#menu > li:nth-child(9) > ul > a:nth-child(9)',
        curriculumMgrBySubject: '#menu > li:nth-child(9) > ul > ul:nth-child(10) > li:nth-child(1) > a',
        curriculumMgrByGrade: '#menu > li:nth-child(9) > ul > ul:nth-child(10) > li:nth-child(2) > a',
        //Academic Assessment Manager
        assessmentMgr: '#menu > li:nth-child(9) > ul > a:nth-child(11)',
        assessmentMgrSkillSets: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(1) > a',
        assessmentMgrStandards: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(2) > a',
        assessmentMgrAssessments: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(3) > a',
        assessmentMgrAchievements: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(4) > a',
        assessmentMgrStandardizedTests: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(5) > a',
        assessmentMgrLessonPlans: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > a',
        assessmentMgrLessonPlansByDay: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > ul > li:nth-child(1) > a',
        assessmentMgrLessonPlansByClass: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > ul > li:nth-child(2) > a',
        assessmentMgrLessonPlansConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > ul > li:nth-child(3) > a',
        assessmentMgrReports: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(8) > a',
        //Academic IEP Manager
        iepMgr: '#menu > li:nth-child(9) > ul > a:nth-child(13)',
        iepMgrStudents: '#menu > li:nth-child(9) > ul > ul:nth-child(14) > li:nth-child(1) > a',
        iepMgrCoordinators: '#menu > li:nth-child(9) > ul > ul:nth-child(14) > li:nth-child(2) > a',
        iepMgrConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(14) > li:nth-child(3) > a',
        iepMgrReports: '#menu > li:nth-child(9) > ul > ul:nth-child(14) > li:nth-child(4) > a',
        //Academic College Credit Manager
        collegeCreditMgr: '#menu > li:nth-child(9) > ul > a:nth-child(15)',
        collegeCreditMgrStudents: '#menu > li:nth-child(9) > ul > ul:nth-child(16) > li:nth-child(1) > a',
        collegeCreditMgrColleges: '#menu > li:nth-child(9) > ul > ul:nth-child(16) > li:nth-child(2) > a',
        //Financial Menu
        financial: '#menu > li:nth-child(10)',
        //Financial Accounting Manager
        accountingMgr: '#menu > li:nth-child(10) > ul > a:nth-child(1)',
        //Accounting Manager School
        accountingMgrSchool: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > a:nth-child(1)',
        accountingMgrSchoolChartOfAccounts: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(1) > a',
        accountingMgrSchoolActivityLogs: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(2) > a',
        //Accounting Manager Families 
        accountingMgrFamilies: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > a:nth-child(3)',
        accountingMgrFamiliesCurrent: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(1) > a',
        accountingMgrFamiliesAccounts: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(2) > a',
        accountingMgrFamiliesBillingSetup: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(3) > a',
        accountingMgrFamiliesMonthlyCharges: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(4) > a',
        accountingMgrFamiliesReceivePayment: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(5) > a',
        accountingMgrFamiliesNotifications: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(6) > a',
        accountingMgrFamiliesInvoices: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(7) > a',
        //Accounting Manager Banking
        accountingMgrBanking: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > a:nth-child(5)',
        accountingMgrBankingDeposits: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(6) > li:nth-child(1) > a',
        accountingMgrBankingRegisters: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(6) > li:nth-child(2) > a',
        accountingMgrBankingJournal: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(6) > li:nth-child(3) > a',
        //Accounting Manager Employees
        accountingMgrEmployees: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > a:nth-child(7)',
        //Accounting Manager Employees Payroll Menu
        accountingMgrEmployeesPayroll: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(8) > a:nth-child(1)',
        accountingMgrEmployeesPayrollByEmployee: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(8) > ul:nth-child(2) > li:nth-child(1) > a',
        accountingMgrEmployeesPayrollByMonth: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(8) > ul:nth-child(2) > li:nth-child(2) > a',
        //Accounting Manager Employees Expenses Menu
        accountingMgrEmployeesExpenses: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(8) > a:nth-child(3)',
        accountingMgrEmployeesExpensesSubmitted: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(8) > ul:nth-child(4) > li:nth-child(1) > a',
        accountingMgrEmployeesExpensesApproved: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(8) > ul:nth-child(4) > li:nth-child(2) > a',
        accountingMgrEmployeesExpensesPaid: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(8) > ul:nth-child(4) > li:nth-child(3) > a',
        //Accounting Manager Services
        accountingMgrServices: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > a:nth-child(9)',
        //Accounting Manager Services Dwolla Menu 
        accountingMgrServicesDwolla: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > a:nth-child(1)',
        accountingMgrServicesDwollaTransactions: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(2) > li:nth-child(1) > a',
        accountingMgrServicesDwollaConfiguration: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(2) > li:nth-child(2) > a',
        //Accounting Manager Services Payjunction:
        accountingMgrServicesPayJunction: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > a:nth-child(3)',
        accountingMgrServicesPayJunctionInvoices: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(4) > li:nth-child(1) > a',
        accountingMgrServicesPayJunctionPayments: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(4) > li:nth-child(2) > a',
        accountingMgrServicesPayJunctionConvenienceFees: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(4) > li:nth-child(3) > a',
        accountingMgrServicesPayJunctionConfiguration: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(4) > li:nth-child(4) > a',
        //Accouting Manager Services Smart Tuition
        accountingMgrServicesSmartTuition: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > a:nth-child(5)',
        accountingMgrServicesSmartTuitionConfiguration: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(6) > li > a',
        //Accounting Manager Services PayPal
        accountingMgrServicesPayPal: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > a:nth-child(7)',
        accountingMgrServicesPayPalOnlinePayments: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(8) > li:nth-child(1) > a',
        accountingMgrServicesPayPalInvoices: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(8) > li:nth-child(2) > a',
        accountingMgrServicesPayPalConfiguration: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(8) > li:nth-child(3) > a',
        //Accounting Manager Services EFunds
        accountingMgrServicesEFunds: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > a:nth-child(9)',
        accountingMgrServicesEFundsPayments: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(10) > li:nth-child(1) > a',
        accountingMgrServicesEFundsTransactions: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(10) > li:nth-child(2) > a',
        accountingMgrServicesEFundsRemittance: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(10) > li:nth-child(3) > a',
        accountingMgrServicesEFundsConfiguration: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > ul:nth-child(10) > ul:nth-child(10) > li:nth-child(4) > a',
        //Accounting Manger Menu Items
        accountingMgrConfiguration: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > li:nth-child(11) > a',
        accountingMgrReports: '#menu > li:nth-child(10) > ul > ul:nth-child(2) > li:nth-child(12) > a',
        //Cafeteria Manager
        cafeteriaMgr: '#menu > li:nth-child(10) > ul > a:nth-child(3)',
        cafeteriaMgrFood: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        cafeteriaMgrMenu: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        cafeteriaMgrCycles: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        cafeteriaMgrOrders: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        cafeteriaMgrPricePlans: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > li:nth-child(5) > a',
        cafeteriaMgrNotifications: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > li:nth-child(6) > a',
        //Cafeteria Manager Accounts
        cafeteriaMgrAccounts: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > a',
        cafeteriaMgrAccountsFamily: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > ul > li:nth-child(1) > a',
        cafeteriaMgrAccountsEmployee: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > ul > li:nth-child(2) > a',
        //Cafeteria Manager Menu Items
        cafeteriaMgrReports: '#menu > li:nth-child(10) > ul > ul:nth-child(4) > li:nth-child(9) > a',
        //Accounting Manager Childcare Manager
        childcareMgr: '#menu > li:nth-child(10) > ul > a:nth-child(5)',
        childcareMgrAccounts: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        //Childcare Manager Daily
        childcareMgrDaily: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > a:nth-child(2)',
        childcareMgrDailyCheckInOut: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(3) > li:nth-child(1) > a',
        childcareMgrDailyDailyCharges: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(3) > li:nth-child(2) > a',
        childcareMgrDailyPricePlans: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(3) > li:nth-child(3) > a',
        //Childcare Manager Weekly
        childcareMgrWeekly: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > a:nth-child(4)',
        childcareMgrWeeklyCharges: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(5) > li:nth-child(1) > a',
        childcareMgrWeeklyBillingSetup: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(5) > li:nth-child(2) > a',
        childcareMgrWeeklyPricePlans: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(5) > li:nth-child(3) > a',
        //Childcare Manager Monthly
        childcareMgrMonthly: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > a:nth-child(6)',
        childcareMgrMonthlyCharges: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(7) > li:nth-child(1) > a',
        childcareMgrMonthlyBillingSetup: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(7) > li:nth-child(2) > a',
        childcareMgrMonthlyPricePlans: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > ul:nth-child(7) > li:nth-child(3) > a',
        //Childcare Manager Menu Items
        childcareMgrNotifications: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > li:nth-child(8) > a',
        childcareMgrReports: '#menu > li:nth-child(10) > ul > ul:nth-child(6) > li:nth-child(9) > a',
        //Accounting Manager Donation Manager
        donationMgr: '#menu > li:nth-child(10) > ul > a:nth-child(7)',
        //Donation Manager Donors
        donationMgrDonors: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > a:nth-child(1)',
        donationMgrDonorsNewDonors: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > ul:nth-child(2) > li:nth-child(1) > a',
        donationMgrDonorsByContact: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > ul:nth-child(2) > li:nth-child(2) > a',
        donationMgrDonorsPledges: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > ul:nth-child(2) > li:nth-child(3) > a',
        //Donation Manager Donations
        donationMgrDonations: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > a:nth-child(3)',
        donationMgrDonationsReceive: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > ul:nth-child(4) > li:nth-child(1) > a',
        donationMgrDonationsProcess: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > ul:nth-child(4) > li:nth-child(2) > a',
        //Donatoin Manager Menu Items
        donationMgrCampaings: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > li:nth-child(5) > a',
        donationMgrReports: '#menu > li:nth-child(10) > ul > ul:nth-child(8) > li:nth-child(6) > a',
        //Addmissions Menu
        addmissions: '#menu > li:nth-child(11)',
        //Addmissions Inquiries
        inquiries: '#menu > li:nth-child(11) > ul > a:nth-child(1)',
        inquiresStudents: '#menu > li:nth-child(11) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        inquiriesFamilies: '#menu > li:nth-child(11) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        //Addmissions Enrollment
        enrollment: '#menu > li:nth-child(11) > ul > a:nth-child(3)',
        enrollmentStudent: '#menu > li:nth-child(11) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        enrollmentFamilies: '#menu > li:nth-child(11) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        //Class Manager
        classMgr: '#menu > li:nth-child(11) > ul > a:nth-child(5)',
        classMgrClasses: '#menu > li:nth-child(11) > ul > ul:nth-child(6) > li > a',
        //Course Manager
        courseMgr: '#menu > li:nth-child(11) > ul > a:nth-child(7)',
        courseMgrCourses: '#menu > li:nth-child(11) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        courseMgrTeachers: '#menu > li:nth-child(11) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        courseMgrStudents: '#menu > li:nth-child(11) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        courseMgrFacility: '#menu > li:nth-child(11) > ul > ul:nth-child(8) > li:nth-child(4) > a',
        courseMgrScheduler: '#menu > li:nth-child(11) > ul > ul:nth-child(8) > li:nth-child(5) > a',
        courseMgrConfiguration: '#menu > li:nth-child(11) > ul > ul:nth-child(8) > li:nth-child(6) > a',
        courseMgrReports: '#menu > li:nth-child(11) > ul > ul:nth-child(8) > li:nth-child(7) > a',
        //Addmissions Communication
        addmissionsCommunication: '#menu > li:nth-child(11) > ul > a:nth-child(9)',
        addmissionsCommunicationBatchEmail: '#menu > li:nth-child(11) > ul > ul:nth-child(10) > li > a',
        //Portal Manager
        portalMgr: '#menu > li:nth-child(11) > ul > a:nth-child(11)',
        portalMgrStudents: '#menu > li:nth-child(11) > ul > ul:nth-child(12) > li:nth-child(1) > a',
        portalMgrFamilies: '#menu > li:nth-child(11) > ul > ul:nth-child(12) > li:nth-child(2) > a',
        portalMgrApplications: '#menu > li:nth-child(11) > ul > ul:nth-child(12) > li:nth-child(3) > a',
        portalMgrEssayQuestions: '#menu > li:nth-child(11) > ul > ul:nth-child(12) > li:nth-child(4) > a',
        portalMgrRequestedDocs: '#menu > li:nth-child(11) > ul > ul:nth-child(12) > li:nth-child(5) > a',
        //Addmissions Configuration
        addmissionsConfiguration: '#menu > li:nth-child(11) > ul > a:nth-child(13)',
        addmissionsConfigurationChecklist: '#menu > li:nth-child(11) > ul > ul:nth-child(14) > li:nth-child(1) > a',
        addmissionsConfigurationDocuments: '#menu > li:nth-child(11) > ul > ul:nth-child(14) > li:nth-child(2) > a',
        addmissionsConfigurationAgreements: '#menu > li:nth-child(11) > ul > ul:nth-child(14) > li:nth-child(3) > a',
        addmissionsConfigurationTuitionPlans: '#menu > li:nth-child(11) > ul > ul:nth-child(14) > li:nth-child(4) > a',
        addmissionsConfigurationEnrollStatus: '#menu > li:nth-child(11) > ul > ul:nth-child(14) > li:nth-child(5) > a',
        addmissionsConfigurationSetup: '#menu > li:nth-child(11) > ul > ul:nth-child(14) > li:nth-child(6) > a',
        //Addmissions Menu Items
        addmissionsReports: '#menu > li:nth-child(11) > ul > li > a',
        //Specialties Menu
        specialties: '#menu > li:nth-child(12) > a',
        //Athletic Director
        athleticDirector: '#menu > li:nth-child(12) > ul > a:nth-child(1)',
        athleticDirectorSports: '#menu > li:nth-child(12) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        athleticDirectorTeams: '#menu > li:nth-child(12) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        athleticDirectorScoreboard: '#menu > li:nth-child(12) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        athleticDirectorEquipment: '#menu > li:nth-child(12) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        //NursesOffice
        nursesOffice: '#menu > li:nth-child(12) > ul > a:nth-child(3)',
        nursesOfficeDailyLogs: '#menu > li:nth-child(12) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        nursesOfficeStudents: '#menu > li:nth-child(12) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        nursesOfficeConfiguration: '#menu > li:nth-child(12) > ul > ul:nth-child(4) > a',
        nursesOfficeConfigurationComplaints: '#menu > li:nth-child(12) > ul > ul:nth-child(4) > ul > li:nth-child(1) > a',
        nursesOfficeConfigurationMedications: '#menu > li:nth-child(12) > ul > ul:nth-child(4) > ul > li:nth-child(2) > a',
        nursesOfficeConfigurationImmunizations: '#menu > li:nth-child(12) > ul > ul:nth-child(4) > ul > li:nth-child(3) > a',
        nursesOfficeReports: '#menu > li:nth-child(12) > ul > ul:nth-child(4) > li:nth-child(5) > a',
        // P/T Conferences
        ptConferences: '#menu > li:nth-child(12) > ul > a:nth-child(5)',
        ptConferencesTeachers: '#menu > li:nth-child(12) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        ptConferencesByDate: '#menu > li:nth-child(12) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        ptConferencesByTeacher: '#menu > li:nth-child(12) > ul > ul:nth-child(6) > li:nth-child(3) > a',
        ptConferencesConfiguration: '#menu > li:nth-child(12) > ul > ul:nth-child(6) > li:nth-child(4) > a',
        // Discipline
        discipline: '#menu > li:nth-child(12) > ul > a:nth-child(7)',
        disciplineStudents: '#menu > li:nth-child(12) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        disciplineDailyLogs: '#menu > li:nth-child(12) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        disciplineDetentions: '#menu > li:nth-child(12) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        disciplineConfiguration: '#menu > li:nth-child(12) > ul > ul:nth-child(8) > li:nth-child(4) > a',
        disciplineReports: '#menu > li:nth-child(12) > ul > ul:nth-child(8) > li:nth-child(5) > a',
        //Service Manager
        serviceMgr: '#menu > li:nth-child(12) > ul > a:nth-child(9)',
        serviceMgrStudents: '#menu > li:nth-child(12) > ul > ul:nth-child(10) > li:nth-child(1) > a',
        serviceMgrFamilies: '#menu > li:nth-child(12) > ul > ul:nth-child(10) > li:nth-child(2) > a',
        serviceMgrDailyLogs: '#menu > li:nth-child(12) > ul > ul:nth-child(10) > li:nth-child(3) > a',
        serviceMgrOpportunites: '#menu > li:nth-child(12) > ul > ul:nth-child(10) > li:nth-child(4) > a',
        serviceMgrReports: '#menu > li:nth-child(12) > ul > ul:nth-child(10) > li:nth-child(5) > a',
        //Connection Manager
        connectionMgr: '#menu > li:nth-child(12) > ul > a:nth-child(11)',
        connectionMgrStudents: '#menu > li:nth-child(12) > ul > ul:nth-child(12) > li:nth-child(1) > a',
        connectionMgrDailyLogs: '#menu > li:nth-child(12) > ul > ul:nth-child(12) > li:nth-child(2) > a',
        connectionMgrInitiator: '#menu > li:nth-child(12) > ul > ul:nth-child(12) > li:nth-child(3) > a',
        connectionMgrReports: '#menu > li:nth-child(12) > ul > ul:nth-child(12) > li:nth-child(4) > a',
        //Transportation Manager
        tranportationMgr: '#menu > li:nth-child(12) > ul > a:nth-child(13)',
        tranportationMgrBusRoutes: '#menu > li:nth-child(12) > ul > ul:nth-child(14) > li:nth-child(1) > a',
        tranportationMgrFieldTrips: '#menu > li:nth-child(12) > ul > ul:nth-child(14) > li:nth-child(2) > a',
        tranportationMgrCarpoolMgr: '#menu > li:nth-child(12) > ul > ul:nth-child(14) > li:nth-child(3) > a',
        tranportationMgrParkingPasses: '#menu > li:nth-child(12) > ul > ul:nth-child(14) > li:nth-child(4) > a',
        tranportationMgrReports: '#menu > li:nth-child(12) > ul > ul:nth-child(14) > li:nth-child(5) > a',
        //Volunteer Manager
        volunteerMgr: '#menu > li:nth-child(12) > ul > a:nth-child(15)',
        volunteerMgrEvents: '#menu > li:nth-child(12) > ul > ul:nth-child(16) > li > a',
        //Library Manager
        libraryMgr: '#menu > li:nth-child(12) > ul > a:nth-child(17)',
        libraryMgrBook: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > li:nth-child(1) > a',
        libraryMgrStudents: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > li:nth-child(2) > a',
        libraryMgrCheckIn: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > li:nth-child(3) > a',
        libraryMgrCheckOut: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > li:nth-child(4) > a',
        libraryMgrWhatsOut: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > li:nth-child(5) > a',
        //Library Manager Books Menu
        libraryMgrBooks: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > a:nth-child(6)',
        libraryMgrBooksLibrary: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > ul:nth-child(7) > li:nth-child(1) > a',
        libraryMgrBooksTextBooks: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > ul:nth-child(7) > li:nth-child(2) > a',
        libraryMgrBooksInventoryLibrary: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > ul:nth-child(7) > li:nth-child(3) > a',
        //Library Manager Search Menu
        libraryMgrSearch: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > a:nth-child(8)',
        libraryMgrSearchLocal: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > ul:nth-child(9) > li:nth-child(1) > a',
        libraryMgrSearchGoogle: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > ul:nth-child(9) > li:nth-child(2) > a',
        //Library Manager Configuration Menu
        libraryMgrConfiguration: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > a:nth-child(10)',
        libraryMgrConfigurationLocations: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > ul:nth-child(11) > li:nth-child(1) > a',
        libraryMgrConfigurationImport: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > ul:nth-child(11) > li:nth-child(2) > a',
        libraryMgrConfigurationSetup: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > ul:nth-child(11) > li:nth-child(3) > a',
        //Library Manager Menu Items
        libraryMgrReports: '#menu > li:nth-child(12) > ul > ul:nth-child(18) > li:nth-child(12) > a',
        //Auction Manager
        auctionMgr: '#menu > li:nth-child(12) > ul > a:nth-child(19)',
        auctionMgrStaff: '#menu > li:nth-child(12) > ul > ul:nth-child(20) > li:nth-child(1) > a',
        auctionMgrAuctions: '#menu > li:nth-child(12) > ul > ul:nth-child(20) > li:nth-child(2) > a',
        auctionMgrAuctionItems: '#menu > li:nth-child(12) > ul > ul:nth-child(20) > li:nth-child(3) > a',
        auctionMgrDonorCompanies: '#menu > li:nth-child(12) > ul > ul:nth-child(20) > li:nth-child(4) > a',
        auctionMgrReports: '#menu > li:nth-child(12) > ul > ul:nth-child(20) > li:nth-child(5) > a',
        //Utilities Menu
        utilities: '#menu > li:nth-child(13) > a',
        //Asset Manager 
        assetMgr: '#menu > li:nth-child(13) > ul > a:nth-child(1)',
        assetMgrInventory: '#menu > li:nth-child(13) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        assetMgrTypes: '#menu > li:nth-child(13) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        assetMgrAdditionalFields: '#menu > li:nth-child(13) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        assetMgrReports: '#menu > li:nth-child(13) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        //Event Manager
        eventMgr: '#menu > li:nth-child(13) > ul > a:nth-child(3)',
        eventMgrManagedEvents: '#menu > li:nth-child(13) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        eventMgrRegistration: '#menu > li:nth-child(13) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        eventMgrParticipants: '#menu > li:nth-child(13) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        eventMgrReports: '#menu > li:nth-child(13) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        //Facility Manager
        facilityMgr: '#menu > li:nth-child(13) > ul > a:nth-child(5)',
        facilityMgrLocations: '#menu > li:nth-child(13) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        facilityMgrBuildings: '#menu > li:nth-child(13) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        facilityMgrRooms: '#menu > li:nth-child(13) > ul > ul:nth-child(6) > li:nth-child(3) > a',
        facilityMgrPlanner: '#menu > li:nth-child(13) > ul > ul:nth-child(6) > li:nth-child(4) > a',
        facilityMgrActivities: '#menu > li:nth-child(13) > ul > ul:nth-child(6) > li:nth-child(5) > a',
        facilityMgrSearch: '#menu > li:nth-child(13) > ul > ul:nth-child(6) > li:nth-child(6) > a',
        //Timecard Manager
        timecardMgr: '#menu > li:nth-child(13) > ul > a:nth-child(7)',
        timecardMgrByDay: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        timecardMgrByPeriod: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        timecardMgrByEmployee: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        timecardMgrRequests: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(4) > a',
        timecardMgrTasks: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(5) > a',
        timecardMgrConfiguration: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(6) > a',
        timecardMgrReports: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(7) > a',
        //Workflow Manager
        workflowMgr: '#menu > li:nth-child(13) > ul > a:nth-child(9)',
        workflowMgrByStatus: '#menu > li:nth-child(13) > ul > ul:nth-child(10) > li:nth-child(1) > a',
        workflowMgrByAuthor: '#menu > li:nth-child(13) > ul > ul:nth-child(10) > li:nth-child(2) > a',
        workflowMgrByCategory: '#menu > li:nth-child(13) > ul > ul:nth-child(10) > li:nth-child(3) > a',
        workflowMgrByClassroom: '#menu > li:nth-child(13) > ul > ul:nth-child(10) > li:nth-child(4) > a',
        workflowMgrCategories: '#menu > li:nth-child(13) > ul > ul:nth-child(10) > li:nth-child(5) > a',
        //Database Manager
        databaseMgr: '#menu > li:nth-child(13) > ul > a:nth-child(11)',
        databaseMgrPublicTables: '#menu > li:nth-child(13) > ul > ul:nth-child(12) > li:nth-child(1) > a',
        databaseMgrPrivateTables: '#menu > li:nth-child(13) > ul > ul:nth-child(12) > li:nth-child(2) > a',
        //Online Form Manager
        onlineFormMgr: '#menu > li:nth-child(13) > ul > a:nth-child(13)',
        onlineFormMgrActive: '#menu > li:nth-child(13) > ul > ul:nth-child(14) > li:nth-child(1) > a',
        onlineFormMgrNonActive: '#menu > li:nth-child(13) > ul > ul:nth-child(14) > li:nth-child(2) > a',
        //Knowledge Base
        knowledgeBase: '#menu > li:nth-child(13) > ul > a:nth-child(15)',
        knowledgeBasePublished: '#menu > li:nth-child(13) > ul > ul:nth-child(16) > li:nth-child(1) > a',
        knowledgeBasePending: '#menu > li:nth-child(13) > ul > ul:nth-child(16) > li:nth-child(2) > a',
        //Breakroom Menu
        breakRoom: '#menu > li:nth-child(14)',
        classifiedAds: '#menu > li:nth-child(14) > ul > li > a',
        //System Help Menu
        systemHelp: '#menu > li:nth-child(15) > a',
        welcomeAboard: '#menu > li:nth-child(15) > ul > li:nth-child(1) > a',
        onlineHelp: '#menu > li:nth-child(15) > ul > li:nth-child(2) > a',
        trainingVideos: '#menu > li:nth-child(15) > ul > li:nth-child(3) > a',
        webinarTraining: '#menu > li:nth-child(15) > ul > li:nth-child(4) > a',
        sycamoreLeafNotes: '#menu > li:nth-child(15) > ul > li:nth-child(5) > a',
        releaseNotes: '#menu > li:nth-child(15) > ul > li:nth-child(6) > a',
        //System Support Menu
        systemSupport: '#menu > li:nth-child(17) > a',
        openTickets: '#menu > li:nth-child(17) > ul > li:nth-child(1) > a',
        closedTickets: '#menu > li:nth-child(17) > ul > li:nth-child(2) > a',
        //Site Admin Menu
        siteAdmin: '#menu > li:nth-child(18) > a',
        siteAdminInformation: '#menu > li:nth-child(18) > ul > li:nth-child(1) > a',
        siteAdminConfiguration: '#menu > li:nth-child(18) > ul > li:nth-child(2) > a',
        siteAdminSubscription: '#menu > li:nth-child(18) > ul > li:nth-child(3) > a',
        siteAdminPermissions: '#menu > li:nth-child(18) > ul > li:nth-child(4) > a',
        siteAdminEmailAccounts: '#menu > li:nth-child(18) > ul > li:nth-child(5) > a',
        siteAdminYearEndCloseout: '#menu > li:nth-child(18) > ul > li:nth-child(6) > a',
        //System Logs
        systemLogs: '#menu > li:nth-child(18) > ul > a:nth-child(7)',
        systemLogsSiteUsage: '#menu > li:nth-child(18) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        systemLogsDailyOverview: '#menu > li:nth-child(18) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        systmeLogsSecurityLogs: '#menu > li:nth-child(18) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        //Connections
        connections: '#menu > li:nth-child(18) > ul > a:nth-child(9)',
        connectionsIntegrations: '#menu > li:nth-child(18) > ul > ul:nth-child(10) > li:nth-child(1) > a',
        connectionsWebHooks: '#menu > li:nth-child(18) > ul > ul:nth-child(10) > li:nth-child(2) > a',
        //Import Data
        importData: '#menu > li:nth-child(18) > ul > a:nth-child(11)',
        importDataMigrationWizard: '#menu > li:nth-child(18) > ul > ul:nth-child(12) > li:nth-child(1) > a',
        importDataStudentPhotos: '#menu > li:nth-child(18) > ul > ul:nth-child(12) > li:nth-child(2) > a',
        importDataEmployeePhotos: '#menu > li:nth-child(18) > ul > ul:nth-child(12) > li:nth-child(3) > a',
        importDataMiscellaneous: '#menu > li:nth-child(18) > ul > ul:nth-child(12) > li:nth-child(4) > a',
        //My School Menu
        mySchool: '#menu > li:nth-child(20) > a',
        myClasses: '#menu > li:nth-child(20) > ul > li:nth-child(1) > a',
        myStudents: '#menu > li:nth-child(20) > ul > li:nth-child(2) > a',
        myServiceLogs: '#menu > li:nth-child(20) > ul > li:nth-child(3) > a',
        myLessonPlans: '#menu > li:nth-child(20) > ul > li:nth-child(4) > a',
        myDisciplineLogs: '#menu > li:nth-child(20) > ul > li:nth-child(5) > a',
        myConnectionLogs: '#menu > li:nth-child(20) > ul > li:nth-child(6) > a',
        myNotifications: '#menu > li:nth-child(20) > ul > li:nth-child(7) > a',
        myWorkFlow: '#menu > li:nth-child(20) > ul > li:nth-child(8) > a',
        myTimecard: '#menu > li:nth-child(20) > ul > li:nth-child(9) > a',
        myEmployees: '#menu > li:nth-child(20) > ul > li:nth-child(10) > a',
        staffDiscussions: '#menu > li:nth-child(20) > ul > li:nth-child(11) > a',
        schoolSchedule: '#menu > li:nth-child(20) > ul > li:nth-child(12) > a',
        //My Organizer Menu
        myOrganizer: '#menu > li:nth-child(21) > a',
        myDesktop: '#menu > li:nth-child(21) > ul > li:nth-child(1) > a',
        myTasks: '#menu > li:nth-child(21) > ul > li:nth-child(2) > a',
        myCalendar: '#menu > li:nth-child(21) > ul > li:nth-child(3) > a',
        myDocuments: '#menu > li:nth-child(21) > ul > li:nth-child(4) > a',
        myAddressBook: '#menu > li:nth-child(21) > ul > li:nth-child(5) > a',
        myPhotoAlbums: '#menu > li:nth-child(21) > ul > li:nth-child(6) > a',
        myMemos: '#menu > li:nth-child(21) > ul > li:nth-child(7) > a',
        myFavoriteLinks: '#menu > li:nth-child(21) > ul > li:nth-child(8) > a',
        myDailyJournal: '#menu > li:nth-child(21) > ul > li:nth-child(9) > a',
        //My Utilties Menu
        myUtilities: '#menu > li:nth-child(21) > ul > a',
        myUtilitiesOptions: '#menu > li:nth-child(21) > ul > ul > li:nth-child(1) > a',
        myUtilitiesCategories: '#menu > li:nth-child(21) > ul > ul > li:nth-child(2) > a',
        myUtilitiesImport: '#menu > li:nth-child(21) > ul > ul > li:nth-child(3) > a',
        myUtilitiesApplications: '#menu > li:nth-child(21) > ul > ul > li:nth-child(4) > a',
        myUtilitiesWebHooks: '#menu > li:nth-child(21) > ul > ul > li:nth-child(5) > a',
        //My Organizer Menu Items
        myPassword: '#menu > li:nth-child(21) > ul > li:nth-child(12) > a',
        //My Accounting Menu
        myAccounting: '#menu > li:nth-child(22) > a',
        myAccountingCafetieria: '#menu > li:nth-child(22) > ul > li:nth-child(1) > a',
        myAccountingExpenseReports: '#menu > li:nth-child(22) > ul > li:nth-child(2) > a',
        //My Resources Menu
        myResources: '#menu > li:nth-child(23)',
        myResourcesNews: '#menu > li:nth-child(23) > ul > li:nth-child(1) > a',
        myResourcesPhotos: '#menu > li:nth-child(23) > ul > li:nth-child(2) > a',
        myResourcesDocuments: '#menu > li:nth-child(23) > ul > li:nth-child(3) > a',
        myResourcesOnlineTests: '#menu > li:nth-child(23) > ul > li:nth-child(4) > a',
        myResourcesGradeBook: '#menu > li:nth-child(23) > ul > li:nth-child(5) > a',
        //My Communications Menu
        myCommunication: '#menu > li:nth-child(24)',
        myBatchEmail: '#menu > li:nth-child(24) > ul > li:nth-child(1) > a',
        myBlogs: '#menu > li:nth-child(24) > ul > li:nth-child(2) > a',
        //Pass-A-Note Menu
        passANote: '#menu > li:nth-child(25)',
        passANoteInbox: '#menu > li:nth-child(25) > ul > li:nth-child(1) > a',
        passANoteOutbox: '#menu > li:nth-child(25) > ul > li:nth-child(2) > a',
        passANoteEmployees: '#menu > li:nth-child(25) > ul > li:nth-child(3) > a',
        passANoteAssociates: '#menu > li:nth-child(25) > ul > li:nth-child(4) > a',
        passANoteFamilies: '#menu > li:nth-child(25) > ul > li:nth-child(5) > a',
        passANoteStudents: '#menu > li:nth-child(25) > ul > li:nth-child(6) > a',
        passANoteOptions: '#menu > li:nth-child(25) > ul > li:nth-child(7) > a',
        //Email Menu
        email: '#menu > li:nth-child(26)',
        emailInbox: '#menu > li:nth-child(26) > ul > li:nth-child(1) > a',
        emailFolders: '#menu > li:nth-child(26) > ul > li:nth-child(2) > a',
        emailCompose: '#menu > li:nth-child(26) > ul > li:nth-child(3) > a',
        emailPreferences: '#menu > li:nth-child(26) > ul > li:nth-child(4) > a',
        emailAccounts: '#menu > li:nth-child(26) > ul > li:nth-child(5) > a',
        //Logout
        logout: '#menu > li:nth-child(28) > a',
    }
};
