module.exports = {
    elements: {
        //School Menu
        school: '#menu > li:nth-child(1) > a',
        schoolNews: '#menu > li:nth-child(1) > ul > li:nth-child(1) > a',
        schoolCalendar: '#menu > li:nth-child(1) > ul > li:nth-child(2) > a',
        schoolDocuments: '#menu > li:nth-child(1) > ul > li:nth-child(3) > a',
        schoolPhotoAlbums: '#menu > li:nth-child(1) > ul > li:nth-child(4) > a',
        schoolMultimedia: '#menu > li:nth-child(1) > ul > li:nth-child(5) > a',
        schoolFavorites: '#menu > li:nth-child(1) > ul > li:nth-child(6) > a',
        //Front Desk Menu
        frontDesk: '#menu > li:nth-child(2) > a',
        frontDeskFamilyDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(1) > a',
        frontDeskEmployeeDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(2) > a',
        frontDeskClassroomDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(3) > a',
        frontDeskDepartments: '#menu > li:nth-child(2) > ul > li:nth-child(4) > a',
        frontDeskFacility: '#menu > li:nth-child(2) > ul > li:nth-child(5) > a',
        //Info Center Menu
        infoCenter: '#menu > li:nth-child(3) > a',
        infoCenterLibrary: '#menu > li:nth-child(3) > ul > li:nth-child(1) > a',
        infoCenterCafeteria: '#menu > li:nth-child(3) > ul > li:nth-child(2) > a',
        infoCenterOnlineAuctions: '#menu > li:nth-child(3) > ul > li:nth-child(3) > a',
        infoCenterDatabases: '#menu > li:nth-child(3) > ul > li:nth-child(4) > a',
        infoCenterOnlineForms: '#menu > li:nth-child(3) > ul > li:nth-child(5) > a',
        infoCenterEventRegistration: '#menu > li:nth-child(3) > ul > li:nth-child(6) > a',
        infoCenterKnowledgebase: '#menu > li:nth-child(3) > ul > li:nth-child(7) > a',
        //Comm Center Menu
        commCenter: '#menu > li:nth-child(4) > a',
        commCenterBlogs: '#menu > li:nth-child(4) > ul > li:nth-child(1) > a',
        commCenterDiscussions: '#menu > li:nth-child(4) > ul > li:nth-child(2) > a',
        //Address Book Menu
        addressBook: '#menu > li:nth-child(6) > a',
        addressBookByLastName: '#menu > li:nth-child(6) > ul > li:nth-child(1) > a',
        addressBookByCompany: '#menu > li:nth-child(6) > ul > li:nth-child(2) > a',
        addressBookCategories: '#menu > li:nth-child(6) > ul > li:nth-child(3) > a',
        addressBookAdditionalFields: '#menu > li:nth-child(6) > ul > li:nth-child(4) > a',
        addressBookReports: '#menu > li:nth-child(6) > ul > li:nth-child(5) > a',
        //Communication Menu
        communication: '#menu > li:nth-child(7) > a',
        //Communicaton Homepage
        communicationHomepage: '#menu > li:nth-child(7) > ul > a:nth-child(1)',
        communicationHomepagePolling: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        communicationHomepageFlashNews: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        communicationHomepageSponsorAds: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        communicationHomepageRequest: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        communicationHomepageMsgOfTheDay: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(5) > a',
        //Communication Batch Email
        communicationBatchEmail: '#menu > li:nth-child(7) > ul > a:nth-child(3)',
        communicationBatchEmailCompose: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        communicationBatchEmailDrafts: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        communicationBatchEmailScheduled: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        communicationBatchEmailSent: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        //Communication Text Messaging
        communicationTextMessaging: '#menu > li:nth-child(7) > ul > a:nth-child(5)',
        communicationTextMessagingBatchTextMessage: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        communicationTextMessagingMessageLogs: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        //Communication Menu Items
        communicationTemplates: '#menu > li:nth-child(7) > ul > li:nth-child(7) > a',
        communicationSafetyAlerts: '#menu > li:nth-child(7) > ul > li:nth-child(8) > a',
        communicationMemoMaker: '#menu > li:nth-child(7) > ul > li:nth-child(9) > a',
        communicationEVerification: '#menu > li:nth-child(7) > ul > li:nth-child(10) > a',
        communicationChecklist: '#menu > li:nth-child(7) > ul > li:nth-child(11) > a',
        communicationNotificationLists: '#menu > li:nth-child(7) > ul > li:nth-child(12) > a',
        communicationConfiguration: '#menu > li:nth-child(7) > ul > li:nth-child(13) > a',
        communicationReports: '#menu > li:nth-child(7) > ul > li:nth-child(14) > a',
        //Administrative Menu
        administrative: '#menu > li:nth-child(8) > a',
        //Administrative Back Office Mgr
        backOfficeMgr: '#menu > li:nth-child(8) > ul > a:nth-child(1)',
        //Back Office Mgr Students
        backOfficeMgrStudents: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > a:nth-child(1)',
        backOfficeMgrStudentsAll: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(1) > a',
        backOfficeMgrStudentsCurrent: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(2) > a',
        backOfficeMgrStudentsTypes: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(3) > a',
        backOfficeMgrStudentsAdditionalFields: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(4) > a',
        backOfficeMgrStudentsCategories: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(5) > a',
        backOfficeMgrStudentsActivites: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(6) > a',
        backOfficeMgrStudentsChecklists: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(7) > a',
        //Back Office Mgr Families
        backOfficeMgrFamilies: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > a:nth-child(3)',
        backOfficeMgrFamiliesAll: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(1) > a',
        backOfficeMgrFamiliesCurrent: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(2) > a',
        backOfficeMgrFamiliesAdditionalFields: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(3) > a',
        backOfficeMgrFamiliesNewFamily: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(4) > a',
        //Back Office Mgr Menu Items
        backOfficeReports: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > li > a',
        //Administrative Attendance
        attendance: '#menu > li:nth-child(8) > ul > a:nth-child(3)',
        //Attendance Menu Items
        attendanceHomeroom: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        attendanceByPeriods: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        attendanceByStudent: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        attendanceByClassroom: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        attendanceByEmployee: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(5) > a',
        attendanceDailyAbsences: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(6) > a',
        attendanceCheckInOut: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(7) > a',
        attendanceRecordTypes: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(8) > a',
        attendanceScale: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(9) > a',
        attendanceReports: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(10) > a',
        //Administrative Administration
        administration: '#menu > li:nth-child(8) > ul > a:nth-child(5)',
        administrationSchoolYears: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        administrationSchoolPeriods: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        administrationGradeLevels: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(3) > a',
        administrationCalendarOptions: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(4) > a',
        administrationReportTemplate: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(5) > a',
        administrationReportArchives: '#menu > li:nth-child(8) > ul > ul:nth-child(6) > li:nth-child(7) > a:nth-child(2)',
        //Administartive Human Resources
        humanReources: '#menu > li:nth-child(8) > ul > a:nth-child(7)',
        humanResourcesEmployees: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        humanResourcesSubstitutes: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        humanResourcesDepartments: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        humanResourcesPositions: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(4) > a',
        humanResourcesTypes: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(5) > a',
        humanResourcesCategories: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(6) > a',
        humanResourcesAdditionalFields: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(7) > a',
        humanResourcesReports: '#menu > li:nth-child(8) > ul > ul:nth-child(8) > li:nth-child(8) > a',
        //Academic Menu
        academic: '#menu > li:nth-child(9) > a',
        //Academic Grade Manager
        gradeMgr: '#menu > li:nth-child(9) > ul > a:nth-child(1)',
        gradeMgrReportCards: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        gradeMgrGradingScales: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        gradeMgrAttributesGrades: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        gradeMgrGradeComments: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        gradeMgrAdditionalFields: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(5) > a',
        gradeMgrGpaScales: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(6) > a',
        gradeMgrRequirements: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(7) > a',
        gradeMgrConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(8) > a',
        gradeMgrReports: '#menu > li:nth-child(9) > ul > ul:nth-child(2) > li:nth-child(9) > a',
        //Academic Classroom Manager
        classroomMgr: '#menu > li:nth-child(9) > ul > a:nth-child(3)',
        classroomMgrDayLong: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        classroomMgrPeriodLong: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        classroomMgrGeneral: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        classroomMgrAdditionalFields: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        classroomMgrConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(5) > a',
        classroomMgrReports: '#menu > li:nth-child(9) > ul > ul:nth-child(4) > li:nth-child(6) > a',
        //Academic Resource Manager
        resourceMgr: '#menu > li:nth-child(9) > ul > a:nth-child(5)',
        resourceMgrNews: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        resourceMgrPhotos: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        resourceMgrDocuments: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(3) > a',
        resourceMgrOnlineTests: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(4) > a',
        resourceMgrBlogs: '#menu > li:nth-child(9) > ul > ul:nth-child(6) > li:nth-child(5) > a',
        //Academic Transcript Manager
        transcriptMgr: '#menu > li:nth-child(9) > ul > a:nth-child(7)',
        transcriptMgrStudents: '#menu > li:nth-child(9) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        transcriptMgrTemplates: '#menu > li:nth-child(9) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        transcriptMgrConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        //Academic Curriculum Manager
        curriculumMgr: '#menu > li:nth-child(9) > ul > a:nth-child(9)',
        curriculumMgrBySubject: '#menu > li:nth-child(9) > ul > ul:nth-child(10) > li:nth-child(1) > a',
        curriculumMgrByGrade: '#menu > li:nth-child(9) > ul > ul:nth-child(10) > li:nth-child(2) > a',
        //Academic Assessment Manager
        assessmentMgr: '#menu > li:nth-child(9) > ul > a:nth-child(11)',
        assessmentMgrSkillSets: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(1) > a',
        assessmentMgrStandards: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(2) > a',
        assessmentMgrAssessments: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(3) > a',
        assessmentMgrAchievements: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(4) > a',
        assessmentMgrStandardizedTests: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(5) > a',
        assessmentMgrLessonPlans: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > a',
        assessmentMgrLessonPlansByDay: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > ul > li:nth-child(1) > a',
        assessmentMgrLessonPlansByClass: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > ul > li:nth-child(2) > a',
        assessmentMgrLessonPlansConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > ul > li:nth-child(3) > a',
        assessmentMgrReports: '#menu > li:nth-child(9) > ul > ul:nth-child(12) > li:nth-child(8) > a',
        //Academic IEP Manager
        iepMgr: '#menu > li:nth-child(9) > ul > a:nth-child(13)',
        iepMgrStudents: '#menu > li:nth-child(9) > ul > ul:nth-child(14) > li:nth-child(1) > a',
        iepMgrCoordinators: '#menu > li:nth-child(9) > ul > ul:nth-child(14) > li:nth-child(2) > a',
        iepMgrConfiguration: '#menu > li:nth-child(9) > ul > ul:nth-child(14) > li:nth-child(3) > a',
        iepMgrReports: '#menu > li:nth-child(9) > ul > ul:nth-child(14) > li:nth-child(4) > a',
        //Academic College Credit Manager
        collegeCreditMgr: '#menu > li:nth-child(9) > ul > a:nth-child(15)',
        collegeCreditMgrStudents: '#menu > li:nth-child(9) > ul > ul:nth-child(16) > li:nth-child(1) > a',
        collegeCreditMgrColleges: '#menu > li:nth-child(9) > ul > ul:nth-child(16) > li:nth-child(2) > a'
    }
};
