module.exports = {
    elements: {
        home: {
            selector: 'ul.breadcrumb li.active a',
        },
        school: '#menu > li:nth-child(1) > a',
        frontDesk: '#menu > li:nth-child(2) > a',
        frontDeskFamilyDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(1) > a',
        frontDeskEmployeeDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(2) > a',
        frontDeskClassroomDirectory: '#menu > li:nth-child(2) > ul > li:nth-child(3) > a',
        frontDeskDepartments: '#menu > li:nth-child(2) > ul > li:nth-child(4) > a',
        commCenter: '#menu > li:nth-child(3) > a',
        commCenterBlogs: '#menu > li:nth-child(3) > ul > li:nth-child(1) > a',
        commCenterDiscussions: '#menu > li:nth-child(3) > ul > li:nth-child(2) > a',
        communication: '#menu > li:nth-child(5) > a',
        homepage: '#menu > li:nth-child(5) > ul > a:nth-child(1)',
        polling: '#menu > li:nth-child(5) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        flashNews: '#menu > li:nth-child(5) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        sponsorAds: '#menu > li:nth-child(5) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        request: '#menu > li:nth-child(5) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        msgOfTheDay: '#menu > li:nth-child(5) > ul > ul:nth-child(2) > li:nth-child(5) > a',
        batchEmail: '#menu > li:nth-child(5) > ul > a:nth-child(3)',
        compose: '#menu > li:nth-child(5) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        drafts: '#menu > li:nth-child(5) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        scheduled: '#menu > li:nth-child(5) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        sent: '#menu > li:nth-child(5) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        textMessaging: '#menu > li:nth-child(5) > ul > a:nth-child(5)',
        batchTextMessage: '#menu > li:nth-child(5) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        messageLogs: '#menu > li:nth-child(5) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        templates: '#menu > li:nth-child(5) > ul > li:nth-child(7) > a',
        safetyAlerts: '#menu > li:nth-child(5) > ul > li:nth-child(8) > a',
        memoMaker: '#menu > li:nth-child(5) > ul > li:nth-child(9) > a',
        eVerification: '#menu > li:nth-child(5) > ul > li:nth-child(10) > a',
        checklist: '#menu > li:nth-child(5) > ul > li:nth-child(11) > a',
        notificationLists: '#menu > li:nth-child(5) > ul > li:nth-child(12) > a',
        configuration: '#menu > li:nth-child(5) > ul > li:nth-child(13) > a',
        reports: '#menu > li:nth-child(5) > ul > li:nth-child(14) > a',
        administrative: '#menu > li:nth-child(6) > a',
        backOffice: '#menu > li:nth-child(6) > ul > a:nth-child(1)',
        students: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > a:nth-child(1)',
        studentsAll: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(1) > a',
        studentsCurrent: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(2) > a',
        studentsTypes: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(3) > a',
        studentsAdditionalFields: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(4) > a',
        studentsCategories: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(5) > a',
        studentsActivites: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(6) > a',
        studentsChecklists: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(2) > li:nth-child(7) > a',
        families: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > a:nth-child(3)',
        familiesAll: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(1) > a',
        familiesCurrent: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(2) > a',
        familiesAdditionalFields: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(3) > a',
        familiesNewFamily: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > ul:nth-child(4) > li:nth-child(4) > a',
        reports: '#menu > li:nth-child(6) > ul > ul:nth-child(2) > li > a',
        attendance: '#menu > li:nth-child(6) > ul > a:nth-child(3)',
        homeroom: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        byPeriods: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        byStudent: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        byClassroom: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        byEmployee: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(5) > a',
        dailyAbsences: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(6) > a',
        checkInOut: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(7) > a',
        recordTypes: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(8) > a',
        attendanceScale: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(9) > a',
        attendanceReports: '#menu > li:nth-child(6) > ul > ul:nth-child(4) > li:nth-child(10) > a',
        administration: '#menu > li:nth-child(6) > ul > a:nth-child(5)',
        schoolYears: '#menu > li:nth-child(6) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        schoolPeriods: '#menu > li:nth-child(6) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        gradeLevels: '#menu > li:nth-child(6) > ul > ul:nth-child(6) > li:nth-child(3) > a',
        calendarOptions: '#menu > li:nth-child(6) > ul > ul:nth-child(6) > li:nth-child(4) > a',
        reportTemplate: '#menu > li:nth-child(6) > ul > ul:nth-child(6) > li:nth-child(5) > a',
        reportArchives: '#menu > li:nth-child(6) > ul > ul:nth-child(6) > li:nth-child(7) > a:nth-child(2)',
        humanReources: '#menu > li:nth-child(6) > ul > a:nth-child(7)',
        employees: '#menu > li:nth-child(6) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        substitutes: '#menu > li:nth-child(6) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        departments: '#menu > li:nth-child(6) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        positions: '#menu > li:nth-child(6) > ul > ul:nth-child(8) > li:nth-child(4) > a',
        hrTypes: '#menu > li:nth-child(6) > ul > ul:nth-child(8) > li:nth-child(5) > a',
        hrCategories: '#menu > li:nth-child(6) > ul > ul:nth-child(8) > li:nth-child(6) > a',
        hrAdditionalFields: '#menu > li:nth-child(6) > ul > ul:nth-child(8) > li:nth-child(7) > a',
        hrReports: '#menu > li:nth-child(6) > ul > ul:nth-child(8) > li:nth-child(8) > a',
        academic: '#menu > li:nth-child(7) > a',
        gradeMgr: '#menu > li:nth-child(7) > ul > a:nth-child(1)',
        gradeMgrReportCards: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        gradeMgrGradingScales: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        gradeMgrAttributesGrades: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        gradeMgrGradeComments: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        gradeMgrAdditionalFields: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(5) > a',
        gradeMgrGpaScales: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(6) > a',
        gradeMgrequirements: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(7) > a',
        gradeMgrConfiguration: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(8) > a',
        gradeMgrReports: '#menu > li:nth-child(7) > ul > ul:nth-child(2) > li:nth-child(9) > a',
        classroomMgr: '#menu > li:nth-child(7) > ul > a:nth-child(3)',
        classroomMgrDayLong: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        classroomMgrPeriodLong: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        classroomMgrGeneral: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        classroomMgrAdditionalFields: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        classroomMgrConfiguration: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(5) > a',
        classroomMgrReports: '#menu > li:nth-child(7) > ul > ul:nth-child(4) > li:nth-child(6) > a',
        resourceMgr: '#menu > li:nth-child(7) > ul > a:nth-child(5)',
        resourceMgrNews: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(1) > a',
        resourceMgrPhotos: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(2) > a',
        resourceMgrDocuments: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(3) > a',
        resourceMgrOnlineTests: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(4) > a',
        resourceMgrBlogs: '#menu > li:nth-child(7) > ul > ul:nth-child(6) > li:nth-child(5) > a',
        transcriptMgr: '#menu > li:nth-child(7) > ul > a:nth-child(7)',
        transcriptMgrStudents: '#menu > li:nth-child(7) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        transcriptMgrTemplates: '#menu > li:nth-child(7) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        transcriptMgrConfiguration: '#menu > li:nth-child(7) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        curriculumMgr: '#menu > li:nth-child(7) > ul > a:nth-child(9)',
        curriculumMgrBySubject: '#menu > li:nth-child(7) > ul > ul:nth-child(10) > li:nth-child(1) > a',
        curriculumMgrByGrade: '#menu > li:nth-child(7) > ul > ul:nth-child(10) > li:nth-child(2) > a',
        assessmentMgr: '#menu > li:nth-child(7) > ul > a:nth-child(11)',
        assessmentMgrSkillSets: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > li:nth-child(1) > a',
        assessmentMgrStandards: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > li:nth-child(2) > a',
        assessmentMgrAssessments: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > li:nth-child(3) > a',
        assessmentMgrStandardizedTests: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > li:nth-child(5) > a',
        assessmentMgrLessonPlans: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > a',
        assessmentMgrLessonPlansByDay: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > ul > li:nth-child(1) > a',
        assessmentMgrLessonPlansByClass: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > ul > li:nth-child(2) > a',
        assessmentMgrLessonPlansConfiguration: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > ul > li:nth-child(3) > a',
        assessmentMgrReports: '#menu > li:nth-child(7) > ul > ul:nth-child(12) > li:nth-child(8) > a',
        specialties: '#menu > li:nth-child(8) > a',
        athleticDirector: '#menu > li:nth-child(8) > ul > a:nth-child(1)',
        sports: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > li:nth-child(1) > a',
        teams: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > li:nth-child(2) > a',
        scoreboard: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > li:nth-child(3) > a',
        equiptment: '#menu > li:nth-child(8) > ul > ul:nth-child(2) > li:nth-child(4) > a',
        ptConferences: '#menu > li:nth-child(8) > ul > a:nth-child(3)',
        ptConferencesTeachers: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(1) > a',
        ptConferencesByDate: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(2) > a',
        ptConferencesByTeacher: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(3) > a',
        ptConferencesConfiguration: '#menu > li:nth-child(8) > ul > ul:nth-child(4) > li:nth-child(4) > a',
        utilities: '#menu > li:nth-child(9) > a',
        onlineFormMgr: '#menu > li:nth-child(9) > ul > a',
        onlineFormMgrActive: '#menu > li:nth-child(9) > ul > ul > li:nth-child(1) > a',
        onlineFormMgrNonActive: '#menu > li:nth-child(9) > ul > ul > li:nth-child(2) > a',
        systemHelp: '#menu > li:nth-child(10) > a',
        welcomeAboard: '#menu > li:nth-child(10) > ul > li:nth-child(1) > a',
        onlineHelp: '#menu > li:nth-child(10) > ul > li:nth-child(2) > a',
        trainingVideos: '#menu > li:nth-child(10) > ul > li:nth-child(3) > a',
        webinarTraining: '#menu > li:nth-child(10) > ul > li:nth-child(4) > a',
        sycamoreLeafNotes: '#menu > li:nth-child(10) > ul > li:nth-child(5) > a',
        releaseNotes: '#menu > li:nth-child(10) > ul > li:nth-child(6) > a',
        systemSupport: '#menu > li:nth-child(12) > a',
        openTickets: '#menu > li:nth-child(12) > ul > li:nth-child(1) > a',
        closedTickets: '#menu > li:nth-child(12) > ul > li:nth-child(2) > a',
        siteAdmin: '#menu > li:nth-child(13) > a',
        information: '#menu > li:nth-child(13) > ul > li:nth-child(1) > a',
        configuration: '#menu > li:nth-child(13) > ul > li:nth-child(2) > a',
        subscription: '#menu > li:nth-child(13) > ul > li:nth-child(3) > a',
        permissions: '#menu > li:nth-child(13) > ul > li:nth-child(4) > a',
        emailAccounts: '#menu > li:nth-child(13) > ul > li:nth-child(5) > a',
        yearEndCloseout: '#menu > li:nth-child(13) > ul > li:nth-child(6) > a',
        systemLogs: '#menu > li:nth-child(13) > ul > a:nth-child(7)',
        siteUsage: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(1) > a',
        dailyOverview: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(2) > a',
        securityLogs: '#menu > li:nth-child(13) > ul > ul:nth-child(8) > li:nth-child(3) > a',
        connections: '#menu > li:nth-child(13) > ul > a:nth-child(9)',
        integrations: '#menu > li:nth-child(13) > ul > ul:nth-child(10) > li:nth-child(1) > a',
        webHooks: '#menu > li:nth-child(13) > ul > ul:nth-child(10) > li:nth-child(2) > a',
        siteAdmin: '#menu > li:nth-child(13) > a',
        migrationWizard: '#menu > li:nth-child(13) > ul > ul:nth-child(12) > li:nth-child(1) > a',
        studentPhotos: '#menu > li:nth-child(13) > ul > ul:nth-child(12) > li:nth-child(2) > a',
        employeePhotos: '#menu > li:nth-child(13) > ul > ul:nth-child(12) > li:nth-child(3) > a',
        miscellaneous: '#menu > li:nth-child(13) > ul > ul:nth-child(12) > li:nth-child(4) > a',
        mySchool: '#menu > li:nth-child(15) > a',
        myClasses: '#menu > li:nth-child(15) > ul > li:nth-child(1) > a',
        myStudents: '#menu > li:nth-child(15) > ul > li:nth-child(2) > a',
        myLessonPlans: '#menu > li:nth-child(15) > ul > li:nth-child(3) > a',
        myNotifications: '#menu > li:nth-child(15) > ul > li:nth-child(4) > a',
        myEmployees: '#menu > li:nth-child(15) > ul > li:nth-child(5) > a',
        staffDiscussions: '#menu > li:nth-child(15) > ul > li:nth-child(6) > a',
        schoolSchedule: '#menu > li:nth-child(15) > ul > li:nth-child(7) > a',
        myOrganizer: '#menu > li:nth-child(16) > a',
        myDesktop: '#menu > li:nth-child(16) > ul > li:nth-child(1) > a',
        myTasks: '#menu > li:nth-child(16) > ul > li:nth-child(2) > a',
        myCalendar: '#menu > li:nth-child(16) > ul > li:nth-child(3) > a',
        myDocuments: '#menu > li:nth-child(16) > ul > li:nth-child(4) > a',
        myAddressBook: '#menu > li:nth-child(16) > ul > li:nth-child(5) > a',
        myPhotoAlbums: '#menu > li:nth-child(16) > ul > li:nth-child(6) > a',
        myMemos: '#menu > li:nth-child(16) > ul > li:nth-child(7) > a',
        myFavoriteLinks: '#menu > li:nth-child(16) > ul > li:nth-child(8) > a',
        myDailyJournal: '#menu > li:nth-child(16) > ul > li:nth-child(9) > a',
        myUtilities: '#menu > li:nth-child(16) > ul > a',
        myUtilitiesOptions: '#menu > li:nth-child(16) > ul > ul > li:nth-child(1) > a',
        myUtilitiesCategories: '#menu > li:nth-child(16) > ul > ul > li:nth-child(2) > a',
        myUtilitiesImport: '#menu > li:nth-child(16) > ul > ul > li:nth-child(3) > a',
        myUtilitiesApplications: '#menu > li:nth-child(16) > ul > ul > li:nth-child(4) > a',
        myUtilitiesWebHooks: '#menu > li:nth-child(16) > ul > ul > li:nth-child(5) > a',
        myUtilitiesPassword: '#menu > li:nth-child(16) > ul > li:nth-child(12) > a',
        myAccounting: '#menu > li:nth-child(17) > a',
        myAccountingCafetieria: '#menu > li:nth-child(17) > ul > li:nth-child(1) > a',
        myAccountingExpenseReports: '#menu > li:nth-child(17) > ul > li:nth-child(2) > a',
        myResources: '#menu > li:nth-child(18) > a',
        myResourcesNews: '#menu > li:nth-child(18) > ul > li:nth-child(1) > a',
        myResourcesPhotos: '#menu > li:nth-child(18) > ul > li:nth-child(2) > a',
        myResourcesDocuments: '#menu > li:nth-child(18) > ul > li:nth-child(3) > a',
        myResourcesOnlineTests: '#menu > li:nth-child(18) > ul > li:nth-child(4) > a',
        myResourcesGradeBook: '#menu > li:nth-child(18) > ul > li:nth-child(5) > a',
        myCommunication: '#menu > li:nth-child(19) > a',
        myBatchEmail: '#menu > li:nth-child(19) > ul > li:nth-child(1) > a',
        myBlogs: '#menu > li:nth-child(19) > ul > li:nth-child(2) > a',
        passANote: '#menu > li:nth-child(20) > a',
        passANoteInbox: '#menu > li:nth-child(20) > ul > li:nth-child(1) > a',
        passANoteOutbox: '#menu > li:nth-child(20) > ul > li:nth-child(2) > a',
        passANoteEmployees: '#menu > li:nth-child(20) > ul > li:nth-child(3) > a',
        passANoteAssociates: '#menu > li:nth-child(20) > ul > li:nth-child(4) > a',
        passANoteOptions: '#menu > li:nth-child(20) > ul > li:nth-child(5) > a',
        logout: '#menu > li:nth-child(22) > a',
        spiritStore: '#menu > li:nth-child(23) > a',
    }
};
