module.exports = {
    tags: ['academicTest', 'menuTests'],

    'Academic Menu Test': (client) => {

        var page = client.page.login();

        page.navigate()
            .schoolLogin('superuser', 'guest', '1');

        client.frame(1);
        client.page.menu()
            .assert.visible('@academic')
            .assert.containsText('@academic', '\273 Academic')
            .assert.attributeEquals('@academic', 'href', page.url() + '/schoolmenu.php#')

            .assert.hidden('@gradeMgr')
            .assert.hidden('@gradeMgrReportCards')
            .assert.hidden('@gradeMgrGradingScales')
            .assert.hidden('@gradeMgrAttributesGrades')
            .assert.hidden('@gradeMgrGradeComments')
            .assert.hidden('@gradeMgrAdditionalFields')
            .assert.hidden('@gradeMgrGpaScales')
            .assert.hidden('@gradeMgrRequirements')
            .assert.hidden('@gradeMgrConfiguration')
            .assert.hidden('@gradeMgrReports')

            .assert.hidden('@classroomMgr')
            .assert.hidden('@classroomMgrDayLong')
            .assert.hidden('@classroomMgrPeriodLong')
            .assert.hidden('@classroomMgrGeneral')
            .assert.hidden('@classroomMgrAdditionalFields')
            .assert.hidden('@classroomMgrConfiguration')
            .assert.hidden('@classroomMgrReports')

            .assert.hidden('@resourceMgr')
            .assert.hidden('@resourceMgrNews')
            .assert.hidden('@resourceMgrPhotos')
            .assert.hidden('@resourceMgrDocuments')
            .assert.hidden('@resourceMgrOnlineTests')
            .assert.hidden('@resourceMgrBlogs')

            .assert.hidden('@transcriptMgr')
            .assert.hidden('@transcriptMgrStudents')
            .assert.hidden('@transcriptMgrTemplates')
            .assert.hidden('@transcriptMgrConfiguration')

            .assert.hidden('@curriculumMgr')
            .assert.hidden('@curriculumMgrByGrade')
            .assert.hidden('@curriculumMgrBySubject')

            .assert.hidden('@assessmentMgr')
            .assert.hidden('@assessmentMgrSkillSets')
            .assert.hidden('@assessmentMgrStandards')
            .assert.hidden('@assessmentMgrAssessments')
            .assert.hidden('@assessmentMgrStandardizedTests')
            .assert.hidden('@assessmentMgrLessonPlans')
            .assert.hidden('@assessmentMgrLessonPlansByDay')
            .assert.hidden('@assessmentMgrLessonPlansByClass')
            .assert.hidden('@assessmentMgrLessonPlansConfiguration')
            .assert.hidden('@assessmentMgrReports')

            .assert.hidden('@iepMgr')
            .assert.hidden('@iepMgrStudents')
            .assert.hidden('@iepMgrCoordinators')
            .assert.hidden('@iepMgrConfiguration')
            .assert.hidden('@iepMgrReports')

            .assert.hidden('@collegeCreditMgr')
            .assert.hidden('@collegeCreditMgrStudents')
            .assert.hidden('@collegeCreditMgrColleges')

            .click('@academic')
            .assert.visible('@academic')
            .assert.visible('@gradeMgr')
            .assert.visible('@classroomMgr')
            .assert.visible('@resourceMgr')
            .assert.visible('@transcriptMgr')
            .assert.visible('@curriculumMgr')
            .assert.visible('@assessmentMgr')
            .assert.visible('@iepMgr')
            .assert.visible('@collegeCreditMgr')
            .assert.containsText('@gradeMgr', 'Grade Mgr')
            .assert.containsText('@classroomMgr', 'Classroom Mgr')
            .assert.containsText('@resourceMgr', 'Resource Mgr')
            .assert.containsText('@transcriptMgr', 'Transcript Mgr')
            .assert.containsText('@curriculumMgr', 'Curriculum Mgr')
            .assert.containsText('@assessmentMgr', 'Assessment Mgr')
            .assert.containsText('@iepMgr', 'IEP Mgr')
            .assert.containsText('@collegeCreditMgr', 'College Credit Mgr')
            .assert.attributeEquals('@gradeMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@classroomMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@resourceMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@transcriptMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@curriculumMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@assessmentMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@iepMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@collegeCreditMgr', 'href', page.url() + '/schoolmenu.php#')

            .click('@gradeMgr')
            .assert.visible('@gradeMgrReportCards')
            .assert.visible('@gradeMgrGradingScales')
            .assert.visible('@gradeMgrAttributesGrades')
            .assert.visible('@gradeMgrGradeComments')
            .assert.visible('@gradeMgrAdditionalFields')
            .assert.visible('@gradeMgrGpaScales')
            .assert.visible('@gradeMgrRequirements')
            .assert.visible('@gradeMgrConfiguration')
            .assert.visible('@gradeMgrReports')
            .assert.containsText('@gradeMgrReportCards', 'Report Cards')
            .assert.containsText('@gradeMgrGradingScales', 'Grading Scales')
            .assert.containsText('@gradeMgrAttributesGrades', 'Attributes Grades')
            .assert.containsText('@gradeMgrGradeComments', 'Grade Comments')
            .assert.containsText('@gradeMgrAdditionalFields', 'Additional Fields')
            .assert.containsText('@gradeMgrGpaScales', 'GPA Scales')
            .assert.containsText('@gradeMgrRequirements', 'Requirements')
            .assert.containsText('@gradeMgrConfiguration', 'Configuration')
            .assert.containsText('@gradeMgrReports', 'Reports')
            .assert.attributeEquals('@gradeMgrReportCards', 'href', page.url() + '/gradecards.php?grade=99')
            .assert.attributeEquals('@gradeMgrGradingScales', 'href', page.url() + '/schoolscale.php')
            .assert.attributeEquals('@gradeMgrAttributesGrades', 'href', page.url() + '/studenthabits.php')
            .assert.attributeEquals('@gradeMgrGradeComments', 'href', page.url() + '/classcomments.php')
            .assert.attributeEquals('@gradeMgrAdditionalFields', 'href', page.url() + '/classgradestatistics.php?task=list')
            .assert.attributeEquals('@gradeMgrGpaScales', 'href', page.url() + '/gpascale.php')
            .assert.attributeEquals('@gradeMgrRequirements', 'href', page.url() + '/classrequirements.php')
            .assert.attributeEquals('@gradeMgrConfiguration', 'href', page.url() + '/gradecfg.php')
            .assert.attributeEquals('@gradeMgrReports', 'href', page.url() + '/reports.php?type=10')

            .click('@gradeMgr')
            .assert.hidden('@gradeMgrReportCards')
            .assert.hidden('@gradeMgrGradingScales')
            .assert.hidden('@gradeMgrAttributesGrades')
            .assert.hidden('@gradeMgrGradeComments')
            .assert.hidden('@gradeMgrAdditionalFields')
            .assert.hidden('@gradeMgrGpaScales')
            .assert.hidden('@gradeMgrRequirements')
            .assert.hidden('@gradeMgrConfiguration')
            .assert.hidden('@gradeMgrReports')

            .click('@classroomMgr')
            .assert.visible('@classroomMgrDayLong')
            .assert.visible('@classroomMgrPeriodLong')
            .assert.visible('@classroomMgrGeneral')
            .assert.visible('@classroomMgrAdditionalFields')
            .assert.visible('@classroomMgrConfiguration')
            .assert.visible('@classroomMgrReports')
            .assert.containsText('@classroomMgrDayLong', 'Day Long')
            .assert.containsText('@classroomMgrPeriodLong', 'Period Long')
            .assert.containsText('@classroomMgrGeneral', 'General')
            .assert.containsText('@classroomMgrAdditionalFields', 'Additional Fields')
            .assert.containsText('@classroomMgrConfiguration', 'Configuration')
            .assert.containsText('@classroomMgrReports', 'Reports')
            .assert.attributeEquals('@classroomMgrDayLong', 'href', page.url() + '/classes.php?task=listelementary')
            .assert.attributeEquals('@classroomMgrPeriodLong', 'href', page.url() + '/classes.php?task=listsecondary')
            .assert.attributeEquals('@classroomMgrGeneral', 'href', page.url() + '/classes.php?task=listgeneral')
            .assert.attributeEquals('@classroomMgrAdditionalFields', 'href', page.url() + '/classstatistics.php?task=list')
            .assert.attributeEquals('@classroomMgrConfiguration', 'href', page.url() + '/classcfg.php')
            .assert.attributeEquals('@classroomMgrReports', 'href', page.url() + '/reports.php?type=7')

            .click('@classroomMgr')
            .assert.hidden('@classroomMgrDayLong')
            .assert.hidden('@classroomMgrPeriodLong')
            .assert.hidden('@classroomMgrGeneral')
            .assert.hidden('@classroomMgrAdditionalFields')
            .assert.hidden('@classroomMgrConfiguration')
            .assert.hidden('@classroomMgrReports')

            .click('@resourceMgr')
            .assert.visible('@resourceMgrNews')
            .assert.visible('@resourceMgrPhotos')
            .assert.visible('@resourceMgrDocuments')
            .assert.visible('@resourceMgrOnlineTests')
            .assert.visible('@resourceMgrBlogs')
            .assert.containsText('@resourceMgrNews', 'News')
            .assert.containsText('@resourceMgrPhotos', 'Photos')
            .assert.containsText('@resourceMgrDocuments', 'Documents')
            .assert.containsText('@resourceMgrOnlineTests', 'Online Tests')
            .assert.containsText('@resourceMgrBlogs', 'Blogs')
            .assert.attributeEquals('@resourceMgrNews', 'href', page.url() + '/onlinenews.php')
            .assert.attributeEquals('@resourceMgrPhotos', 'href', page.url() + '/onlinephotos.php')
            .assert.attributeEquals('@resourceMgrDocuments', 'href', page.url() + '/onlinedocuments.php')
            .assert.attributeEquals('@resourceMgrOnlineTests', 'href', page.url() + '/onlinetests.php')
            .assert.attributeEquals('@resourceMgrBlogs', 'href', page.url() + '/onlineblogs.php')

            .click('@resourceMgr')
            .assert.hidden('@resourceMgrNews')
            .assert.hidden('@resourceMgrPhotos')
            .assert.hidden('@resourceMgrDocuments')
            .assert.hidden('@resourceMgrOnlineTests')
            .assert.hidden('@resourceMgrBlogs')

            .click('@transcriptMgr')
            .assert.visible('@transcriptMgrStudents')
            .assert.visible('@transcriptMgrTemplates')
            .assert.visible('@transcriptMgrConfiguration')
            .assert.containsText('@transcriptMgrStudents', 'Students')
            .assert.containsText('@transcriptMgrTemplates', 'Templates')
            .assert.containsText('@transcriptMgrConfiguration', 'Configuration')
            .assert.attributeEquals('@transcriptMgrStudents', 'href', page.url() + '/transcripts.php')
            .assert.attributeEquals('@transcriptMgrTemplates', 'href', page.url() + '/transcript_editor.php')
            .assert.attributeEquals('@transcriptMgrConfiguration', 'href', page.url() + '/transcriptcfg.php')

            .click('@transcriptMgr')
            .assert.hidden('@transcriptMgrStudents')
            .assert.hidden('@transcriptMgrTemplates')
            .assert.hidden('@transcriptMgrConfiguration')

            .click('@curriculumMgr')
            .assert.visible('@curriculumMgrByGrade')
            .assert.visible('@curriculumMgrBySubject')
            .assert.containsText('@curriculumMgrByGrade', 'by Grade')
            .assert.containsText('@curriculumMgrBySubject', 'by Subject')
            .assert.attributeEquals('@curriculumMgrByGrade', 'href', page.url() + '/curriculumcourses.php?type=bygrade')
            .assert.attributeEquals('@curriculumMgrBySubject', 'href', page.url() + '/curriculumcourses.php?type=bysubject')

            .click('@curriculumMgr')
            .assert.hidden('@curriculumMgrByGrade')
            .assert.hidden('@curriculumMgrBySubject')

            .click('@assessmentMgr')
            .assert.visible('@assessmentMgrSkillSets')
            .assert.visible('@assessmentMgrStandards')
            .assert.visible('@assessmentMgrAssessments')
            .assert.visible('@assessmentMgrAchievements')
            .assert.visible('@assessmentMgrStandardizedTests')
            .assert.visible('@assessmentMgrLessonPlans')
            .assert.visible('@assessmentMgrReports')
            .assert.containsText('@assessmentMgrSkillSets', 'Skill Sets')
            .assert.containsText('@assessmentMgrStandards', 'Standards')
            .assert.containsText('@assessmentMgrAssessments', 'Assessments')
            .assert.containsText('@assessmentMgrAchievements', 'Achievements')
            .assert.containsText('@assessmentMgrStandardizedTests', 'Standardized Tests')
            .assert.containsText('@assessmentMgrLessonPlans', 'Lesson Plans')
            .assert.containsText('@assessmentMgrReports', 'Reports')
            .assert.attributeEquals('@assessmentMgrSkillSets', 'href', page.url() + '/gradeskills.php')
            .assert.attributeEquals('@assessmentMgrStandards', 'href', page.url() + '/gradestandards.php?grade=99')
            .assert.attributeEquals('@assessmentMgrAssessments', 'href', page.url() + '/studentassessments.php?grade=99')
            .assert.attributeEquals('@assessmentMgrAchievements', 'href', page.url() + '/achievement.php')
            .assert.attributeEquals('@assessmentMgrStandardizedTests', 'href', page.url() + '/standardizedtests.php')
            .assert.attributeEquals('@assessmentMgrLessonPlans', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@assessmentMgrReports', 'href', page.url() + '/reports.php?type=27')

            .click('@assessmentMgrLessonPlans')
            .assert.visible('@assessmentMgrLessonPlansByDay')
            .assert.visible('@assessmentMgrLessonPlansByClass')
            .assert.visible('@assessmentMgrLessonPlansConfiguration')
            .assert.containsText('@assessmentMgrLessonPlansByDay', 'by Day')
            .assert.containsText('@assessmentMgrLessonPlansByClass', 'by Class')
            .assert.containsText('@assessmentMgrLessonPlansConfiguration', 'Configuration')
            .assert.attributeEquals('@assessmentMgrLessonPlansByDay', 'href', page.url() + '/schoollesson.php?view=byday')
            .assert.attributeEquals('@assessmentMgrLessonPlansByClass', 'href', page.url() + '/schoollesson.php?view=byclass')
            .assert.attributeEquals('@assessmentMgrLessonPlansConfiguration', 'href', page.url() + '/schoollessoncfg.php')

            .click('@assessmentMgrLessonPlans')
            .assert.hidden('@assessmentMgrLessonPlansByDay')
            .assert.hidden('@assessmentMgrLessonPlansByClass')
            .assert.hidden('@assessmentMgrLessonPlansConfiguration')

            .click('@assessmentMgr')
            .assert.hidden('@assessmentMgrSkillSets')
            .assert.hidden('@assessmentMgrStandards')
            .assert.hidden('@assessmentMgrAssessments')
            .assert.hidden('@assessmentMgrAchievements')
            .assert.hidden('@assessmentMgrStandardizedTests')
            .assert.hidden('@assessmentMgrLessonPlans')
            .assert.hidden('@assessmentMgrReports')

            .click('@iepMgr')
            .assert.visible('@iepMgrStudents')
            .assert.visible('@iepMgrCoordinators')
            .assert.visible('@iepMgrConfiguration')
            .assert.visible('@iepMgrReports')
            .assert.containsText('@iepMgrStudents', 'Students')
            .assert.containsText('@iepMgrCoordinators', 'Coordinators')
            .assert.containsText('@iepMgrConfiguration', 'Configuration')
            .assert.containsText('@iepMgrReports', 'Reports')
            .assert.attributeEquals('@iepMgrStudents', 'href', page.url() + '/studentiep.php?grade=99')
            .assert.attributeEquals('@iepMgrCoordinators', 'href', page.url() + '/studentiepteam.php')
            .assert.attributeEquals('@iepMgrConfiguration', 'href', page.url() + '/studentiepcfg.php')
            .assert.attributeEquals('@iepMgrReports', 'href', page.url() + '/reports.php?type=29')

            .click('@iepMgr')
            .assert.hidden('@iepMgrStudents')
            .assert.hidden('@iepMgrCoordinators')
            .assert.hidden('@iepMgrConfiguration')
            .assert.hidden('@iepMgrReports')

            .click('@collegeCreditMgr')
            .assert.visible('@collegeCreditMgrStudents')
            .assert.visible('@collegeCreditMgrColleges')
            .assert.containsText('@collegeCreditMgrStudents', 'Students')
            .assert.containsText('@collegeCreditMgrColleges', 'Colleges')
            .assert.attributeEquals('@collegeCreditMgrStudents', 'href', page.url() + '/collegecredits.php?task=students')
            .assert.attributeEquals('@collegeCreditMgrColleges', 'href', page.url() + '/collegecredits.php?task=colleges')

            .click('@academic')

            .assert.hidden('@gradeMgr')
            .assert.hidden('@gradeMgrReportCards')
            .assert.hidden('@gradeMgrGradingScales')
            .assert.hidden('@gradeMgrAttributesGrades')
            .assert.hidden('@gradeMgrGradeComments')
            .assert.hidden('@gradeMgrAdditionalFields')
            .assert.hidden('@gradeMgrGpaScales')
            .assert.hidden('@gradeMgrRequirements')
            .assert.hidden('@gradeMgrConfiguration')
            .assert.hidden('@gradeMgrReports')

            .assert.hidden('@classroomMgr')
            .assert.hidden('@classroomMgrDayLong')
            .assert.hidden('@classroomMgrPeriodLong')
            .assert.hidden('@classroomMgrGeneral')
            .assert.hidden('@classroomMgrAdditionalFields')
            .assert.hidden('@classroomMgrConfiguration')
            .assert.hidden('@classroomMgrReports')

            .assert.hidden('@resourceMgr')
            .assert.hidden('@resourceMgrNews')
            .assert.hidden('@resourceMgrPhotos')
            .assert.hidden('@resourceMgrDocuments')
            .assert.hidden('@resourceMgrOnlineTests')
            .assert.hidden('@resourceMgrBlogs')

            .assert.hidden('@transcriptMgr')
            .assert.hidden('@transcriptMgrStudents')
            .assert.hidden('@transcriptMgrTemplates')
            .assert.hidden('@transcriptMgrConfiguration')

            .assert.hidden('@curriculumMgr')
            .assert.hidden('@curriculumMgrByGrade')
            .assert.hidden('@curriculumMgrBySubject')

            .assert.hidden('@assessmentMgr')
            .assert.hidden('@assessmentMgrSkillSets')
            .assert.hidden('@assessmentMgrStandards')
            .assert.hidden('@assessmentMgrAssessments')
            .assert.hidden('@assessmentMgrStandardizedTests')
            .assert.hidden('@assessmentMgrLessonPlans')
            .assert.hidden('@assessmentMgrLessonPlansByDay')
            .assert.hidden('@assessmentMgrLessonPlansByClass')
            .assert.hidden('@assessmentMgrLessonPlansConfiguration')
            .assert.hidden('@assessmentMgrReports')

            .assert.hidden('@iepMgr')
            .assert.hidden('@iepMgrStudents')
            .assert.hidden('@iepMgrCoordinators')
            .assert.hidden('@iepMgrConfiguration')
            .assert.hidden('@iepMgrReports')

            .assert.hidden('@collegeCreditMgr')
            .assert.hidden('@collegeCreditMgrStudents')
            .assert.hidden('@collegeCreditMgrColleges')

        client.frame(null);

        client.end();
    }
};
