module.exports = {
    tags: ['admissionsTest', 'menuTests'],

    'Admissions Menu Test': (client) => {

        var page = client.page.login();

        page.navigate()
            .schoolLogin('superuser', 'guest', '1');

        client.frame(1);
        client.page.menu()
            .assert.visible('@admissions')
            .assert.containsText('@admissions', '\273 Admissions')
            .assert.attributeEquals('@admissions', 'href', 'http://web/schoolmenu.php#')

            .assert.hidden('@inquiries')
            .assert.hidden('@inquiresStudents')
            .assert.hidden('@inquiriesFamilies')

            .assert.hidden('@enrollment')
            .assert.hidden('@enrollmentStudent')
            .assert.hidden('@enrollmentFamilies')

            .assert.hidden('@classMgr')
            .assert.hidden('@classMgrClasses')

            .assert.hidden('@courseMgr')
            .assert.hidden('@courseMgrCourses')
            .assert.hidden('@courseMgrTeachers')
            .assert.hidden('@courseMgrStudents')
            .assert.hidden('@courseMgrFacility')
            .assert.hidden('@courseMgrScheduler')
            .assert.hidden('@courseMgrConfiguration')
            .assert.hidden('@courseMgrReports')

            .assert.hidden('@admissionsCommunication')
            .assert.hidden('@admissionsCommunicationBatchEmail')

            .assert.hidden('@portalMgr')
            .assert.hidden('@portalMgrStudents')
            .assert.hidden('@portalMgrFamilies')
            .assert.hidden('@portalMgrApplications')
            .assert.hidden('@portalMgrEssayQuestions')
            .assert.hidden('@portalMgrRequestedDocs')

            .assert.hidden('@admissionsConfiguration')
            .assert.hidden('@admissionsConfigurationChecklist')
            .assert.hidden('@admissionsConfigurationDocuments')
            .assert.hidden('@admissionsConfigurationAgreements')
            .assert.hidden('@admissionsConfigurationTuitionPlans')
            .assert.hidden('@admissionsConfigurationEnrollStatus')
            .assert.hidden('@admissionsConfigurationSetup')

            .assert.hidden('@admissionsReports')

            .click('@admissions')
            .assert.visible('@inquiries')
            .assert.visible('@enrollment')
            .assert.visible('@classMgr')
            .assert.visible('@courseMgr')
            .assert.visible('@admissionsCommunication')
            .assert.visible('@portalMgr')
            .assert.visible('@admissionsConfiguration')
            .assert.visible('@admissionsReports')
            .assert.containsText('@inquiries', '\273 Inquiries')
            .assert.containsText('@enrollment', '\273 Enrollment')
            .assert.containsText('@classMgr', '\273 Class Mgr')
            .assert.containsText('@courseMgr', '\273 Course Mgr')
            .assert.containsText('@admissionsCommunication', '\273 Communication')
            .assert.containsText('@portalMgr', '\273 Portal Mgr')
            .assert.containsText('@admissionsConfiguration', '\273 Configuration')
            .assert.containsText('@admissionsReports', 'Reports')
            .assert.attributeEquals('@inquiries', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@enrollment', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@classMgr', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@courseMgr', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@admissionsCommunication', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@portalMgr', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@admissionsConfiguration', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@admissionsReports', 'href', 'http://web/reports.php?type=18')

            .click('@inquiries')
            .assert.visible('@inquiresStudents')
            .assert.visible('@inquiriesFamilies')
            .assert.containsText('@inquiresStudents', 'Students')
            .assert.containsText('@inquiriesFamilies', 'Families')
            .assert.attributeEquals('@inquiresStudents', 'href', 'http://web/enrollstudentprospects.php')
            .assert.attributeEquals('@inquiriesFamilies', 'href', 'http://web/enrollfamilyprospects.php')

            .click('@inquiries')
            .assert.hidden('@inquiresStudents')
            .assert.hidden('@inquiriesFamilies')

            .click('@enrollment')
            .assert.visible('@enrollmentStudent')
            .assert.visible('@enrollmentFamilies')
            .assert.containsText('@enrollmentStudent', 'Student')
            .assert.containsText('@enrollmentFamilies', 'Families')
            .assert.attributeEquals('@enrollmentStudent', 'href', 'http://web/enrollstudents.php')
            .assert.attributeEquals('@enrollmentFamilies', 'href', 'http://web/enrollfamilies.php')

            .click('@enrollment')
            .assert.hidden('@enrollmentStudent')
            .assert.hidden('@enrollmentFamilies')

            .click('@classMgr')
            .assert.visible('@classMgrClasses')
            .assert.containsText('@classMgrClasses', 'Classes')
            .assert.attributeEquals('@classMgrClasses', 'href', 'http://web/enrollclasses.php')

            .click('@classMgr')
            .assert.hidden('@classMgrClasses')

            .click('@courseMgr')
            .assert.visible('@courseMgrCourses')
            .assert.visible('@courseMgrTeachers')
            .assert.visible('@courseMgrStudents')
            .assert.visible('@courseMgrFacility')
            .assert.visible('@courseMgrScheduler')
            .assert.visible('@courseMgrConfiguration')
            .assert.visible('@courseMgrReports')
            .assert.containsText('@courseMgrCourses', 'Courses')
            .assert.containsText('@courseMgrTeachers', 'Teachers')
            .assert.containsText('@courseMgrStudents', 'Students')
            .assert.containsText('@courseMgrFacility', 'Facility')
            .assert.containsText('@courseMgrScheduler', 'Scheduler')
            .assert.containsText('@courseMgrConfiguration', 'Configuration')
            .assert.containsText('@courseMgrReports', 'Reports')
            .assert.attributeEquals('@courseMgrCourses', 'href', 'http://web/courses.php')
            .assert.attributeEquals('@courseMgrTeachers', 'href', 'http://web/courseloadteachers.php')
            .assert.attributeEquals('@courseMgrStudents', 'href', 'http://web/courseloadstudents.php?grade=99')
            .assert.attributeEquals('@courseMgrFacility', 'href', 'http://web/courseloadfacility.php')
            .assert.attributeEquals('@courseMgrScheduler', 'href', 'http://web/coursescheduler.php')
            .assert.attributeEquals('@courseMgrConfiguration', 'href', 'http://web/coursecfg.php')
            .assert.attributeEquals('@courseMgrReports', 'href', 'http://web/reports.php?type=25')

            .click('@courseMgr')
            .assert.hidden('@courseMgrCourses')
            .assert.hidden('@courseMgrTeachers')
            .assert.hidden('@courseMgrStudents')
            .assert.hidden('@courseMgrFacility')
            .assert.hidden('@courseMgrScheduler')
            .assert.hidden('@courseMgrConfiguration')
            .assert.hidden('@courseMgrReports')

            .click('@admissionsCommunication')
            .assert.visible('@admissionsCommunicationBatchEmail')
            .assert.containsText('@admissionsCommunicationBatchEmail', 'Batch Email')
            .assert.attributeEquals('@admissionsCommunicationBatchEmail', 'href', 'http://web/batchemail3.php?classid=-2')

            .click('@portalMgr')
            .assert.visible('@portalMgrStudents')
            .assert.visible('@portalMgrFamilies')
            .assert.visible('@portalMgrApplications')
            .assert.visible('@portalMgrEssayQuestions')
            .assert.visible('@portalMgrRequestedDocs')
            .assert.containsText('@portalMgrStudents', 'Students')
            .assert.containsText('@portalMgrFamilies', 'Families')
            .assert.containsText('@portalMgrApplications', 'Applications')
            .assert.containsText('@portalMgrEssayQuestions', 'Essay Questions')
            .assert.containsText('@portalMgrRequestedDocs', 'Requested Docs')
            .assert.attributeEquals('@portalMgrStudents', 'href', 'http://web/enrollstudents2.php')
            .assert.attributeEquals('@portalMgrFamilies', 'href', 'http://web/enrollfamilies2.php')
            .assert.attributeEquals('@portalMgrApplications', 'href', 'http://web/enrollapplications.php')
            .assert.attributeEquals('@portalMgrEssayQuestions', 'href', 'http://web/enrollessays.php')
            .assert.attributeEquals('@portalMgrRequestedDocs', 'href', 'http://web/essentialdocuments.php')

            .click('@portalMgr')
            .assert.hidden('@portalMgrStudents')
            .assert.hidden('@portalMgrFamilies')
            .assert.hidden('@portalMgrApplications')
            .assert.hidden('@portalMgrEssayQuestions')
            .assert.hidden('@portalMgrRequestedDocs')

            .click('@admissionsConfiguration')
            .assert.visible('@admissionsConfigurationChecklist')
            .assert.visible('@admissionsConfigurationDocuments')
            .assert.visible('@admissionsConfigurationAgreements')
            .assert.visible('@admissionsConfigurationTuitionPlans')
            .assert.visible('@admissionsConfigurationEnrollStatus')
            .assert.visible('@admissionsConfigurationSetup')
            .assert.containsText('@admissionsConfigurationChecklist', 'Checklist')
            .assert.containsText('@admissionsConfigurationDocuments', 'Documents')
            .assert.containsText('@admissionsConfigurationAgreements', 'Agreements')
            .assert.containsText('@admissionsConfigurationTuitionPlans', 'Tuition Plans')
            .assert.containsText('@admissionsConfigurationEnrollStatus', 'Enroll Status')
            .assert.containsText('@admissionsConfigurationSetup', 'Setup')
            .assert.attributeEquals('@admissionsConfigurationChecklist', 'href', 'http://web/enrollcheck.php')
            .assert.attributeEquals('@admissionsConfigurationDocuments', 'href', 'http://web/enrolldocs.php')
            .assert.attributeEquals('@admissionsConfigurationAgreements', 'href', 'http://web/enrollagreements.php')
            .assert.attributeEquals('@admissionsConfigurationTuitionPlans', 'href', 'http://web/tuition.php')
            .assert.attributeEquals('@admissionsConfigurationEnrollStatus', 'href', 'http://web/enrollstatus.php')
            .assert.attributeEquals('@admissionsConfigurationSetup', 'href', 'http://web/enrollconfig.php')

            .click('@admissionsConfiguration')
            .assert.hidden('@admissionsConfigurationChecklist')
            .assert.hidden('@admissionsConfigurationDocuments')
            .assert.hidden('@admissionsConfigurationAgreements')
            .assert.hidden('@admissionsConfigurationTuitionPlans')
            .assert.hidden('@admissionsConfigurationEnrollStatus')
            .assert.hidden('@admissionsConfigurationSetup')

            .click('@admissions')

            .assert.hidden('@inquiries')
            .assert.hidden('@inquiresStudents')
            .assert.hidden('@inquiriesFamilies')

            .assert.hidden('@enrollment')
            .assert.hidden('@enrollmentStudent')
            .assert.hidden('@enrollmentFamilies')

            .assert.hidden('@classMgr')
            .assert.hidden('@classMgrClasses')

            .assert.hidden('@courseMgr')
            .assert.hidden('@courseMgrCourses')
            .assert.hidden('@courseMgrTeachers')
            .assert.hidden('@courseMgrStudents')
            .assert.hidden('@courseMgrFacility')
            .assert.hidden('@courseMgrScheduler')
            .assert.hidden('@courseMgrConfiguration')
            .assert.hidden('@courseMgrReports')

            .assert.hidden('@admissionsCommunication')
            .assert.hidden('@admissionsCommunicationBatchEmail')

            .assert.hidden('@portalMgr')
            .assert.hidden('@portalMgrStudents')
            .assert.hidden('@portalMgrFamilies')
            .assert.hidden('@portalMgrApplications')
            .assert.hidden('@portalMgrEssayQuestions')
            .assert.hidden('@portalMgrRequestedDocs')

            .assert.hidden('@admissionsConfiguration')
            .assert.hidden('@admissionsConfigurationChecklist')
            .assert.hidden('@admissionsConfigurationDocuments')
            .assert.hidden('@admissionsConfigurationAgreements')
            .assert.hidden('@admissionsConfigurationTuitionPlans')
            .assert.hidden('@admissionsConfigurationEnrollStatus')
            .assert.hidden('@admissionsConfigurationSetup')

            .assert.hidden('@admissionsReports')

        client.frame(null);

        client.end();
    }
};
