module.exports = {
    tags: ['administrativeTest', 'menuTests'],

    'Administrative Test': (client) => {

        var page = client.page.login();

        page.navigate()
            .schoolLogin('superuser', 'guest', '1');

        client.frame(1);
        client.page.menu()
            .assert.visible('@administrative')
            .assert.containsText('@administrative', '\273 Administrative')
            .assert.attributeEquals('@administrative', 'href', page.url() + '/schoolmenu.php#')

            .assert.hidden('@backOfficeMgr')
            .assert.hidden('@backOfficeMgrStudents')
            .assert.hidden('@backOfficeMgrStudentsAll')
            .assert.hidden('@backOfficeMgrStudentsCurrent')
            .assert.hidden('@backOfficeMgrStudentsTypes')
            .assert.hidden('@backOfficeMgrStudentsAdditionalFields')
            .assert.hidden('@backOfficeMgrStudentsCategories')
            .assert.hidden('@backOfficeMgrStudentsActivites')
            .assert.hidden('@backOfficeMgrStudentsChecklists')

            .assert.hidden('@backOfficeMgrFamilies')
            .assert.hidden('@backOfficeMgrFamiliesAll')
            .assert.hidden('@backOfficeMgrFamiliesCurrent')
            .assert.hidden('@backOfficeMgrFamiliesAdditionalFields')
            .assert.hidden('@backOfficeMgrFamiliesNewFamily')

            .assert.hidden('@backOfficeReports')

            .assert.hidden('@attendance')
            .assert.hidden('@attendanceHomeroom')
            .assert.hidden('@attendanceByPeriods')
            .assert.hidden('@attendanceByStudent')
            .assert.hidden('@attendanceByClassroom')
            .assert.hidden('@attendanceByEmployee')
            .assert.hidden('@attendanceDailyAbsences')
            .assert.hidden('@attendanceCheckInOut')
            .assert.hidden('@attendanceRecordTypes')
            .assert.hidden('@attendanceScale')
            .assert.hidden('@attendanceReports')

            .assert.hidden('@administration')
            .assert.hidden('@administrationSchoolYears')
            .assert.hidden('@administrationSchoolPeriods')
            .assert.hidden('@administrationGradeLevels')
            .assert.hidden('@administrationCalendarOptions')
            .assert.hidden('@administrationReportTemplate')
            .assert.hidden('@administrationReportArchives')

            .assert.hidden('@humanReources')
            .assert.hidden('@humanResourcesEmployees')
            .assert.hidden('@humanResourcesSubstitutes')
            .assert.hidden('@humanResourcesDepartments')
            .assert.hidden('@humanResourcesPositions')
            .assert.hidden('@humanResourcesTypes')
            .assert.hidden('@humanResourcesCategories')
            .assert.hidden('@humanResourcesAdditionalFields')
            .assert.hidden('@humanResourcesReports')

            .click('@administrative')
            .assert.visible('@backOfficeMgr')
            .assert.visible('@attendance')
            .assert.visible('@administration')
            .assert.visible('@humanReources')
            .assert.containsText('@backOfficeMgr', 'Back Office Mgr')
            .assert.containsText('@attendance', 'Attendance')
            .assert.containsText('@administration', 'Administration')
            .assert.containsText('@humanReources', 'Human Resources')

            .click('@backOfficeMgr')
            .assert.visible('@backOfficeMgrStudents')
            .assert.visible('@backOfficeMgrFamilies')
            .assert.visible('@backOfficeReports')
            .assert.containsText('@backOfficeMgrStudents', 'Students')
            .assert.containsText('@backOfficeMgrFamilies', 'Families')
            .assert.containsText('@backOfficeReports', 'Reports')
            .assert.attributeEquals('@backOfficeReports', 'href', page.url() + '/reports.php?type=2')

            .click('@backOfficeMgrStudents')
            .assert.visible('@backOfficeMgrStudentsAll')
            .assert.visible('@backOfficeMgrStudentsCurrent')
            .assert.visible('@backOfficeMgrStudentsTypes')
            .assert.visible('@backOfficeMgrStudentsAdditionalFields')
            .assert.visible('@backOfficeMgrStudentsCategories')
            .assert.visible('@backOfficeMgrStudentsActivites')
            .assert.visible('@backOfficeMgrStudentsChecklists')
            .assert.containsText('@backOfficeMgrStudentsAll', 'All')
            .assert.containsText('@backOfficeMgrStudentsCurrent', 'Current')
            .assert.containsText('@backOfficeMgrStudentsTypes', 'Types')
            .assert.containsText('@backOfficeMgrStudentsAdditionalFields', 'Additional Fields')
            .assert.containsText('@backOfficeMgrStudentsCategories', 'Categories')
            .assert.containsText('@backOfficeMgrStudentsActivites', 'Activities')
            .assert.containsText('@backOfficeMgrStudentsChecklists', 'Checklists')
            .assert.attributeEquals('@backOfficeMgrStudentsAll', 'href', page.url() + '/students.php?task=list&all=1&grade=99')
            .assert.attributeEquals('@backOfficeMgrStudentsCurrent', 'href', page.url() + '/students.php?task=list&cur=1&grade=99')
            .assert.attributeEquals('@backOfficeMgrStudentsTypes', 'href', page.url() + '/studenttypes.php')
            .assert.attributeEquals('@backOfficeMgrStudentsAdditionalFields', 'href', page.url() + '/studentstatistics.php?task=list')
            .assert.attributeEquals('@backOfficeMgrStudentsCategories', 'href', page.url() + '/studentcategories.php')
            .assert.attributeEquals('@backOfficeMgrStudentsActivites', 'href', page.url() + '/studentactivities.php')
            .assert.attributeEquals('@backOfficeMgrStudentsChecklists', 'href', page.url() + '/studentchecklist.php?task=list')

            .click('@backOfficeMgrStudents')
            .assert.hidden('@backOfficeMgrStudentsAll')
            .assert.hidden('@backOfficeMgrStudentsCurrent')
            .assert.hidden('@backOfficeMgrStudentsTypes')
            .assert.hidden('@backOfficeMgrStudentsAdditionalFields')
            .assert.hidden('@backOfficeMgrStudentsCategories')
            .assert.hidden('@backOfficeMgrStudentsActivites')
            .assert.hidden('@backOfficeMgrStudentsChecklists')

            .click('@backOfficeMgrFamilies')
            .assert.visible('@backOfficeMgrFamiliesAll')
            .assert.visible('@backOfficeMgrFamiliesCurrent')
            .assert.visible('@backOfficeMgrFamiliesAdditionalFields')
            .assert.visible('@backOfficeMgrFamiliesNewFamily')
            .assert.containsText('@backOfficeMgrFamiliesAll', 'All')
            .assert.containsText('@backOfficeMgrFamiliesCurrent', 'Current')
            .assert.containsText('@backOfficeMgrFamiliesAdditionalFields', 'Additional Fields')
            .assert.containsText('@backOfficeMgrFamiliesNewFamily', 'New Family')
            .assert.attributeEquals('@backOfficeMgrFamiliesAll', 'href', page.url() + '/families.php?task=list&all=1')
            .assert.attributeEquals('@backOfficeMgrFamiliesCurrent', 'href', page.url() + '/families.php?task=list&cur=1')
            .assert.attributeEquals('@backOfficeMgrFamiliesAdditionalFields', 'href', page.url() + '/familystatistics.php?task=list')
            .assert.attributeEquals('@backOfficeMgrFamiliesNewFamily', 'href', page.url() + '/families.php?task=new')

            .click('@backOfficeMgrFamilies')
            .assert.hidden('@backOfficeMgrFamiliesAll')
            .assert.hidden('@backOfficeMgrFamiliesCurrent')
            .assert.hidden('@backOfficeMgrFamiliesAdditionalFields')
            .assert.hidden('@backOfficeMgrFamiliesNewFamily')

            .click('@backOfficeMgr')
            .assert.hidden('@backOfficeMgrStudents')
            .assert.hidden('@backOfficeMgrFamilies')
            .assert.hidden('@backOfficeReports')

            .click('@attendance')
            .assert.visible('@attendanceHomeroom')
            .assert.visible('@attendanceByPeriods')
            .assert.visible('@attendanceByStudent')
            .assert.visible('@attendanceByClassroom')
            .assert.visible('@attendanceByEmployee')
            .assert.visible('@attendanceDailyAbsences')
            .assert.visible('@attendanceCheckInOut')
            .assert.visible('@attendanceRecordTypes')
            .assert.visible('@attendanceScale')
            .assert.visible('@attendanceReports')
            .assert.containsText('@attendanceHomeroom', 'Homeroom')
            .assert.containsText('@attendanceByPeriods', 'by Periods')
            .assert.containsText('@attendanceByStudent', 'by Student')
            .assert.containsText('@attendanceByClassroom', 'by Classroom')
            .assert.containsText('@attendanceByEmployee', 'by Employee')
            .assert.containsText('@attendanceDailyAbsences', 'Daily Absences')
            .assert.containsText('@attendanceCheckInOut', 'Check In-Out')
            .assert.containsText('@attendanceRecordTypes', 'Record Types')
            .assert.containsText('@attendanceScale', 'Attendance Scale')
            .assert.containsText('@attendanceReports', 'Reports')
            .assert.attributeEquals('@attendanceHomeroom', 'href', page.url() + '/homeroom.php')
            .assert.attributeEquals('@attendanceByPeriods', 'href', page.url() + '/attendperiods.php')
            .assert.attributeEquals('@attendanceByStudent', 'href', page.url() + '/attendstudents.php')
            .assert.attributeEquals('@attendanceByClassroom', 'href', page.url() + '/attendclasses.php')
            .assert.attributeEquals('@attendanceByEmployee', 'href', page.url() + '/attendusers.php')
            .assert.attributeEquals('@attendanceDailyAbsences', 'href', page.url() + '/attendabsents.php')
            .assert.attributeEquals('@attendanceCheckInOut', 'href', page.url() + '/attendcheck.php')
            .assert.attributeEquals('@attendanceRecordTypes', 'href', page.url() + '/attendancetypes.php')
            .assert.attributeEquals('@attendanceScale', 'href', page.url() + '/attendancescale.php')
            .assert.attributeEquals('@attendanceReports', 'href', page.url() + '/reports.php?type=12')

            .click('@attendance')
            .assert.hidden('@attendanceHomeroom')
            .assert.hidden('@attendanceByPeriods')
            .assert.hidden('@attendanceByStudent')
            .assert.hidden('@attendanceByClassroom')
            .assert.hidden('@attendanceByEmployee')
            .assert.hidden('@attendanceDailyAbsences')
            .assert.hidden('@attendanceCheckInOut')
            .assert.hidden('@attendanceRecordTypes')
            .assert.hidden('@attendanceScale')
            .assert.hidden('@attendanceReports')

            .click('@administration')
            .assert.visible('@administrationSchoolYears')
            .assert.visible('@administrationSchoolPeriods')
            .assert.visible('@administrationGradeLevels')
            .assert.visible('@administrationCalendarOptions')
            .assert.visible('@administrationReportTemplate')
            .assert.visible('@administrationReportArchives')
            .assert.containsText('@administrationSchoolYears', 'School Years')
            .assert.containsText('@administrationSchoolPeriods', 'School Periods')
            .assert.containsText('@administrationGradeLevels', 'Grade Levels')
            .assert.containsText('@administrationCalendarOptions', 'Calendar Options')
            .assert.containsText('@administrationReportTemplate', 'Report Template +')
            .assert.containsText('@administrationReportArchives', 'Report Archives')
            .assert.attributeEquals('@administrationSchoolYears', 'href', page.url() + '/schoolyear.php')
            .assert.attributeEquals('@administrationSchoolPeriods', 'href', page.url() + '/schoolperiods.php')
            .assert.attributeEquals('@administrationGradeLevels', 'href', page.url() + '/schoolgrades.php')
            .assert.attributeEquals('@administrationCalendarOptions', 'href', page.url() + '/calendaroptions.php')
            .assert.attributeEquals('@administrationReportTemplate', 'href', page.url() + '/report_mgr.php')
            .assert.attributeEquals('@administrationReportArchives', 'href', page.url() + '/reportarchives.php?noheader=1')

            .click('@administration')
            .assert.hidden('@administrationSchoolYears')
            .assert.hidden('@administrationSchoolPeriods')
            .assert.hidden('@administrationGradeLevels')
            .assert.hidden('@administrationCalendarOptions')
            .assert.hidden('@administrationReportTemplate')
            .assert.hidden('@administrationReportArchives')

            .click('@humanReources')
            .assert.visible('@humanResourcesEmployees')
            .assert.visible('@humanResourcesSubstitutes')
            .assert.visible('@humanResourcesDepartments')
            .assert.visible('@humanResourcesPositions')
            .assert.visible('@humanResourcesTypes')
            .assert.visible('@humanResourcesCategories')
            .assert.visible('@humanResourcesAdditionalFields')
            .assert.visible('@humanResourcesReports')
            .assert.containsText('@humanResourcesEmployees', 'Employees')
            .assert.containsText('@humanResourcesSubstitutes', 'Substitutes')
            .assert.containsText('@humanResourcesDepartments', 'Departments')
            .assert.containsText('@humanResourcesPositions', 'Positions')
            .assert.containsText('@humanResourcesTypes', 'Types')
            .assert.containsText('@humanResourcesCategories', 'Categories')
            .assert.containsText('@humanResourcesAdditionalFields', 'Additional Fields')
            .assert.containsText('@humanResourcesReports', 'Reports')
            .assert.attributeEquals('@humanResourcesEmployees', 'href', page.url() + '/users.php?task=list')
            .assert.attributeEquals('@humanResourcesSubstitutes', 'href', page.url() + '/substitutes.php')
            .assert.attributeEquals('@humanResourcesDepartments', 'href', page.url() + '/departments.php')
            .assert.attributeEquals('@humanResourcesPositions', 'href', page.url() + '/userpositions.php?task=list')
            .assert.attributeEquals('@humanResourcesTypes', 'href', page.url() + '/usertypes.php')
            .assert.attributeEquals('@humanResourcesCategories', 'href', page.url() + '/usercategories.php?task=list')
            .assert.attributeEquals('@humanResourcesAdditionalFields', 'href', page.url() + '/userstatistics.php?task=list')
            .assert.attributeEquals('@humanResourcesReports', 'href', page.url() + '/reports.php?type=5')

            .click('@humanReources')
            .assert.hidden('@humanResourcesEmployees')
            .assert.hidden('@humanResourcesSubstitutes')
            .assert.hidden('@humanResourcesDepartments')
            .assert.hidden('@humanResourcesPositions')
            .assert.hidden('@humanResourcesTypes')
            .assert.hidden('@humanResourcesCategories')
            .assert.hidden('@humanResourcesAdditionalFields')
            .assert.hidden('@humanResourcesReports')

            .click('@administrative')
            .assert.hidden('@backOfficeMgr')
            .assert.hidden('@attendance')
            .assert.hidden('@administration')
            .assert.hidden('@humanReources')

        client.frame(null);

        client.end();
    }
};
