module.exports = {
    tags: ['administrativeTest', 'menuTests'],

    'Administrative Test': (client) => {

        var page = client.page.login();

        var schoolID = '1';
        var username = 'superuser';
        var password = 'guest';

        page.navigate()
            .schoolLogin(username, password, schoolID);

        client.frame(1);
        client.page.menu()
            .assert.visible('@administrative')
            .assert.containsText('@administrative', '\273 Administrative')
            .assert.attributeEquals('@administrative', 'href', 'http://web/schoolmenu.php#')

            .assert.hidden('@backOffice')
            .assert.hidden('@students')
            .assert.hidden('@studentsAll')
            .assert.hidden('@studentsCurrent')
            .assert.hidden('@studentsTypes')
            .assert.hidden('@studentsAdditionalFields')
            .assert.hidden('@studentsCategories')
            .assert.hidden('@studentsActivites')
            .assert.hidden('@studentsChecklists')

            .assert.hidden('@families')
            .assert.hidden('@familiesAll')
            .assert.hidden('@familiesCurrent')
            .assert.hidden('@familiesAdditionalFields')
            .assert.hidden('@familiesNewFamily')

            .assert.hidden('@backOfficeReports')

            .assert.hidden('@attendance')
            .assert.hidden('@attendanceHomeroom')
            .assert.hidden('@attendanceByPeriods')
            .assert.hidden('@attendanceByStudent')
            .assert.hidden('@attendanceByClassroom')
            .assert.hidden('@attendanceByEmployee')
            .assert.hidden('@attendanceDailyAbsences')
            .assert.hidden('@attendanceCheckInOut')
            .assert.hidden('@attendanceRecordTypes')
            .assert.hidden('@attendanceScale')
            .assert.hidden('@attendanceReports')

            .assert.hidden('@administration')
            .assert.hidden('@administrationSchoolYears')
            .assert.hidden('@administrationSchoolPeriods')
            .assert.hidden('@administrationGradeLevels')
            .assert.hidden('@administrationCalendarOptions')
            .assert.hidden('@administrationReportTemplate')
            .assert.hidden('@administrationReportArchives')

            .assert.hidden('@humanReources')
            .assert.hidden('@humanResourcesEmployees')
            .assert.hidden('@humanResourcesSubstitutes')
            .assert.hidden('@humanResourcesDepartments')
            .assert.hidden('@humanResourcesPositions')
            .assert.hidden('@humanResourcesTypes')
            .assert.hidden('@humanResourcesCategories')
            .assert.hidden('@humanResourcesAdditionalFields')
            .assert.hidden('@humanResourcesReports')

            .click('@administrative')
            .assert.visible('@backOffice')
            .assert.visible('@attendance')
            .assert.visible('@administration')
            .assert.visible('@humanReources')
            .assert.containsText('@backOffice', 'Back Office Mgr')
            .assert.containsText('@attendance', 'Attendance')
            .assert.containsText('@administration', 'Administration')
            .assert.containsText('@humanReources', 'Human Resources')

            .click('@backOffice')
            .assert.visible('@students')
            .assert.visible('@families')
            .assert.visible('@backOfficeReports')
            .assert.containsText('@students', 'Students')
            .assert.containsText('@families', 'Families')
            .assert.containsText('@backOfficeReports', 'Reports')
            .assert.attributeEquals('@backOfficeReports', 'href', 'http://web/reports.php?type=2')

            .click('@students')
            .assert.visible('@studentsAll')
            .assert.visible('@studentsCurrent')
            .assert.visible('@studentsTypes')
            .assert.visible('@studentsAdditionalFields')
            .assert.visible('@studentsCategories')
            .assert.visible('@studentsActivites')
            .assert.visible('@studentsChecklists')
            .assert.containsText('@studentsAll', 'All')
            .assert.containsText('@studentsCurrent', 'Current')
            .assert.containsText('@studentsTypes', 'Types')
            .assert.containsText('@studentsAdditionalFields', 'Additional Fields')
            .assert.containsText('@studentsCategories', 'Categories')
            .assert.containsText('@studentsActivites', 'Activities')
            .assert.containsText('@studentsChecklists', 'Checklists')
            .assert.attributeEquals('@studentsAll', 'href', 'http://web/students.php?task=list&all=1&grade=99')
            .assert.attributeEquals('@studentsCurrent', 'href', 'http://web/students.php?task=list&cur=1&grade=99')
            .assert.attributeEquals('@studentsTypes', 'href', 'http://web/studenttypes.php')
            .assert.attributeEquals('@studentsAdditionalFields', 'href', 'http://web/studentstatistics.php?task=list')
            .assert.attributeEquals('@studentsCategories', 'href', 'http://web/studentcategories.php')
            .assert.attributeEquals('@studentsActivites', 'href', 'http://web/studentactivities.php')
            .assert.attributeEquals('@studentsChecklists', 'href', 'http://web/studentchecklist.php?task=list')

            .click('@students')
            .assert.hidden('@studentsAll')
            .assert.hidden('@studentsCurrent')
            .assert.hidden('@studentsTypes')
            .assert.hidden('@studentsAdditionalFields')
            .assert.hidden('@studentsCategories')
            .assert.hidden('@studentsActivites')
            .assert.hidden('@studentsChecklists')

            .click('@families')
            .assert.visible('@familiesAll')
            .assert.visible('@familiesCurrent')
            .assert.visible('@familiesAdditionalFields')
            .assert.visible('@familiesNewFamily')
            .assert.containsText('@familiesAll', 'All')
            .assert.containsText('@familiesCurrent', 'Current')
            .assert.containsText('@familiesAdditionalFields', 'Additional Fields')
            .assert.containsText('@familiesNewFamily', 'New Family')
            .assert.attributeEquals('@familiesAll', 'href', 'http://web/families.php?task=list&all=1')
            .assert.attributeEquals('@familiesCurrent', 'href', 'http://web/families.php?task=list&cur=1')
            .assert.attributeEquals('@familiesAdditionalFields', 'href', 'http://web/familystatistics.php?task=list')
            .assert.attributeEquals('@familiesNewFamily', 'href', 'http://web/families.php?task=new')

            .click('@families')
            .assert.hidden('@familiesAll')
            .assert.hidden('@familiesCurrent')
            .assert.hidden('@familiesAdditionalFields')
            .assert.hidden('@familiesNewFamily')

            .click('@backOffice')
            .assert.hidden('@students')
            .assert.hidden('@families')
            .assert.hidden('@backOfficeReports')

            .click('@attendance')
            .assert.visible('@attendanceHomeroom')
            .assert.visible('@attendanceByPeriods')
            .assert.visible('@attendanceByStudent')
            .assert.visible('@attendanceByClassroom')
            .assert.visible('@attendanceByEmployee')
            .assert.visible('@attendanceDailyAbsences')
            .assert.visible('@attendanceCheckInOut')
            .assert.visible('@attendanceRecordTypes')
            .assert.visible('@attendanceScale')
            .assert.visible('@attendanceReports')
            .assert.containsText('@attendanceHomeroom', 'Homeroom')
            .assert.containsText('@attendanceByPeriods', 'by Periods')
            .assert.containsText('@attendanceByStudent', 'by Student')
            .assert.containsText('@attendanceByClassroom', 'by Classroom')
            .assert.containsText('@attendanceByEmployee', 'by Employee')
            .assert.containsText('@attendanceDailyAbsences', 'Daily Absences')
            .assert.containsText('@attendanceCheckInOut', 'Check In-Out')
            .assert.containsText('@attendanceRecordTypes', 'Record Types')
            .assert.containsText('@attendanceScale', 'Attendance Scale')
            .assert.containsText('@attendanceReports', 'Reports')
            .assert.attributeEquals('@attendanceHomeroom', 'href', 'http://web/homeroom.php')
            .assert.attributeEquals('@attendanceByPeriods', 'href', 'http://web/attendperiods.php')
            .assert.attributeEquals('@attendanceByStudent', 'href', 'http://web/attendstudents.php')
            .assert.attributeEquals('@attendanceByClassroom', 'href', 'http://web/attendclasses.php')
            .assert.attributeEquals('@attendanceByEmployee', 'href', 'http://web/attendusers.php')
            .assert.attributeEquals('@attendanceDailyAbsences', 'href', 'http://web/attendabsents.php')
            .assert.attributeEquals('@attendanceCheckInOut', 'href', 'http://web/attendcheck.php')
            .assert.attributeEquals('@attendanceRecordTypes', 'href', 'http://web/attendancetypes.php')
            .assert.attributeEquals('@attendanceScale', 'href', 'http://web/attendancescale.php')
            .assert.attributeEquals('@attendanceReports', 'href', 'http://web/reports.php?type=12')

            .click('@attendance')
            .assert.hidden('@attendanceHomeroom')
            .assert.hidden('@attendanceByPeriods')
            .assert.hidden('@attendanceByStudent')
            .assert.hidden('@attendanceByClassroom')
            .assert.hidden('@attendanceByEmployee')
            .assert.hidden('@attendanceDailyAbsences')
            .assert.hidden('@attendanceCheckInOut')
            .assert.hidden('@attendanceRecordTypes')
            .assert.hidden('@attendanceScale')
            .assert.hidden('@attendanceReports')

            .click('@administration')
            .assert.visible('@administrationSchoolYears')
            .assert.visible('@administrationSchoolPeriods')
            .assert.visible('@administrationGradeLevels')
            .assert.visible('@administrationCalendarOptions')
            .assert.visible('@administrationReportTemplate')
            .assert.visible('@administrationReportArchives')
            .assert.containsText('@administrationSchoolYears', 'School Years')
            .assert.containsText('@administrationSchoolPeriods', 'School Periods')
            .assert.containsText('@administrationGradeLevels', 'Grade Levels')
            .assert.containsText('@administrationCalendarOptions', 'Calendar Options')
            .assert.containsText('@administrationReportTemplate', 'Report Template +')
            .assert.containsText('@administrationReportArchives', 'Report Archives')
            .assert.attributeEquals('@administrationSchoolYears', 'href', 'http://web/schoolyear.php')
            .assert.attributeEquals('@administrationSchoolPeriods', 'href', 'http://web/schoolperiods.php')
            .assert.attributeEquals('@administrationGradeLevels', 'href', 'http://web/schoolgrades.php')
            .assert.attributeEquals('@administrationCalendarOptions', 'href', 'http://web/calendaroptions.php')
            .assert.attributeEquals('@administrationReportTemplate', 'href', 'http://web/report_mgr.php')
            .assert.attributeEquals('@administrationReportArchives', 'href', 'http://web/reportarchives.php?noheader=1')

            .click('@administration')
            .assert.hidden('@administrationSchoolYears')
            .assert.hidden('@administrationSchoolPeriods')
            .assert.hidden('@administrationGradeLevels')
            .assert.hidden('@administrationCalendarOptions')
            .assert.hidden('@administrationReportTemplate')
            .assert.hidden('@administrationReportArchives')

            .click('@humanReources')
            .assert.visible('@humanResourcesEmployees')
            .assert.visible('@humanResourcesSubstitutes')
            .assert.visible('@humanResourcesDepartments')
            .assert.visible('@humanResourcesPositions')
            .assert.visible('@humanResourcesTypes')
            .assert.visible('@humanResourcesCategories')
            .assert.visible('@humanResourcesAdditionalFields')
            .assert.visible('@humanResourcesReports')
            .assert.containsText('@humanResourcesEmployees', 'Employees')
            .assert.containsText('@humanResourcesSubstitutes', 'Substitutes')
            .assert.containsText('@humanResourcesDepartments', 'Departments')
            .assert.containsText('@humanResourcesPositions', 'Positions')
            .assert.containsText('@humanResourcesTypes', 'Types')
            .assert.containsText('@humanResourcesCategories', 'Categories')
            .assert.containsText('@humanResourcesAdditionalFields', 'Additional Fields')
            .assert.containsText('@humanResourcesReports', 'Reports')
            .assert.attributeEquals('@humanResourcesEmployees', 'href', 'http://web/users.php?task=list')
            .assert.attributeEquals('@humanResourcesSubstitutes', 'href', 'http://web/substitutes.php')
            .assert.attributeEquals('@humanResourcesDepartments', 'href', 'http://web/departments.php')
            .assert.attributeEquals('@humanResourcesPositions', 'href', 'http://web/userpositions.php?task=list')
            .assert.attributeEquals('@humanResourcesTypes', 'href', 'http://web/usertypes.php')
            .assert.attributeEquals('@humanResourcesCategories', 'href', 'http://web/usercategories.php?task=list')
            .assert.attributeEquals('@humanResourcesAdditionalFields', 'href', 'http://web/userstatistics.php?task=list')
            .assert.attributeEquals('@humanResourcesReports', 'href', 'http://web/reports.php?type=5')

            .click('@humanReources')
            .assert.hidden('@humanResourcesEmployees')
            .assert.hidden('@humanResourcesSubstitutes')
            .assert.hidden('@humanResourcesDepartments')
            .assert.hidden('@humanResourcesPositions')
            .assert.hidden('@humanResourcesTypes')
            .assert.hidden('@humanResourcesCategories')
            .assert.hidden('@humanResourcesAdditionalFields')
            .assert.hidden('@humanResourcesReports')

            .click('@administrative')
            .assert.hidden('@backOffice')
            .assert.hidden('@attendance')
            .assert.hidden('@administration')
            .assert.hidden('@humanReources')

        client.frame(null);

        client.end();
    }
};
