module.exports = {
    tags: ['financialTest', 'menuTests'],

    'Financial Menu Test': (client) => {

        var page = client.page.login();

        page.navigate()
            .schoolLogin();

        client.frame(1);
        client.page.menu()
            .assert.visible('@financial')
            .assert.containsText('@financial', '\273 Financial')
            .assert.attributeEquals('@financial', 'href', 'http://web/schoolmenu.php#')

            .assert.hidden('@accountingMgr')

            .assert.hidden('@accountingMgrSchool')
            .assert.hidden('@accountingMgrSchoolChartOfAccounts')
            .assert.hidden('@accountingMgrSchoolActivityLogs')

            .assert.hidden('@accountingMgrFamilies')
            .assert.hidden('@accountingMgrFamiliesAccounts')
            .assert.hidden('@accountingMgrFamiliesBillingSetup')
            .assert.hidden('@accountingMgrFamiliesMonthlyCharges')
            .assert.hidden('@accountingMgrFamiliesReceivePayment')
            .assert.hidden('@accountingMgrFamiliesNotification')
            .assert.hidden('@accountingMgrFamiliesInvoices')

            .assert.hidden('@accountingMgrBanking')
            .assert.hidden('@accountingMgrBankingDeposits')
            .assert.hidden('@accountingMgrBankingRegisters')
            .assert.hidden('@accountingMgrBankingJournal')

            .assert.hidden('@accountingMgrEmployees')
            .assert.hidden('@accountingMgrEmployeesPayroll')
            .assert.hidden('@accountingMgrEmployeesPayrollByEmployee')
            .assert.hidden('@accountingMgrEmployeesPayrollByMonth')
            .assert.hidden('@accountingMgrEmployeesExpenses')
            .assert.hidden('@accountingMgrEmployeesExpensesSubmitted')
            .assert.hidden('@accountingMgrEmployeesExpensesApproved')
            .assert.hidden('@accountingMgrEmployeesExpensesPaid')

            .assert.hidden('@accountingMgrServices')
            .assert.hidden('@accountingMgrServicesDwolla')
            .assert.hidden('@accountingMgrServicesDwollaTransactions')
            .assert.hidden('@accountingMgrServicesDwollaConfiguration')
            .assert.hidden('@accountingMgrServicesPayJunction')
            .assert.hidden('@accountingMgrServicesPayJunctionInvoices')
            .assert.hidden('@accountingMgrServicesPayJunctionPayments')
            .assert.hidden('@accountingMgrServicesPayJunctionConvenienceFees')
            .assert.hidden('@accountingMgrServicesPayJunctionConfiguration')
            .assert.hidden('@accountingMgrServicesSmartTuition')
            .assert.hidden('@accountingMgrServicesSmartTuitionConfiguration')
            .assert.hidden('@accountingMgrServicesPayPal')
            .assert.hidden('@accountingMgrServicesPayPalOnlinePayments')
            .assert.hidden('@accountingMgrServicesPayPalInvoices')
            .assert.hidden('@accountingMgrServicesPayPalConfiguration')
            .assert.hidden('@accountingMgrServicesEFunds')
            .assert.hidden('@accountingMgrServicesEFundsPayments')
            .assert.hidden('@accountingMgrServicesEFundsTransactions')
            .assert.hidden('@accountingMgrServicesEFundsRemittance')
            .assert.hidden('@accountingMgrServicesEFundsConfiguration')

            .assert.hidden('@accountingMgrConfiguration')
            .assert.hidden('@accountingMgrReports')

            .assert.hidden('@cafeteriaMgr')
            .assert.hidden('@cafeteriaMgrFood')
            .assert.hidden('@cafeteriaMgrMenu')
            .assert.hidden('@cafeteriaMgrCycles')
            .assert.hidden('@cafeteriaMgrOrders')
            .assert.hidden('@cafeteriaMgrPricePlans')
            .assert.hidden('@cafeteriaMgrNotifications')
            .assert.hidden('@cafeteriaMgrAccounts')
            .assert.hidden('@cafeteriaMgrAccountsFamily')
            .assert.hidden('@cafeteriaMgrAccountsEmployee')
            .assert.hidden('@cafeteriaMgrReports')

            .assert.hidden('@childcareMgr')
            .assert.hidden('@childcareMgrAccounts')
            .assert.hidden('@childcareMgrDaily')
            .assert.hidden('@childcareMgrDailyCheckInOut')
            .assert.hidden('@childcareMgrDailyDailyCharges')
            .assert.hidden('@childcareMgrDailyPricePlans')
            .assert.hidden('@childcareMgrWeekly')
            .assert.hidden('@childcareMgrWeeklyCharges')
            .assert.hidden('@childcareMgrWeeklyBillingSetup')
            .assert.hidden('@childcareMgrWeeklyPricePlans')
            .assert.hidden('@childcareMgrMonthly')
            .assert.hidden('@childcareMgrMonthlyCharges')
            .assert.hidden('@childcareMgrMonthlyBillingSetup')
            .assert.hidden('@childcareMgrMonthlyPricePlans')
            .assert.hidden('@childcareMgrNotifications')
            .assert.hidden('@childcareMgrReports')

            .assert.hidden('@donationMgr')
            .assert.hidden('@donationMgrDonors')
            .assert.hidden('@donationMgrDonorsNewDonors')
            .assert.hidden('@donationMgrDonorsByContact')
            .assert.hidden('@donationMgrDonorsPledges')
            .assert.hidden('@donationMgrDonations')
            .assert.hidden('@donationMgrDonationsReceive')
            .assert.hidden('@donationMgrDonationsProcess')
            .assert.hidden('@donationMgrCampaings')
            .assert.hidden('@donationMgrReports')

            .click('@financial')
            .assert.visible('@accountingMgr')
            .assert.visible('@cafeteriaMgr')
            .assert.visible('@childcareMgr')
            .assert.visible('@donationMgr')
            .assert.containsText('@accountingMgr', '\273 Accounting Mgr')
            .assert.containsText('@cafeteriaMgr', '\273 Cafeteria Mgr')
            .assert.containsText('@childcareMgr', '\273 Childcare Mgr')
            .assert.containsText('@donationMgr', '\273 Donation Mgr')
            .assert.attributeEquals('@accountingMgr', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@cafeteriaMgr', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@childcareMgr', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@donationMgr', 'href', 'http://web/schoolmenu.php#')

            .click('@accountingMgr')
            .assert.visible('@accountingMgrSchool')
            .assert.visible('@accountingMgrFamilies')
            .assert.visible('@accountingMgrBanking')
            .assert.visible('@accountingMgrEmployees')
            .assert.visible('@accountingMgrServices')
            .assert.visible('@accountingMgrConfiguration')
            .assert.visible('@accountingMgrReports')
            .assert.containsText('@accountingMgrSchool', '\273 School')
            .assert.containsText('@accountingMgrFamilies', '\273 Families')
            .assert.containsText('@accountingMgrBanking', '\273 Banking')
            .assert.containsText('@accountingMgrEmployees', '\273 Employees')
            .assert.containsText('@accountingMgrServices', '\273 Services')
            .assert.containsText('@accountingMgrConfiguration', 'Configuration')
            .assert.containsText('@accountingMgrReports', 'Reports')
            .assert.attributeEquals('@accountingMgrSchool', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrFamilies', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrBanking', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrEmployees', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrServices', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrConfiguration', 'href', 'http://web/superstatementcfg.php')
            .assert.attributeEquals('@accountingMgrReports', 'href', 'http://web/reports.php?type=3')

            .click('@accountingMgrSchool')
            .assert.visible('@accountingMgrSchoolChartOfAccounts')
            .assert.visible('@accountingMgrSchoolActivityLogs')
            .assert.containsText('@accountingMgrSchoolChartOfAccounts', 'Chart of Accounts')
            .assert.containsText('@accountingMgrSchoolActivityLogs', 'Activity Logs')
            .assert.attributeEquals('@accountingMgrSchoolChartOfAccounts', 'href', 'http://web/schoolaccounts.php')
            .assert.attributeEquals('@accountingMgrSchoolActivityLogs', 'href', 'http://web/acctactivity.php')

            .click('@accountingMgrSchool')
            .assert.hidden('@accountingMgrSchoolChartOfAccounts')
            .assert.hidden('@accountingMgrSchoolActivityLogs')

            .click('@accountingMgrFamilies')
            .assert.visible('@accountingMgrFamiliesCurrent')
            .assert.visible('@accountingMgrFamiliesAccounts')
            .assert.visible('@accountingMgrFamiliesBillingSetup')
            .assert.visible('@accountingMgrFamiliesMonthlyCharges')
            .assert.visible('@accountingMgrFamiliesReceivePayment')
            .assert.visible('@accountingMgrFamiliesNotification')
            .assert.visible('@accountingMgrFamiliesInvoices')
            .assert.containsText('@accountingMgrFamiliesCurrent', 'Current')
            .assert.containsText('@accountingMgrFamiliesAccounts', 'Accounts')
            .assert.containsText('@accountingMgrFamiliesBillingSetup', 'Billing Setup')
            .assert.containsText('@accountingMgrFamiliesMonthlyCharges', 'Monthly Charges')
            .assert.containsText('@accountingMgrFamiliesReceivePayment', 'Receive Payment')
            .assert.containsText('@accountingMgrFamiliesNotification', 'Notification')
            .assert.containsText('@accountingMgrFamiliesInvoices', 'Invoices')
            .assert.attributeEquals('@accountingMgrFamiliesCurrent', 'href', 'http://web/familyaccounting.php')
            .assert.attributeEquals('@accountingMgrFamiliesAccounts', 'href', 'http://web/familyaccountmgr.php')
            .assert.attributeEquals('@accountingMgrFamiliesBillingSetup', 'href', 'http://web/familymonthlybilling.php')
            .assert.attributeEquals('@accountingMgrFamiliesMonthlyCharges', 'href', 'http://web/familymonthlycharges.php')
            .assert.attributeEquals('@accountingMgrFamiliesReceivePayment', 'href', 'http://web/familypayment.php?task=payment')
            .assert.attributeEquals('@accountingMgrFamiliesNotification', 'href', 'http://web/accountnotification.php')
            .assert.attributeEquals('@accountingMgrFamiliesInvoices', 'href', 'http://web/acctinv.php')

            .click('@accountingMgrFamilies')
            .assert.hidden('@accountingMgrFamiliesCurrent')
            .assert.hidden('@accountingMgrFamiliesAccounts')
            .assert.hidden('@accountingMgrFamiliesBillingSetup')
            .assert.hidden('@accountingMgrFamiliesMonthlyCharges')
            .assert.hidden('@accountingMgrFamiliesReceivePayment')
            .assert.hidden('@accountingMgrFamiliesNotification')
            .assert.hidden('@accountingMgrFamiliesInvoices')

            .click('@accountingMgrBanking')
            .assert.visible('@accountingMgrBankingDeposits')
            .assert.visible('@accountingMgrBankingRegisters')
            .assert.visible('@accountingMgrBankingJournal')
            .assert.containsText('@accountingMgrBankingDeposits', 'Deposits')
            .assert.containsText('@accountingMgrBankingRegisters', 'Registers')
            .assert.containsText('@accountingMgrBankingJournal', 'Journal')
            .assert.attributeEquals('@accountingMgrBankingDeposits', 'href', 'http://web/schooldeposits.php')
            .assert.attributeEquals('@accountingMgrBankingRegisters', 'href', 'http://web/schoolregister.php')
            .assert.attributeEquals('@accountingMgrBankingJournal', 'href', 'http://web/acctjournals.php')

            .click('@accountingMgrBanking')
            .assert.hidden('@accountingMgrBankingDeposits')
            .assert.hidden('@accountingMgrBankingRegisters')
            .assert.hidden('@accountingMgrBankingJournal')

            .click('@accountingMgrEmployees')
            .assert.visible('@accountingMgrEmployeesPayroll')
            .assert.visible('@accountingMgrEmployeesExpenses')
            .assert.containsText('@accountingMgrEmployeesPayroll', '\273 Payroll')
            .assert.containsText('@accountingMgrEmployeesExpenses', '\273 Expenses')
            .assert.attributeEquals('@accountingMgrEmployeesPayroll', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrEmployeesExpenses', 'href', 'http://web/schoolmenu.php#')

            .click('@accountingMgrEmployeesPayroll')
            .assert.visible('@accountingMgrEmployeesPayrollByEmployee')
            .assert.visible('@accountingMgrEmployeesPayrollByMonth')
            .assert.containsText('@accountingMgrEmployeesPayrollByEmployee', 'by Employee')
            .assert.containsText('@accountingMgrEmployeesPayrollByMonth', 'by Month')
            .assert.attributeEquals('@accountingMgrEmployeesPayrollByEmployee', 'href', 'http://web/payrollemployee.php')
            .assert.attributeEquals('@accountingMgrEmployeesPayrollByMonth', 'href', 'http://web/payrollmonthly.php')

            .click('@accountingMgrEmployeesPayroll')
            .assert.hidden('@accountingMgrEmployeesPayrollByEmployee')
            .assert.hidden('@accountingMgrEmployeesPayrollByMonth')

            .click('@accountingMgrEmployeesExpenses')
            .assert.visible('@accountingMgrEmployeesExpensesSubmitted')
            .assert.visible('@accountingMgrEmployeesExpensesApproved')
            .assert.visible('@accountingMgrEmployeesExpensesPaid')
            .assert.containsText('@accountingMgrEmployeesExpensesSubmitted', 'Submitted')
            .assert.containsText('@accountingMgrEmployeesExpensesApproved', 'Approved')
            .assert.containsText('@accountingMgrEmployeesExpensesPaid', 'Paid')
            .assert.attributeEquals('@accountingMgrEmployeesExpensesSubmitted', 'href', 'http://web/expenseaccounts.php?type=1')
            .assert.attributeEquals('@accountingMgrEmployeesExpensesApproved', 'href', 'http://web/expenseaccounts.php?type=2')
            .assert.attributeEquals('@accountingMgrEmployeesExpensesPaid', 'href', 'http://web/expenseaccounts.php?type=3')

            .click('@accountingMgrEmployeesExpenses')
            .assert.hidden('@accountingMgrEmployeesExpensesSubmitted')
            .assert.hidden('@accountingMgrEmployeesExpensesApproved')
            .assert.hidden('@accountingMgrEmployeesExpensesPaid')

            .click('@accountingMgrEmployees')
            .assert.hidden('@accountingMgrEmployeesPayroll')
            .assert.hidden('@accountingMgrEmployeesExpenses')

            .click('@accountingMgrServices')
            .assert.visible('@accountingMgrServicesDwolla')
            .assert.visible('@accountingMgrServicesPayJunction')
            .assert.visible('@accountingMgrServicesSmartTuition')
            .assert.visible('@accountingMgrServicesPayPal')
            .assert.visible('@accountingMgrServicesEFunds')
            .assert.containsText('@accountingMgrServicesDwolla', '\273 Dwolla')
            .assert.containsText('@accountingMgrServicesPayJunction', '\273 PayJunction')
            .assert.containsText('@accountingMgrServicesSmartTuition', '\273 Smart Tuition')
            .assert.containsText('@accountingMgrServicesPayPal', '\273 PayPal')
            .assert.containsText('@accountingMgrServicesEFunds', '\273 E-Funds')
            .assert.attributeEquals('@accountingMgrServicesDwolla', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrServicesPayJunction', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrServicesSmartTuition', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrServicesPayPal', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@accountingMgrServicesEFunds', 'href', 'http://web/schoolmenu.php#')

            .click('@accountingMgrServicesDwolla')
            .assert.visible('@accountingMgrServicesDwollaTransactions')
            .assert.visible('@accountingMgrServicesDwollaConfiguration')
            .assert.containsText('@accountingMgrServicesDwollaTransactions', 'Transactions')
            .assert.containsText('@accountingMgrServicesDwollaConfiguration', 'Configuration')
            .assert.visible('@accountingMgrServicesDwollaTransactions', 'href', 'http://web/dwolla.php')
            .assert.visible('@accountingMgrServicesDwollaConfiguration', 'href', 'http://web/dwollacfg.php')

            .click('@accountingMgrServicesDwolla')
            .assert.hidden('@accountingMgrServicesDwollaTransactions')
            .assert.hidden('@accountingMgrServicesDwollaConfiguration')

            .click('@accountingMgrServicesPayJunction')
            .assert.visible('@accountingMgrServicesPayJunctionInvoices')
            .assert.visible('@accountingMgrServicesPayJunctionPayments')
            .assert.visible('@accountingMgrServicesPayJunctionConvenienceFees')
            .assert.visible('@accountingMgrServicesPayJunctionConfiguration')
            .assert.containsText('@accountingMgrServicesPayJunctionInvoices', 'Invoices')
            .assert.containsText('@accountingMgrServicesPayJunctionPayments', 'Payments')
            .assert.containsText('@accountingMgrServicesPayJunctionConvenienceFees', 'Convenience Fees')
            .assert.containsText('@accountingMgrServicesPayJunctionConfiguration', 'Configuration')
            .assert.attributeEquals('@accountingMgrServicesPayJunctionInvoices', 'href', 'http://web/payjunction.php?task=allinvoices')
            .assert.attributeEquals('@accountingMgrServicesPayJunctionPayments', 'href', 'http://web/payjunction.php?task=allpayments')
            .assert.attributeEquals('@accountingMgrServicesPayJunctionConvenienceFees', 'href', 'http://web/payjunction.php?task=convenience')
            .assert.attributeEquals('@accountingMgrServicesPayJunctionConfiguration', 'href', 'http://web/payjunctioncfg.php')

            .click('@accountingMgrServicesPayJunction')
            .assert.hidden('@accountingMgrServicesPayJunctionInvoices')
            .assert.hidden('@accountingMgrServicesPayJunctionPayments')
            .assert.hidden('@accountingMgrServicesPayJunctionConvenienceFees')
            .assert.hidden('@accountingMgrServicesPayJunctionConfiguration')

            .click('@accountingMgrServicesSmartTuition')
            .assert.visible('@accountingMgrServicesSmartTuitionConfiguration')
            .assert.containsText('@accountingMgrServicesSmartTuitionConfiguration', 'Configuration')
            .assert.attributeEquals('@accountingMgrServicesSmartTuitionConfiguration', 'href', 'http://web/smarttuitioncfg.php')

            .click('@accountingMgrServicesSmartTuition')
            .assert.hidden('@accountingMgrServicesSmartTuitionConfiguration')

            .click('@accountingMgrServicesPayPal')
            .assert.visible('@accountingMgrServicesPayPalOnlinePayments')
            .assert.visible('@accountingMgrServicesPayPalInvoices')
            .assert.visible('@accountingMgrServicesPayPalConfiguration')
            .assert.containsText('@accountingMgrServicesPayPalOnlinePayments', 'Online Payments')
            .assert.containsText('@accountingMgrServicesPayPalInvoices', 'Invoices')
            .assert.containsText('@accountingMgrServicesPayPalConfiguration', 'Configuration')
            .assert.attributeEquals('@accountingMgrServicesPayPalOnlinePayments', 'href', 'http://web/paypal.php?task=allpayments')
            .assert.attributeEquals('@accountingMgrServicesPayPalInvoices', 'href', 'http://web/paypal.php?task=allinvoices')
            .assert.attributeEquals('@accountingMgrServicesPayPalConfiguration', 'href', 'http://web/paypalcfg.php')

            .click('@accountingMgrServicesPayPal')
            .assert.hidden('@accountingMgrServicesPayPalOnlinePayments')
            .assert.hidden('@accountingMgrServicesPayPalInvoices')
            .assert.hidden('@accountingMgrServicesPayPalConfiguration')

            .click('@accountingMgrServicesEFunds')
            .assert.visible('@accountingMgrServicesEFundsPayments')
            .assert.visible('@accountingMgrServicesEFundsTransactions')
            .assert.visible('@accountingMgrServicesEFundsRemittance')
            .assert.visible('@accountingMgrServicesEFundsConfiguration')
            .assert.containsText('@accountingMgrServicesEFundsPayments', 'Payments')
            .assert.containsText('@accountingMgrServicesEFundsTransactions', 'Transactions')
            .assert.containsText('@accountingMgrServicesEFundsRemittance', 'Remittance')
            .assert.containsText('@accountingMgrServicesEFundsConfiguration', 'Configuration')
            .assert.attributeEquals('@accountingMgrServicesEFundsPayments', 'href', 'http://web/efunds.php?task=allpayments')
            .assert.attributeEquals('@accountingMgrServicesEFundsTransactions', 'href', 'http://web/efunds.php?task=allinvoices')
            .assert.attributeEquals('@accountingMgrServicesEFundsRemittance', 'href', 'http://web/efundsremittance.php')
            .assert.attributeEquals('@accountingMgrServicesEFundsConfiguration', 'href', 'http://web/efundscfg.php')

            .click('@accountingMgrServicesEFunds')
            .assert.hidden('@accountingMgrServicesEFundsPayments')
            .assert.hidden('@accountingMgrServicesEFundsTransactions')
            .assert.hidden('@accountingMgrServicesEFundsRemittance')
            .assert.hidden('@accountingMgrServicesEFundsConfiguration')

            .click('@accountingMgrServices')
            .assert.hidden('@accountingMgrServicesDwolla')
            .assert.hidden('@accountingMgrServicesPayJunction')
            .assert.hidden('@accountingMgrServicesSmartTuition')
            .assert.hidden('@accountingMgrServicesPayPal')
            .assert.hidden('@accountingMgrServicesEFunds')

            .click('@accountingMgr')
            .assert.hidden('@accountingMgrSchool')
            .assert.hidden('@accountingMgrFamilies')
            .assert.hidden('@accountingMgrBanking')
            .assert.hidden('@accountingMgrEmployees')
            .assert.hidden('@accountingMgrServices')
            .assert.hidden('@accountingMgrConfiguration')
            .assert.hidden('@accountingMgrReports')

            .click('@cafeteriaMgr')
            .assert.visible('@cafeteriaMgrFood')
            .assert.visible('@cafeteriaMgrMenu')
            .assert.visible('@cafeteriaMgrCycles')
            .assert.visible('@cafeteriaMgrOrders')
            .assert.visible('@cafeteriaMgrPricePlans')
            .assert.visible('@cafeteriaMgrNotifications')
            .assert.visible('@cafeteriaMgrAccounts')
            .assert.visible('@cafeteriaMgrReports')
            .assert.containsText('@cafeteriaMgrFood', 'Food')
            .assert.containsText('@cafeteriaMgrMenu', 'Menu')
            .assert.containsText('@cafeteriaMgrCycles', 'Cycles')
            .assert.containsText('@cafeteriaMgrOrders', 'Orders')
            .assert.containsText('@cafeteriaMgrPricePlans', 'Price Plans')
            .assert.containsText('@cafeteriaMgrNotifications', 'Notifications')
            .assert.containsText('@cafeteriaMgrAccounts', '\273 Accounts')
            .assert.containsText('@cafeteriaMgrReports', 'Reports')
            .assert.attributeEquals('@cafeteriaMgrFood', 'href', 'http://web/lunchmeals.php?tab=0')
            .assert.attributeEquals('@cafeteriaMgrMenu', 'href', 'http://web/lunchcal.php?tab=1')
            .assert.attributeEquals('@cafeteriaMgrCycles', 'href', 'http://web/lunchcycle.php?tab=2')
            .assert.attributeEquals('@cafeteriaMgrOrders', 'href', 'http://web/lunchorders.php?tab=3')
            .assert.attributeEquals('@cafeteriaMgrPricePlans', 'href', 'http://web/lunchpriceplans.php')
            .assert.attributeEquals('@cafeteriaMgrNotifications', 'href', 'http://web/lunchnotification.php')
            .assert.attributeEquals('@cafeteriaMgrAccounts', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@cafeteriaMgrReports', 'href', 'http://web/reports.php?type=17')

            .click('@cafeteriaMgrAccounts')
            .assert.visible('@cafeteriaMgrAccountsFamily')
            .assert.visible('@cafeteriaMgrAccountsEmployee')
            .assert.containsText('@cafeteriaMgrAccountsFamily', 'Family')
            .assert.containsText('@cafeteriaMgrAccountsEmployee', 'Employee')
            .assert.attributeEquals('@cafeteriaMgrAccountsFamily', 'href', 'http://web/lunchaccounts.php?task=family')
            .assert.attributeEquals('@cafeteriaMgrAccountsEmployee', 'href', 'http://web/lunchaccounts.php?task=employee')

            .click('@cafeteriaMgrAccounts')
            .assert.hidden('@cafeteriaMgrAccountsFamily')
            .assert.hidden('@cafeteriaMgrAccountsEmployee')

            .click('@cafeteriaMgr')
            .assert.hidden('@cafeteriaMgrFood')
            .assert.hidden('@cafeteriaMgrMenu')
            .assert.hidden('@cafeteriaMgrCycles')
            .assert.hidden('@cafeteriaMgrOrders')
            .assert.hidden('@cafeteriaMgrPricePlans')
            .assert.hidden('@cafeteriaMgrNotifications')
            .assert.hidden('@cafeteriaMgrAccounts')
            .assert.hidden('@cafeteriaMgrReports')

            .click('@childcareMgr')
            .assert.visible('@childcareMgrAccounts')
            .assert.visible('@childcareMgrDaily')
            .assert.visible('@childcareMgrWeekly')
            .assert.visible('@childcareMgrMonthly')
            .assert.visible('@childcareMgrNotifications')
            .assert.visible('@childcareMgrReports')
            .assert.containsText('@childcareMgrAccounts', 'Accounts')
            .assert.containsText('@childcareMgrDaily', '\273 Daily')
            .assert.containsText('@childcareMgrWeekly', '\273 Weekly')
            .assert.containsText('@childcareMgrMonthly', '\273 Monthly')
            .assert.containsText('@childcareMgrNotifications', 'Notification')
            .assert.containsText('@childcareMgrReports', 'Reports')
            .assert.attributeEquals('@childcareMgrAccounts', 'href', 'http://web/daycareaccounts.php')
            .assert.attributeEquals('@childcareMgrDaily', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@childcareMgrWeekly', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@childcareMgrMonthly', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@childcareMgrNotifications', 'href', 'http://web/childcarenotification.php')
            .assert.attributeEquals('@childcareMgrReports', 'href', 'http://web/reports.php?type=26')

            .click('@childcareMgrDaily')
            .assert.visible('@childcareMgrDailyCheckInOut')
            .assert.visible('@childcareMgrDailyDailyCharges')
            .assert.visible('@childcareMgrDailyPricePlans')
            .assert.containsText('@childcareMgrDailyCheckInOut', 'Check In/Out')
            .assert.containsText('@childcareMgrDailyDailyCharges', 'Daily Charges')
            .assert.containsText('@childcareMgrDailyPricePlans', 'Price Plans')
            .assert.attributeEquals('@childcareMgrDailyCheckInOut', 'href', 'http://web/daycarecheck.php')
            .assert.attributeEquals('@childcareMgrDailyDailyCharges', 'href', 'http://web/daycareorders.php?grade=99')
            .assert.attributeEquals('@childcareMgrDailyPricePlans', 'href', 'http://web/daycarepriceplans.php')

            .click('@childcareMgrDaily')
            .assert.hidden('@childcareMgrDailyCheckInOut')
            .assert.hidden('@childcareMgrDailyDailyCharges')
            .assert.hidden('@childcareMgrDailyPricePlans')

            .click('@childcareMgrWeekly')
            .assert.visible('@childcareMgrWeeklyCharges')
            .assert.visible('@childcareMgrWeeklyBillingSetup')
            .assert.visible('@childcareMgrWeeklyPricePlans')
            .assert.containsText('@childcareMgrWeeklyCharges', 'Charges')
            .assert.containsText('@childcareMgrWeeklyBillingSetup', 'Billing Setup')
            .assert.containsText('@childcareMgrWeeklyPricePlans', 'Price Plans')
            .assert.attributeEquals('@childcareMgrWeeklyCharges', 'href', 'http://web/daycarecharges.php')
            .assert.attributeEquals('@childcareMgrWeeklyBillingSetup', 'href', 'http://web/daycarebilling.php')
            .assert.attributeEquals('@childcareMgrWeeklyPricePlans', 'href', 'http://web/daycareweeklyplans.php')

            .click('@childcareMgrWeekly')
            .assert.hidden('@childcareMgrWeeklyCharges')
            .assert.hidden('@childcareMgrWeeklyBillingSetup')
            .assert.hidden('@childcareMgrWeeklyPricePlans')

            .click('@childcareMgrMonthly')
            .assert.visible('@childcareMgrMonthlyCharges')
            .assert.visible('@childcareMgrMonthlyBillingSetup')
            .assert.visible('@childcareMgrMonthlyPricePlans')
            .assert.containsText('@childcareMgrMonthlyCharges', 'Charges')
            .assert.containsText('@childcareMgrMonthlyBillingSetup', 'Billing Setup')
            .assert.containsText('@childcareMgrMonthlyPricePlans', 'Price Plans')
            .assert.attributeEquals('@childcareMgrMonthlyCharges', 'href', 'http://web/daycaremonthlycharges.php')
            .assert.attributeEquals('@childcareMgrMonthlyBillingSetup', 'href', 'http://web/daycaremonthlybilling.php')
            .assert.attributeEquals('@childcareMgrMonthlyPricePlans', 'href', 'http://web/daycaremonthlyplans.php')

            .click('@childcareMgrMonthly')
            .assert.hidden('@childcareMgrMonthlyCharges')
            .assert.hidden('@childcareMgrMonthlyBillingSetup')
            .assert.hidden('@childcareMgrMonthlyPricePlans')

            .click('@childcareMgr')
            .assert.hidden('@childcareMgrAccounts')
            .assert.hidden('@childcareMgrDaily')
            .assert.hidden('@childcareMgrWeekly')
            .assert.hidden('@childcareMgrMonthly')
            .assert.hidden('@childcareMgrNotifications')
            .assert.hidden('@childcareMgrReports')

            .click('@donationMgr')
            .assert.visible('@donationMgrDonors')
            .assert.visible('@donationMgrDonations')
            .assert.visible('@donationMgrCampaings')
            .assert.visible('@donationMgrReports')
            .assert.containsText('@donationMgrDonors', '\273 Donors')
            .assert.containsText('@donationMgrDonations', '\273 Donations')
            .assert.containsText('@donationMgrCampaings', 'Campaigns')
            .assert.containsText('@donationMgrReports', 'Reports')
            .assert.attributeEquals('@donationMgrDonors', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@donationMgrDonations', 'href', 'http://web/schoolmenu.php#')
            .assert.attributeEquals('@donationMgrCampaings', 'href', 'http://web/donorcampaigns.php')
            .assert.attributeEquals('@donationMgrReports', 'href', 'http://web/reports.php?type=22')

            .click('@donationMgrDonors')
            .assert.visible('@donationMgrDonorsNewDonors')
            .assert.visible('@donationMgrDonorsByContact')
            .assert.visible('@donationMgrDonorsPledges')
            .assert.containsText('@donationMgrDonorsNewDonors', 'New Donors')
            .assert.containsText('@donationMgrDonorsByContact', 'by Contact')
            .assert.containsText('@donationMgrDonorsPledges', 'Pledges')
            .assert.attributeEquals('@donationMgrDonorsNewDonors', 'href', 'http://web/donors.php?task=new')
            .assert.attributeEquals('@donationMgrDonorsByContact', 'href', 'http://web/donors.php?task=bycontact')
            .assert.attributeEquals('@donationMgrDonorsPledges', 'href', 'http://web/donorpledges.php')

            .click('@donationMgrDonors')
            .assert.hidden('@donationMgrDonorsNewDonors')
            .assert.hidden('@donationMgrDonorsByContact')
            .assert.hidden('@donationMgrDonorsPledges')

            .click('@donationMgrDonations')
            .assert.visible('@donationMgrDonationsReceive')
            .assert.visible('@donationMgrDonationsProcess')
            .assert.containsText('@donationMgrDonationsReceive', 'Receive')
            .assert.containsText('@donationMgrDonationsProcess', 'Process')
            .assert.attributeEquals('@donationMgrDonationsReceive', 'href', 'http://web/donordonations.php?task=receive')
            .assert.attributeEquals('@donationMgrDonationsProcess', 'href', 'http://web/donordonations.php?task=pending')

            .click('@donationMgrDonations')
            .assert.hidden('@donationMgrDonationsReceive')
            .assert.hidden('@donationMgrDonationsProcess')

            .click('@donationMgr')
            .assert.hidden('@donationMgrDonors')
            .assert.hidden('@donationMgrDonations')
            .assert.hidden('@donationMgrCampaings')
            .assert.hidden('@donationMgrReports')

            .click('@financial')
            .assert.hidden('@accountingMgr')
            .assert.hidden('@cafeteriaMgr')
            .assert.hidden('@childcareMgr')
            .assert.hidden('@donationMgr')

        client.frame(null);

        client.end();
    }
};
