module.exports = {
    tags: ['specialtiesTest', 'menuTests'],

    'Specialties Menu Test': (client) => {

        var page = client.page.login();

        page.navigate()
            .schoolLogin();

        client.frame(1);
        client.page.menu()
            .assert.visible('@specialties')
            .assert.containsText('@specialties', '\273 Specialties')
            .assert.attributeEquals('@specialties', 'href', page.menu() + '/schoolmenu.php#')

            .assert.hidden('@athleticDirector')
            .assert.hidden('@athleticDirectorSports')
            .assert.hidden('@athleticDirectorTeams')
            .assert.hidden('@athleticDirectorScoreboard')
            .assert.hidden('@athleticDirectorEquipment')

            .assert.hidden('@nursesOffice')
            .assert.hidden('@nursesOfficeDailyLogs')
            .assert.hidden('@nursesOfficeStudents')
            .assert.hidden('@nursesOfficeConfiguration')
            .assert.hidden('@nursesOfficeConfigurationComplaints')
            .assert.hidden('@nursesOfficeConfigurationMedications')
            .assert.hidden('@nursesOfficeConfigurationImmunizations')
            .assert.hidden('@nursesOfficeReports')

            .assert.hidden('@ptConferences')
            .assert.hidden('@ptConferencesTeachers')
            .assert.hidden('@ptConferencesByDate')
            .assert.hidden('@ptConferencesByTeacher')
            .assert.hidden('@ptConferencesConfiguration')

            .assert.hidden('@discipline')
            .assert.hidden('@disciplineStudents')
            .assert.hidden('@disciplineDailyLogs')
            .assert.hidden('@disciplineDetentions')
            .assert.hidden('@disciplineConfiguration')
            .assert.hidden('@disciplineReports')

            .assert.hidden('@serviceMgr')
            .assert.hidden('@serviceMgrStudents')
            .assert.hidden('@serviceMgrFamilies')
            .assert.hidden('@serviceMgrDailyLogs')
            .assert.hidden('@serviceMgrOpportunites')
            .assert.hidden('@serviceMgrReports')

            .assert.hidden('@connectionMgr')
            .assert.hidden('@connectionMgrStudents')
            .assert.hidden('@connectionMgrDailyLogs')
            .assert.hidden('@connectionMgrInitiator')
            .assert.hidden('@connectionMgrReports')

            .assert.hidden('@tranportationMgr')
            .assert.hidden('@tranportationMgrBusRoutes')
            .assert.hidden('@tranportationMgrFieldTrips')
            .assert.hidden('@tranportationMgrCarpoolMgr')
            .assert.hidden('@tranportationMgrParkingPasses')
            .assert.hidden('@tranportationMgrReports')

            .assert.hidden('@volunteerMgr')
            .assert.hidden('@volunteerMgrEvents')

            .assert.hidden('@libraryMgr')
            .assert.hidden('@libraryMgrBook')
            .assert.hidden('@libraryMgrStudents')
            .assert.hidden('@libraryMgrStudents')
            .assert.hidden('@libraryMgrCheckIn')
            .assert.hidden('@libraryMgrCheckOut')
            .assert.hidden('@libraryMgrWhatsOut')

            .assert.hidden('@libraryMgrBooks')
            .assert.hidden('@libraryMgrBooksLibrary')
            .assert.hidden('@libraryMgrBooksTextBooks')
            .assert.hidden('@libraryMgrBooksInventoryLibrary')

            .assert.hidden('@libraryMgrSearch')
            .assert.hidden('@libraryMgrSearchLocal')
            .assert.hidden('@libraryMgrSearchGoogle')

            .assert.hidden('@libraryMgrConfiguration')
            .assert.hidden('@libraryMgrConfigurationLocations')
            .assert.hidden('@libraryMgrConfigurationImport')
            .assert.hidden('@libraryMgrConfigurationSetup')

            .assert.hidden('@libraryMgrReports')

            .assert.hidden('@auctionMgr')
            .assert.hidden('@auctionMgrStaff')
            .assert.hidden('@auctionMgrAuctions')
            .assert.hidden('@auctionMgrAuctionItems')
            .assert.hidden('@auctionMgrDonorCompanies')
            .assert.hidden('@auctionMgrReports')

            .click('@specialties')
            .assert.visible('@athleticDirector')
            .assert.visible('@nursesOffice')
            .assert.visible('@ptConferences')
            .assert.visible('@discipline')
            .assert.visible('@serviceMgr')
            .assert.visible('@connectionMgr')
            .assert.visible('@tranportationMgr')
            .assert.visible('@volunteerMgr')
            .assert.visible('@libraryMgr')
            .assert.visible('@auctionMgr')
            .assert.containsText('@athleticDirector', '\273 Athletic Director')
            .assert.containsText('@nursesOffice', '\273 Nurse\'s Office')
            .assert.containsText('@ptConferences', '\273 P/T Conference')
            .assert.containsText('@discipline', '\273 Discipline Mgr')
            .assert.containsText('@serviceMgr', '\273 Service Mgr')
            .assert.containsText('@connectionMgr', '\273 Connection Mgr')
            .assert.containsText('@tranportationMgr', '\273 Transportation Mgr')
            .assert.containsText('@volunteerMgr', '\273 Volunteer Mgr')
            .assert.containsText('@libraryMgr', '\273 Library Mgr')
            .assert.containsText('@auctionMgr', '\273 Auction Mgr')
            .assert.attributeEquals('@athleticDirector', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@nursesOffice', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@ptConferences', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@discipline', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@serviceMgr', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@connectionMgr', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@tranportationMgr', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@volunteerMgr', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@libraryMgr', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@auctionMgr', 'href', page.menu() + '/schoolmenu.php#')

            .click('@athleticDirector')
            .assert.visible('@athleticDirectorSports')
            .assert.visible('@athleticDirectorTeams')
            .assert.visible('@athleticDirectorScoreboard')
            .assert.visible('@athleticDirectorEquipment')
            .assert.containsText('@athleticDirectorSports', 'Sports')
            .assert.containsText('@athleticDirectorTeams', 'Teams')
            .assert.containsText('@athleticDirectorScoreboard', 'Scoreboard')
            .assert.containsText('@athleticDirectorEquipment', 'Equipment')
            .assert.attributeEquals('@athleticDirectorSports', 'href', page.menu() + '/adsports.php')
            .assert.attributeEquals('@athleticDirectorTeams', 'href', page.menu() + '/adteams.php')
            .assert.attributeEquals('@athleticDirectorScoreboard', 'href', page.menu() + '/adscoreboard.php')
            .assert.attributeEquals('@athleticDirectorEquipment', 'href', page.menu() + '/eqinventory.php')

            .click('@athleticDirector')
            .assert.hidden('@athleticDirectorSports')
            .assert.hidden('@athleticDirectorTeams')
            .assert.hidden('@athleticDirectorScoreboard')
            .assert.hidden('@athleticDirectorEquipment')

            .click('@nursesOffice')
            .assert.visible('@nursesOfficeDailyLogs')
            .assert.visible('@nursesOfficeStudents')
            .assert.visible('@nursesOfficeConfiguration')
            .assert.visible('@nursesOfficeReports')
            .assert.containsText('@nursesOfficeDailyLogs', 'Daily Logs')
            .assert.containsText('@nursesOfficeStudents', 'Students')
            .assert.containsText('@nursesOfficeConfiguration', '\273 Configuration')
            .assert.containsText('@nursesOfficeReports', 'Reports')
            .assert.attributeEquals('@nursesOfficeDailyLogs', 'href', page.menu() + '/medicallogs.php')
            .assert.attributeEquals('@nursesOfficeStudents', 'href', page.menu() + '/medicalstudents.php')
            .assert.attributeEquals('@nursesOfficeReports', 'href', page.menu() + '/reports.php?type=19')

            .click('@nursesOfficeConfiguration')
            .assert.visible('@nursesOfficeConfigurationComplaints')
            .assert.visible('@nursesOfficeConfigurationMedications')
            .assert.visible('@nursesOfficeConfigurationImmunizations')
            .assert.containsText('@nursesOfficeConfigurationComplaints', 'Complaints')
            .assert.containsText('@nursesOfficeConfigurationMedications', 'Medications')
            .assert.containsText('@nursesOfficeConfigurationImmunizations', 'Immunizations')
            .assert.attributeEquals('@nursesOfficeConfigurationComplaints', 'href', page.menu() + '/medicalcomplaints.php')
            .assert.attributeEquals('@nursesOfficeConfigurationMedications', 'href', page.menu() + '/medicalmedications.php')
            .assert.attributeEquals('@nursesOfficeConfigurationImmunizations', 'href', page.menu() + '/medicalshots.php')

            .click('@nursesOfficeConfiguration')
            .assert.hidden('@nursesOfficeConfigurationComplaints')
            .assert.hidden('@nursesOfficeConfigurationMedications')
            .assert.hidden('@nursesOfficeConfigurationImmunizations')

            .click('@nursesOffice')
            .assert.hidden('@nursesOfficeDailyLogs')
            .assert.hidden('@nursesOfficeStudents')
            .assert.hidden('@nursesOfficeConfiguration')
            .assert.hidden('@nursesOfficeReports')

            .click('@ptConferences')
            .assert.visible('@ptConferencesTeachers')
            .assert.visible('@ptConferencesByDate')
            .assert.visible('@ptConferencesByTeacher')
            .assert.visible('@ptConferencesConfiguration')
            .assert.containsText('@ptConferencesTeachers', 'Teachers')
            .assert.containsText('@ptConferencesByDate', 'by Date')
            .assert.containsText('@ptConferencesByTeacher', 'by Teacher')
            .assert.containsText('@ptConferencesConfiguration', 'Configuration')
            .assert.attributeEquals('@ptConferencesTeachers', 'href', page.menu() + '/ptconf_teachers.php')
            .assert.attributeEquals('@ptConferencesByDate', 'href', page.menu() + '/ptconf_admin.php?view=date')
            .assert.attributeEquals('@ptConferencesByTeacher', 'href', page.menu() + '/ptconf_admin.php?view=staff')
            .assert.attributeEquals('@ptConferencesConfiguration', 'href', page.menu() + '/ptconf_admin.php?view=config')

            .click('@ptConferences')
            .assert.hidden('@ptConferencesTeachers')
            .assert.hidden('@ptConferencesByDate')
            .assert.hidden('@ptConferencesByTeacher')
            .assert.hidden('@ptConferencesConfiguration')

            .click('@discipline')
            .assert.visible('@disciplineStudents')
            .assert.visible('@disciplineDailyLogs')
            .assert.visible('@disciplineDetentions')
            .assert.visible('@disciplineConfiguration')
            .assert.visible('@disciplineReports')
            .assert.containsText('@disciplineStudents', 'Students')
            .assert.containsText('@disciplineDailyLogs', 'Daily Logs')
            .assert.containsText('@disciplineDetentions', 'Detentions')
            .assert.containsText('@disciplineConfiguration', 'Configuration')
            .assert.containsText('@disciplineReports', 'Reports')
            .assert.attributeEquals('@disciplineStudents', 'href', page.menu() + '/discipline.php')
            .assert.attributeEquals('@disciplineDailyLogs', 'href', page.menu() + '/disciplinelogs.php')
            .assert.attributeEquals('@disciplineDetentions', 'href', page.menu() + '/disciplinedetentions.php')
            .assert.attributeEquals('@disciplineConfiguration', 'href', page.menu() + '/disciplineviolations.php')
            .assert.attributeEquals('@disciplineReports', 'href', page.menu() + '/reports.php?type=20')

            .click('@discipline')
            .assert.hidden('@disciplineStudents')
            .assert.hidden('@disciplineDailyLogs')
            .assert.hidden('@disciplineDetentions')
            .assert.hidden('@disciplineConfiguration')
            .assert.hidden('@disciplineReports')

            .click('@serviceMgr')
            .assert.visible('@serviceMgrStudents')
            .assert.visible('@serviceMgrFamilies')
            .assert.visible('@serviceMgrDailyLogs')
            .assert.visible('@serviceMgrOpportunites')
            .assert.visible('@serviceMgrReports')
            .assert.containsText('@serviceMgrStudents', 'Students')
            .assert.containsText('@serviceMgrFamilies', 'Families')
            .assert.containsText('@serviceMgrDailyLogs', 'Daily Logs')
            .assert.containsText('@serviceMgrOpportunites', 'Opportunities')
            .assert.containsText('@serviceMgrReports', 'Reports')
            .assert.attributeEquals('@serviceMgrStudents', 'href', page.menu() + '/service.php?task=liststudents')
            .assert.attributeEquals('@serviceMgrFamilies', 'href', page.menu() + '/service.php?task=listfamilies')
            .assert.attributeEquals('@serviceMgrDailyLogs', 'href', page.menu() + '/servicelogs.php')
            .assert.attributeEquals('@serviceMgrOpportunites', 'href', page.menu() + '/serviceops.php')
            .assert.attributeEquals('@serviceMgrReports', 'href', page.menu() + '/reports.php?type=23')

            .click('@serviceMgr')
            .assert.hidden('@serviceMgrStudents')
            .assert.hidden('@serviceMgrFamilies')
            .assert.hidden('@serviceMgrDailyLogs')
            .assert.hidden('@serviceMgrOpportunites')
            .assert.hidden('@serviceMgrReports')

            .click('@connectionMgr')
            .assert.visible('@connectionMgrStudents')
            .assert.visible('@connectionMgrDailyLogs')
            .assert.visible('@connectionMgrInitiator')
            .assert.visible('@connectionMgrReports')
            .assert.containsText('@connectionMgrStudents', 'Students')
            .assert.containsText('@connectionMgrDailyLogs', 'Daily Logs')
            .assert.containsText('@connectionMgrInitiator', 'Initiator')
            .assert.containsText('@connectionMgrReports', 'Reports')
            .assert.attributeEquals('@connectionMgrStudents', 'href', page.menu() + '/connect.php?task=liststudents')
            .assert.attributeEquals('@connectionMgrDailyLogs', 'href', page.menu() + '/connectlogs.php')
            .assert.attributeEquals('@connectionMgrInitiator', 'href', page.menu() + '/connectroles.php')
            .assert.attributeEquals('@connectionMgrReports', 'href', page.menu() + '/reports.php?type=28')

            .click('@connectionMgr')
            .assert.hidden('@connectionMgrStudents')
            .assert.hidden('@connectionMgrDailyLogs')
            .assert.hidden('@connectionMgrInitiator')
            .assert.hidden('@connectionMgrReports')

            .click('@tranportationMgr')
            .assert.visible('@tranportationMgrBusRoutes')
            .assert.visible('@tranportationMgrFieldTrips')
            .assert.visible('@tranportationMgrCarpoolMgr')
            .assert.visible('@tranportationMgrParkingPasses')
            .assert.visible('@tranportationMgrReports')
            .assert.containsText('@tranportationMgrBusRoutes', 'Bus Routes')
            .assert.containsText('@tranportationMgrFieldTrips', 'Field Trips')
            .assert.containsText('@tranportationMgrCarpoolMgr', 'Carpool Mgr')
            .assert.containsText('@tranportationMgrParkingPasses', 'Parking Passes')
            .assert.containsText('@tranportationMgrReports', 'Reports')
            .assert.attributeEquals('@tranportationMgrBusRoutes', 'href', page.menu() + '/tm_busroute.php')
            .assert.attributeEquals('@tranportationMgrFieldTrips', 'href', page.menu() + '/tm_fieldtrip.php')
            .assert.attributeEquals('@tranportationMgrCarpoolMgr', 'href', page.menu() + '/tm_carpool.php')
            .assert.attributeEquals('@tranportationMgrParkingPasses', 'href', page.menu() + '/tm_parkingpass.php')
            .assert.attributeEquals('@tranportationMgrReports', 'href', page.menu() + '/reports.php?type=33')

            .click('@tranportationMgr')
            .assert.hidden('@tranportationMgrBusRoutes')
            .assert.hidden('@tranportationMgrFieldTrips')
            .assert.hidden('@tranportationMgrCarpoolMgr')
            .assert.hidden('@tranportationMgrParkingPasses')
            .assert.hidden('@tranportationMgrReports')

            .click('@volunteerMgr')
            .assert.visible('@volunteerMgrEvents')
            .assert.containsText('@volunteerMgrEvents', 'Events')
            .assert.attributeEquals('@volunteerMgrEvents', 'href', page.menu() + '/volunteer.php?view=1')

            .click('@libraryMgr')
            .assert.visible('@libraryMgrBook')
            .assert.visible('@libraryMgrStudents')
            .assert.visible('@libraryMgrCheckIn')
            .assert.visible('@libraryMgrCheckOut')
            .assert.visible('@libraryMgrWhatsOut')
            .assert.visible('@libraryMgrBooks')
            .assert.visible('@libraryMgrSearch')
            .assert.visible('@libraryMgrConfiguration')
            .assert.visible('@libraryMgrReports')
            .assert.containsText('@libraryMgrBook', 'Book')
            .assert.containsText('@libraryMgrStudents', 'Students')
            .assert.containsText('@libraryMgrCheckIn', 'Check In')
            .assert.containsText('@libraryMgrCheckOut', 'Check Out')
            .assert.containsText('@libraryMgrWhatsOut', 'What\'s Out')
            .assert.containsText('@libraryMgrBooks', '\273 Books')
            .assert.containsText('@libraryMgrSearch', '\273 Search')
            .assert.containsText('@libraryMgrConfiguration', '\273 Configuration')
            .assert.containsText('@libraryMgrReports', 'Reports')
            .assert.attributeEquals('@libraryMgrBook', 'href', page.menu() + '/library.php?task=book')
            .assert.attributeEquals('@libraryMgrStudents', 'href', page.menu() + '/librarystudents.php')
            .assert.attributeEquals('@libraryMgrCheckIn', 'href', page.menu() + '/librarydesk.php?task=checkin')
            .assert.attributeEquals('@libraryMgrCheckOut', 'href', page.menu() + '/librarydesk.php?task=checkout')
            .assert.attributeEquals('@libraryMgrWhatsOut', 'href', page.menu() + '/librarydesk.php?task=whatsout&grade=99')
            .assert.attributeEquals('@libraryMgrBooks', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@libraryMgrSearch', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@libraryMgrConfiguration', 'href', page.menu() + '/schoolmenu.php#')
            .assert.attributeEquals('@libraryMgrReports', 'href', page.menu() + '/reports.php?type=30')

            .click('@libraryMgrBooks')
            .assert.visible('@libraryMgrBooksLibrary')
            .assert.visible('@libraryMgrBooksTextBooks')
            .assert.visible('@libraryMgrBooksInventoryLibrary')
            .assert.containsText('@libraryMgrBooksLibrary', 'Library')
            .assert.containsText('@libraryMgrBooksTextBooks', 'Textbooks')
            .assert.containsText('@libraryMgrBooksInventoryLibrary', 'Inventory Library')
            .assert.attributeEquals('@libraryMgrBooksLibrary', 'href', page.menu() + '/librarybooks.php')
            .assert.attributeEquals('@libraryMgrBooksTextBooks', 'href', page.menu() + '/libraryclassbooks.php')
            .assert.attributeEquals('@libraryMgrBooksInventoryLibrary', 'href', page.menu() + '/libraryinventory.php')

            .click('@libraryMgrBooks')
            .assert.hidden('@libraryMgrBooksLibrary')
            .assert.hidden('@libraryMgrBooksTextBooks')
            .assert.hidden('@libraryMgrBooksInventoryLibrary')

            .click('@libraryMgrSearch')
            .assert.visible('@libraryMgrSearchLocal')
            .assert.visible('@libraryMgrSearchGoogle')
            .assert.containsText('@libraryMgrSearchLocal', 'Local')
            .assert.containsText('@libraryMgrSearchGoogle', 'Google')
            .assert.attributeEquals('@libraryMgrSearchLocal', 'href', page.menu() + '/library.php?action=search')
            .assert.attributeEquals('@libraryMgrSearchGoogle', 'href', page.menu() + '/librarysearch.php')

            .click('@libraryMgrSearch')
            .assert.hidden('@libraryMgrSearchLocal')
            .assert.hidden('@libraryMgrSearchGoogle')

            .click('@libraryMgrConfiguration')
            .assert.visible('@libraryMgrConfigurationLocations')
            .assert.visible('@libraryMgrConfigurationImport')
            .assert.visible('@libraryMgrConfigurationSetup')
            .assert.containsText('@libraryMgrConfigurationLocations', 'Locations')
            .assert.containsText('@libraryMgrConfigurationImport', 'Import')
            .assert.containsText('@libraryMgrConfigurationSetup', 'Setup')
            .assert.attributeEquals('@libraryMgrConfigurationLocations', 'href', page.menu() + '/librarylocations.php')
            .assert.attributeEquals('@libraryMgrConfigurationImport', 'href', page.menu() + '/librarybookimport.php')
            .assert.attributeEquals('@libraryMgrConfigurationSetup', 'href', page.menu() + '/libraryconfig.php')

            .click('@libraryMgrConfiguration')
            .assert.hidden('@libraryMgrConfigurationLocations')
            .assert.hidden('@libraryMgrConfigurationImport')
            .assert.hidden('@libraryMgrConfigurationSetup')

            .click('@libraryMgr')
            .assert.hidden('@libraryMgrBook')
            .assert.hidden('@libraryMgrStudents')
            .assert.hidden('@libraryMgrCheckIn')
            .assert.hidden('@libraryMgrCheckOut')
            .assert.hidden('@libraryMgrWhatsOut')
            .assert.hidden('@libraryMgrBooks')
            .assert.hidden('@libraryMgrSearch')
            .assert.hidden('@libraryMgrConfiguration')
            .assert.hidden('@libraryMgrReports')

            .click('@auctionMgr')
            .assert.visible('@auctionMgrStaff')
            .assert.visible('@auctionMgrAuctions')
            .assert.visible('@auctionMgrAuctionItems')
            .assert.visible('@auctionMgrDonorCompanies')
            .assert.visible('@auctionMgrReports')
            .assert.containsText('@auctionMgrStaff', 'Staff')
            .assert.containsText('@auctionMgrAuctions', 'Auctions')
            .assert.containsText('@auctionMgrAuctionItems', 'Items')
            .assert.containsText('@auctionMgrDonorCompanies', 'Donor Companies')
            .assert.containsText('@auctionMgrReports', 'Reports')
            .assert.attributeEquals('@auctionMgrStaff', 'href', page.menu() + '/auction_staff.php')
            .assert.attributeEquals('@auctionMgrAuctions', 'href', page.menu() + '/auctions.php')
            .assert.attributeEquals('@auctionMgrAuctionItems', 'href', page.menu() + '/auctionitems.php')
            .assert.attributeEquals('@auctionMgrDonorCompanies', 'href', page.menu() + '/auctiondonors.php')
            .assert.attributeEquals('@auctionMgrReports', 'href', page.menu() + '/reports.php?type=21')

            .click('@specialties')

            .assert.hidden('@athleticDirector')
            .assert.hidden('@athleticDirectorSports')
            .assert.hidden('@athleticDirectorTeams')
            .assert.hidden('@athleticDirectorScoreboard')
            .assert.hidden('@athleticDirectorEquipment')

            .assert.hidden('@nursesOffice')
            .assert.hidden('@nursesOfficeDailyLogs')
            .assert.hidden('@nursesOfficeStudents')
            .assert.hidden('@nursesOfficeConfiguration')
            .assert.hidden('@nursesOfficeConfigurationComplaints')
            .assert.hidden('@nursesOfficeConfigurationMedications')
            .assert.hidden('@nursesOfficeConfigurationImmunizations')
            .assert.hidden('@nursesOfficeReports')

            .assert.hidden('@ptConferences')
            .assert.hidden('@ptConferencesTeachers')
            .assert.hidden('@ptConferencesByDate')
            .assert.hidden('@ptConferencesByTeacher')
            .assert.hidden('@ptConferencesConfiguration')

            .assert.hidden('@discipline')
            .assert.hidden('@disciplineStudents')
            .assert.hidden('@disciplineDailyLogs')
            .assert.hidden('@disciplineDetentions')
            .assert.hidden('@disciplineConfiguration')
            .assert.hidden('@disciplineReports')

            .assert.hidden('@serviceMgr')
            .assert.hidden('@serviceMgrStudents')
            .assert.hidden('@serviceMgrFamilies')
            .assert.hidden('@serviceMgrDailyLogs')
            .assert.hidden('@serviceMgrOpportunites')
            .assert.hidden('@serviceMgrReports')

            .assert.hidden('@connectionMgr')
            .assert.hidden('@connectionMgrStudents')
            .assert.hidden('@connectionMgrDailyLogs')
            .assert.hidden('@connectionMgrInitiator')
            .assert.hidden('@connectionMgrReports')

            .assert.hidden('@tranportationMgr')
            .assert.hidden('@tranportationMgrBusRoutes')
            .assert.hidden('@tranportationMgrFieldTrips')
            .assert.hidden('@tranportationMgrCarpoolMgr')
            .assert.hidden('@tranportationMgrParkingPasses')
            .assert.hidden('@tranportationMgrReports')

            .assert.hidden('@volunteerMgr')
            .assert.hidden('@volunteerMgrEvents')

            .assert.hidden('@libraryMgr')
            .assert.hidden('@libraryMgrBook')
            .assert.hidden('@libraryMgrStudents')
            .assert.hidden('@libraryMgrStudents')
            .assert.hidden('@libraryMgrCheckIn')
            .assert.hidden('@libraryMgrCheckOut')
            .assert.hidden('@libraryMgrWhatsOut')

            .assert.hidden('@libraryMgrBooks')
            .assert.hidden('@libraryMgrBooksLibrary')
            .assert.hidden('@libraryMgrBooksTextBooks')
            .assert.hidden('@libraryMgrBooksInventoryLibrary')

            .assert.hidden('@libraryMgrSearch')
            .assert.hidden('@libraryMgrSearchLocal')
            .assert.hidden('@libraryMgrSearchGoogle')

            .assert.hidden('@libraryMgrConfiguration')
            .assert.hidden('@libraryMgrConfigurationLocations')
            .assert.hidden('@libraryMgrConfigurationImport')
            .assert.hidden('@libraryMgrConfigurationSetup')

            .assert.hidden('@libraryMgrReports')

            .assert.hidden('@auctionMgr')
            .assert.hidden('@auctionMgrStaff')
            .assert.hidden('@auctionMgrAuctions')
            .assert.hidden('@auctionMgrAuctionItems')
            .assert.hidden('@auctionMgrDonorCompanies')
            .assert.hidden('@auctionMgrReports')

        client.frame(null);

        client.end();
    }
};
