module.exports = {
    tags: ['utilitiesTest', 'menuTests'],

    'Utilities Menu Test': (client) => {

        var page = client.page.login();

        page.navigate()
            .schoolLogin();

        client.frame(1);
        client.page.menu()
            .assert.visible('@utilities')
            .assert.containsText('@utilities', '\273 Utilities')
            .assert.attributeEquals('@utilities', 'href', page.url() + '/schoolmenu.php#')

            .assert.hidden('@assetMgr')
            .assert.hidden('@assetMgrInventory')
            .assert.hidden('@assetMgrTypes')
            .assert.hidden('@assetMgrAdditionalFields')
            .assert.hidden('@assetMgrReports')

            .assert.hidden('@eventMgr')
            .assert.hidden('@eventMgrManagedEvents')
            .assert.hidden('@eventMgrRegistration')
            .assert.hidden('@eventMgrParticipants')
            .assert.hidden('@eventMgrReports')

            .assert.hidden('@facilityMgr')
            .assert.hidden('@facilityMgrLocations')
            .assert.hidden('@facilityMgrBuildings')
            .assert.hidden('@facilityMgrRooms')
            .assert.hidden('@facilityMgrPlanner')
            .assert.hidden('@facilityMgrActivities')
            .assert.hidden('@facilityMgrSearch')

            .assert.hidden('@timecardMgr')
            .assert.hidden('@timecardMgrByDay')
            .assert.hidden('@timecardMgrByPeriod')
            .assert.hidden('@timecardMgrByEmployee')
            .assert.hidden('@timecardMgrRequests')
            .assert.hidden('@timecardMgrTasks')
            .assert.hidden('@timecardMgrConfiguration')
            .assert.hidden('@timecardMgrReports')

            .assert.hidden('@workflowMgr')
            .assert.hidden('@workflowMgrByStatus')
            .assert.hidden('@workflowMgrByAuthor')
            .assert.hidden('@workflowMgrByCategory')
            .assert.hidden('@workflowMgrByClassroom')
            .assert.hidden('@workflowMgrCategories')

            .assert.hidden('@databaseMgr')
            .assert.hidden('@databaseMgrPublicTables')
            .assert.hidden('@databaseMgrPrivateTables')

            .assert.hidden('@onlineFormMgr')
            .assert.hidden('@onlineFormMgrActive')
            .assert.hidden('@onlineFormMgrNonActive')

            .assert.hidden('@knowledgeBase')
            .assert.hidden('@knowledgeBasePublished')
            .assert.hidden('@knowledgeBasePending')

            .click('@utilities')
            .assert.visible('@assetMgr')
            .assert.visible('@eventMgr')
            .assert.visible('@facilityMgr')
            .assert.visible('@timecardMgr')
            .assert.visible('@workflowMgr')
            .assert.visible('@databaseMgr')
            .assert.visible('@onlineFormMgr')
            .assert.visible('@knowledgeBase')
            .assert.containsText('@eventMgr', '\273 Event Mgr')
            .assert.containsText('@facilityMgr', '\273 Facility Mgr')
            .assert.containsText('@timecardMgr', '\273 Timecard Mgr')
            .assert.containsText('@workflowMgr', '\273 Workflow Mgr')
            .assert.containsText('@databaseMgr', '\273 Database Mgr')
            .assert.containsText('@onlineFormMgr', '\273 Online Form Mgr')
            .assert.containsText('@knowledgeBase', '\273 Knowledge Base')
            .assert.attributeEquals('@assetMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@eventMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@facilityMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@timecardMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@workflowMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@databaseMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@onlineFormMgr', 'href', page.url() + '/schoolmenu.php#')
            .assert.attributeEquals('@knowledgeBase', 'href', page.url() + '/schoolmenu.php#')

            .click('@assetMgr')
            .assert.visible('@assetMgrInventory')
            .assert.visible('@assetMgrTypes')
            .assert.visible('@assetMgrAdditionalFields')
            .assert.visible('@assetMgrReports')
            .assert.containsText('@assetMgrInventory', 'Inventory')
            .assert.containsText('@assetMgrTypes', 'Types')
            .assert.containsText('@assetMgrAdditionalFields', 'Additional Fields')
            .assert.containsText('@assetMgrReports', 'Reports')
            .assert.attributeEquals('@assetMgrInventory', 'href', page.url() + '/assets.php')
            .assert.attributeEquals('@assetMgrTypes', 'href', page.url() + '/assettypes.php')
            .assert.attributeEquals('@assetMgrAdditionalFields', 'href', page.url() + '/assetstatistics.php?task=list')
            .assert.attributeEquals('@assetMgrReports', 'href', page.url() + '/reports.php?type=34')

            .click('@assetMgr')
            .assert.hidden('@assetMgrInventory')
            .assert.hidden('@assetMgrTypes')
            .assert.hidden('@assetMgrAdditionalFields')
            .assert.hidden('@assetMgrReports')

            .click('@eventMgr')
            .assert.visible('@eventMgrManagedEvents')
            .assert.visible('@eventMgrRegistration')
            .assert.visible('@eventMgrParticipants')
            .assert.visible('@eventMgrReports')
            .assert.containsText('@eventMgrManagedEvents', 'Managed Events')
            .assert.containsText('@eventMgrRegistration', 'Registration')
            .assert.containsText('@eventMgrParticipants', 'Participants')
            .assert.containsText('@eventMgrReports', 'Reports')
            .assert.attributeEquals('@eventMgrManagedEvents', 'href', page.url() + '/eventproperty.php?task=list')
            .assert.attributeEquals('@eventMgrRegistration', 'href', page.url() + '/eventregistrations.php')
            .assert.attributeEquals('@eventMgrParticipants', 'href', page.url() + '/eventparticipants.php')
            .assert.attributeEquals('@eventMgrReports', 'href', page.url() + '/reports.php?type=24')

            .click('@eventMgr')
            .assert.hidden('@eventMgrManagedEvents')
            .assert.hidden('@eventMgrRegistration')
            .assert.hidden('@eventMgrParticipants')
            .assert.hidden('@eventMgrReports')

            .click('@facilityMgr')
            .assert.visible('@facilityMgrLocations')
            .assert.visible('@facilityMgrBuildings')
            .assert.visible('@facilityMgrRooms')
            .assert.visible('@facilityMgrPlanner')
            .assert.visible('@facilityMgrActivities')
            .assert.visible('@facilityMgrSearch')
            .assert.containsText('@facilityMgrLocations', 'Locations')
            .assert.containsText('@facilityMgrBuildings', 'Buildings')
            .assert.containsText('@facilityMgrRooms', 'Rooms')
            .assert.containsText('@facilityMgrPlanner', 'Planner')
            .assert.containsText('@facilityMgrActivities', 'Activities')
            .assert.containsText('@facilityMgrSearch', 'Search')
            .assert.attributeEquals('@facilityMgrLocations', 'href', page.url() + '/facilitylocations.php')
            .assert.attributeEquals('@facilityMgrBuildings', 'href', page.url() + '/facilitybuildings.php')
            .assert.attributeEquals('@facilityMgrRooms', 'href', page.url() + '/facilityrooms.php')
            .assert.attributeEquals('@facilityMgrPlanner', 'href', page.url() + '/facilityplanner.php')
            .assert.attributeEquals('@facilityMgrActivities', 'href', page.url() + '/facilityactivities.php')
            .assert.attributeEquals('@facilityMgrSearch', 'href', page.url() + '/facilitysearch.php')

            .click('@facilityMgr')
            .assert.hidden('@facilityMgrLocations')
            .assert.hidden('@facilityMgrBuildings')
            .assert.hidden('@facilityMgrRooms')
            .assert.hidden('@facilityMgrPlanner')
            .assert.hidden('@facilityMgrActivities')
            .assert.hidden('@facilityMgrSearch')

            .click('@timecardMgr')
            .assert.visible('@timecardMgrByDay')
            .assert.visible('@timecardMgrByPeriod')
            .assert.visible('@timecardMgrByEmployee')
            .assert.visible('@timecardMgrRequests')
            .assert.visible('@timecardMgrTasks')
            .assert.visible('@timecardMgrConfiguration')
            .assert.visible('@timecardMgrReports')
            .assert.containsText('@timecardMgrByDay', 'by Day')
            .assert.containsText('@timecardMgrByPeriod', 'by Period')
            .assert.containsText('@timecardMgrByEmployee', 'by Employee')
            .assert.containsText('@timecardMgrRequests', 'Requests')
            .assert.containsText('@timecardMgrTasks', 'Tasks')
            .assert.containsText('@timecardMgrConfiguration', 'Configuration')
            .assert.containsText('@timecardMgrReports', 'Reports')
            .assert.attributeEquals('@timecardMgrByDay', 'href', page.url() + '/timecard.php?task=day')
            .assert.attributeEquals('@timecardMgrByPeriod', 'href', page.url() + '/timecard.php?task=period')
            .assert.attributeEquals('@timecardMgrByEmployee', 'href', page.url() + '/timecard.php?task=users')
            .assert.attributeEquals('@timecardMgrRequests', 'href', page.url() + '/timeoff.php')
            .assert.attributeEquals('@timecardMgrTasks', 'href', page.url() + '/timetasks.php')
            .assert.attributeEquals('@timecardMgrConfiguration', 'href', page.url() + '/timeperiods.php')
            .assert.attributeEquals('@timecardMgrReports', 'href', page.url() + '/reports.php?type=36')

            .click('@timecardMgr')
            .assert.hidden('@timecardMgrByDay')
            .assert.hidden('@timecardMgrByPeriod')
            .assert.hidden('@timecardMgrByEmployee')
            .assert.hidden('@timecardMgrRequests')
            .assert.hidden('@timecardMgrTasks')
            .assert.hidden('@timecardMgrConfiguration')
            .assert.hidden('@timecardMgrReports')

            .click('@workflowMgr')
            .assert.visible('@workflowMgrByStatus')
            .assert.visible('@workflowMgrByAuthor')
            .assert.visible('@workflowMgrByCategory')
            .assert.visible('@workflowMgrByClassroom')
            .assert.visible('@workflowMgrCategories')
            .assert.containsText('@workflowMgrByStatus', 'by Status')
            .assert.containsText('@workflowMgrByAuthor', 'by Author')
            .assert.containsText('@workflowMgrByCategory', 'by Category')
            .assert.containsText('@workflowMgrByClassroom', 'by Classroom')
            .assert.containsText('@workflowMgrCategories', 'Categories')
            .assert.attributeEquals('@workflowMgrByStatus', 'href', page.url() + '/ticket.php?task=bystatus')
            .assert.attributeEquals('@workflowMgrByAuthor', 'href', page.url() + '/ticket.php?task=byauthor')
            .assert.attributeEquals('@workflowMgrByCategory', 'href', page.url() + '/ticket.php?task=bycatagory')
            .assert.attributeEquals('@workflowMgrByClassroom', 'href', page.url() + '/ticket.php?task=byproject')
            .assert.attributeEquals('@workflowMgrCategories', 'href', page.url() + '/ticketcatagories.php')

            .click('@workflowMgr')
            .assert.hidden('@workflowMgrByStatus')
            .assert.hidden('@workflowMgrByAuthor')
            .assert.hidden('@workflowMgrByCategory')
            .assert.hidden('@workflowMgrByClassroom')
            .assert.hidden('@workflowMgrCategories')

            .click('@databaseMgr')
            .assert.visible('@databaseMgrPublicTables')
            .assert.visible('@databaseMgrPrivateTables')
            .assert.containsText('@databaseMgrPublicTables', 'Public Tables')
            .assert.containsText('@databaseMgrPrivateTables', 'Private Tables')
            .assert.attributeEquals('@databaseMgrPublicTables', 'href', page.url() + '/databases.php?task=list&type=1')
            .assert.attributeEquals('@databaseMgrPrivateTables', 'href', page.url() + '/databases.php?task=list&type=2')

            .click('@databaseMgr')
            .assert.hidden('@databaseMgrPublicTables')
            .assert.hidden('@databaseMgrPrivateTables')

            .click('@onlineFormMgr')
            .assert.visible('@onlineFormMgrActive')
            .assert.visible('@onlineFormMgrNonActive')
            .assert.containsText('@onlineFormMgrActive', 'Active')
            .assert.containsText('@onlineFormMgrNonActive', 'Non Active')
            .assert.attributeEquals('@onlineFormMgrActive', 'href', page.url() + '/forms.php?task=list&type=active')
            .assert.attributeEquals('@onlineFormMgrNonActive', 'href', page.url() + '/forms.php?task=list&type=nonactive')

            .click('@onlineFormMgr')
            .assert.hidden('@onlineFormMgrActive')
            .assert.hidden('@onlineFormMgrNonActive')

            .click('@knowledgeBase')
            .assert.visible('@knowledgeBasePublished')
            .assert.visible('@knowledgeBasePending')
            .assert.containsText('@knowledgeBasePublished', 'Published')
            .assert.containsText('@knowledgeBasePending', 'Pending')
            .assert.attributeEquals('@knowledgeBasePublished', 'href', page.url() + '/knowledge.php?task=list')
            .assert.attributeEquals('@knowledgeBasePending', 'href', page.url() + '/knowledge.php?task=pending')

            .click('@knowledgeBase')
            .assert.hidden('@knowledgeBasePublished')
            .assert.hidden('@knowledgeBasePending')

            .click('@utilities')

            .assert.hidden('@assetMgr')
            .assert.hidden('@assetMgrInventory')
            .assert.hidden('@assetMgrTypes')
            .assert.hidden('@assetMgrAdditionalFields')
            .assert.hidden('@assetMgrReports')

            .assert.hidden('@eventMgr')
            .assert.hidden('@eventMgrManagedEvents')
            .assert.hidden('@eventMgrRegistration')
            .assert.hidden('@eventMgrParticipants')
            .assert.hidden('@eventMgrReports')

            .assert.hidden('@facilityMgr')
            .assert.hidden('@facilityMgrLocations')
            .assert.hidden('@facilityMgrBuildings')
            .assert.hidden('@facilityMgrRooms')
            .assert.hidden('@facilityMgrPlanner')
            .assert.hidden('@facilityMgrActivities')
            .assert.hidden('@facilityMgrSearch')

            .assert.hidden('@timecardMgr')
            .assert.hidden('@timecardMgrByDay')
            .assert.hidden('@timecardMgrByPeriod')
            .assert.hidden('@timecardMgrByEmployee')
            .assert.hidden('@timecardMgrRequests')
            .assert.hidden('@timecardMgrTasks')
            .assert.hidden('@timecardMgrConfiguration')
            .assert.hidden('@timecardMgrReports')

            .assert.hidden('@workflowMgr')
            .assert.hidden('@workflowMgrByStatus')
            .assert.hidden('@workflowMgrByAuthor')
            .assert.hidden('@workflowMgrByCategory')
            .assert.hidden('@workflowMgrByClassroom')
            .assert.hidden('@workflowMgrCategories')

            .assert.hidden('@databaseMgr')
            .assert.hidden('@databaseMgrPublicTables')
            .assert.hidden('@databaseMgrPrivateTables')

            .assert.hidden('@onlineFormMgr')
            .assert.hidden('@onlineFormMgrActive')
            .assert.hidden('@onlineFormMgrNonActive')

            .assert.hidden('@knowledgeBase')
            .assert.hidden('@knowledgeBasePublished')
            .assert.hidden('@knowledgeBasePending')

        client.frame(null);

        client.end();
    }
};
