module.exports = {
    elements: {
        breadcrumb: 'body > form > ul.breadcrumb',
        currentTab: 'body > form > ul.nav.nav-tabs > li:nth-child(1) > a',
        allTab: 'body > form > ul.nav.nav-tabs > li:nth-child(2) > a',
        submitBtn: 'body > form > ul.nav.nav-tabs > input',
        currentCheckbox: 'body > form > table > tbody > tr > td:nth-child(1) > input[type="checkbox"]',
        currentLabel: 'body > form > table > tbody > tr > td:nth-child(1)',
        parentsLabel: 'body > form > div > table > tbody > tr.se-bold',
        title1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(1) > td.se-right',
        title1Select: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(1) > td:nth-child(2) > select',
        firstName1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(2) > td.se-right',
        firstName1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(2) > td:nth-child(2) > input',
        lastName1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(3) > td.se-right',
        lastName1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(3) > td:nth-child(2) > input',
        address1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(4) > td.se-right',
        address1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(4) > td:nth-child(2) > input',
        addressSecondary1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(5) > td.se-right',
        addressSecondary1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(5) > td:nth-child(2) > input',
        city1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(6) > td.se-right',
        city1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(6) > td:nth-child(2) > input',
        state1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(7) > td.se-right',
        state1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(7) > td:nth-child(2) > input',
        zip1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(8) > td.se-right',
        zip1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(8) > td:nth-child(2) > input',
        country1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(9) > td.se-right',
        country1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(9) > td:nth-child(2) > input',
        home1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(10) > td.se-right',
        home1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(10) > td:nth-child(2) > input',
        work1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(11) > td.se-right',
        work1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(11) > td:nth-child(2) > input',
        cell1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(12) > td.se-right',
        cell1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(12) > td:nth-child(2) > input',
        email1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(13) > td.se-right',
        email1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(13) > td:nth-child(2) > input',
        relationship1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(14) > td.se-right',
        relationship1Select: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(14) > td:nth-child(2) > select',
        company1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(15) > td.se-right',
        company1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(15) > td:nth-child(2) > input',
        companyTitle1Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(16) > td.se-right',
        companyTitle1Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(16) > td:nth-child(2) > input',
        title2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(1) > td.se-right',
        title2Select: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(1) > td:nth-child(2) > select',
        firstName2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(2) > td.se-right',
        firstName2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(2) > td:nth-child(2) > input',
        lastName2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(3) > td.se-right',
        lastName2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(3) > td:nth-child(2) > input',
        address2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(4) > td.se-right',
        address2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(4) > td:nth-child(2) > input',
        addressSecondary2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(5) > td.se-right',
        addressSecondary2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(5) > td:nth-child(2) > input',
        city2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(6) > td.se-right',
        city2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(6) > td:nth-child(2) > input',
        state2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(7) > td.se-right',
        state2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(7) > td:nth-child(2) > input',
        zip2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(8) > td.se-right',
        zip2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(8) > td:nth-child(2) > input',
        country2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(9) > td.se-right',
        country2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(9) > td:nth-child(2) > input',
        home2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(10) > td.se-right',
        home2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(10) > td:nth-child(2) > input',
        work2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(11) > td.se-right',
        work2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(11) > td:nth-child(2) > input',
        cell2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(12) > td.se-right',
        cell2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(12) > td:nth-child(2) > input',
        email2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(13) > td.se-right',
        email2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(13) > td:nth-child(2) > input',
        relationship2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(14) > td.se-right',
        relationship2Select: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(14) > td:nth-child(2) > select',
        company2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(15) > td.se-right',
        company2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(15) > td:nth-child(2) > input',
        companyTitle2Label: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(16) > td.se-right',
        companyTitle2Input: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(16) > td:nth-child(2) > input',
        studentsLabel: 'body > form > div > table > tbody > tr:nth-child(3) > td',
        firstNameHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(1)',
        middleNameHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(2)',
        lastNameHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(3)',
        dobHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(4)',
        gradeHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(5)',
        genderHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(6)',
        firstNameInput: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > input',
        middleNameInput: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > input',
        lastNameInput: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(2) > td:nth-child(3) > input',
        monthSelect: '#bmonth0',
        daySelect: '#bday0',
        yearSelect: '#byear0',
        gradeSelect: '#sgrade0',
        genderSelect: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(2) > td:nth-child(6) > select',
        ethnicitySelect: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(3) > td > table > tbody > tr > td > select',
        chooseRaceBtn: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(3) > td > table > tbody > tr > td > input.btn.btn-micro.se-bold'
    }
};
