module.exports = {
    elements: {
        breadcrumb: 'body > form > ul.breadcrumb',
        currentTab: 'body > form > ul.nav.nav-tabs > li:nth-child(1) > a',
        allTab: 'body > form > ul.nav.nav-tabs > li:nth-child(2) > a',
        submitBtn: 'body > form > ul.nav.nav-tabs > input',
        currentCheckbox: 'body > form > table > tbody > tr > td:nth-child(1) > input[type="checkbox"]',
        currentLabel: 'body > form > table > tbody > tr > td:nth-child(1)',
        parentsLabel: 'body > form > div > table > tbody > tr.se-bold',
        titleLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(1) > td.se-right',
        titleSelect: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(1) > td:nth-child(2) > select',
        firstNameLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(2) > td.se-right',
        firstNameInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(2) > td:nth-child(2) > input',
        lastNameLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(3) > td.se-right',
        lastNameInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(3) > td:nth-child(2) > input',
        addressLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(4) > td.se-right',
        addressInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(4) > td:nth-child(2) > input',
        addressSecondaryLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(5) > td.se-right',
        addressSecondaryInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(5) > td:nth-child(2) > input',
        cityLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(6) > td.se-right',
        cityInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(6) > td:nth-child(2) > input',
        stateLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(7) > td.se-right',
        stateInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(7) > td:nth-child(2) > input',
        zipLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(8) > td.se-right',
        zipInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(8) > td:nth-child(2) > input',
        countryLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(9) > td.se-right',
        countryInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(9) > td:nth-child(2) > input',
        homeLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(10) > td.se-right',
        homeInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(10) > td:nth-child(2) > input',
        workLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(11) > td.se-right',
        workInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(11) > td:nth-child(2) > input',
        cellLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(12) > td.se-right',
        cellInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(12) > td:nth-child(2) > input',
        emailLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(13) > td.se-right',
        emailInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(13) > td:nth-child(2) > input',
        relationshipLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(14) > td.se-right',
        relationshipSelect: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(14) > td:nth-child(2) > select',
        companyLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(15) > td.se-right',
        companyInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(15) > td:nth-child(2) > input',
        companyTitleLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(16) > td.se-right',
        companyTitleInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1) > table > tbody > tr:nth-child(16) > td:nth-child(2) > input',
        titleLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(1) > td.se-right',
        titleSelect2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(1) > td:nth-child(2) > select',
        firstNameLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(2) > td.se-right',
        firstNameInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(2) > td:nth-child(2) > input',
        lastNameLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(3) > td.se-right',
        lastNameInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(3) > td:nth-child(2) > input',
        addressLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(4) > td.se-right',
        addressInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(4) > td:nth-child(2) > input',
        addressSecondaryLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(5) > td.se-right',
        addressSecondaryInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(5) > td:nth-child(2) > input',
        cityLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(6) > td.se-right',
        cityInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(6) > td:nth-child(2) > input',
        stateLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(7) > td.se-right',
        stateInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(7) > td:nth-child(2) > input',
        zipLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(8) > td.se-right',
        zipInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(8) > td:nth-child(2) > input',
        countryLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(9) > td.se-right',
        countryInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(9) > td:nth-child(2) > input',
        homeLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(10) > td.se-right',
        homeInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(10) > td:nth-child(2) > input',
        workLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(11) > td.se-right',
        workInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(11) > td:nth-child(2) > input',
        cellLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(12) > td.se-right',
        cellInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(12) > td:nth-child(2) > input',
        emailLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(13) > td.se-right',
        emailInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(13) > td:nth-child(2) > input',
        relationshipLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(14) > td.se-right',
        relationshipSelect2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(14) > td:nth-child(2) > select',
        companyLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(15) > td.se-right',
        companyInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(15) > td:nth-child(2) > input',
        companyTitleLabel2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(16) > td.se-right',
        companyTitleInput2: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > table > tbody > tr:nth-child(16) > td:nth-child(2) > input',
        studentsLabel: 'body > form > div > table > tbody > tr:nth-child(3) > td',
        firstNameHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(1)',
        middleNameHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(2)',
        lastNameHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(3)',
        dobHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(4)',
        gradeHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(5)',
        genderHeader: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(6)',
        firstNameInput: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(2) > td:nth-child(1) > input',
        middleNameInput: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(2) > td:nth-child(2) > input',
        lastNameInput: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(2) > td:nth-child(3) > input',
        monthSelect: '#bmonth0',
        daySelect: '#bday0',
        yearSelect: '#byear0',
        gradeSelect: '#sgrade0',
        genderSelect: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(2) > td:nth-child(6) > select',
        ethnicitySelect: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(3) > td > table > tbody > tr > td > select',
        chooseRaceBtn: 'body > form > div > table > tbody > tr:nth-child(5) > td > table > tbody > tr:nth-child(3) > td > table > tbody > tr > td > input.btn.btn-micro.se-bold'
    }
};
