module.exports = {
    elements: {
        breadcrumb: 'body > ul.breadcrumb',
        lastNameTab: 'body > form > ul > li:nth-child(1) > a',
        categoriesTab: 'body > form > ul > li:nth-child(2) > a',
        searchTab: 'body > form > ul > li:nth-child(3) > a',
        inputField: 'body > form > ul > input[type="text"]:nth-child(4)',
        searchBtn: 'body > form > ul > input[type="submit"]:nth-child(6)',
        newContactBtn: 'body > form > ul > input.btn.btn-mini.btn-primary.pull-right',
        nameTitle: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(1) > td:nth-child(2)',
        companyTitle: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(1) > td:nth-child(3)',
        descriptionTitle: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(1) > td:nth-child(4)',
        phoneTitle: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(1) > td:nth-child(5)',
        //Last Name Tab Elements
        a: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(2) > a',
        b: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(3) > a',
        c: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(4) > a',
        d: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(5) > a',
        e: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(6) > a',
        f: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(7) > a',
        g: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(8) > a',
        h: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(9) > a',
        i: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(10) > a',
        j: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(11) > a',
        k: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(12) > a',
        l: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(13) > a',
        m: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(14) > a',
        n: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(15) > a',
        o: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(16) > a',
        p: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(17) > a',
        q: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(18) > a',
        r: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(19) > a',
        s: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(20) > a',
        t: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(21) > a',
        u: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(22) > a',
        v: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(23) > a',
        w: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(24) > a',
        x: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(25) > a',
        y: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(26) > a',
        z: 'body > form > table > tbody > tr > td > table > tbody > tr > td:nth-child(27) > a',
        janeName: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > font > a',
        janeEnvelope: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(2) > td:nth-child(6) > a',
        janeNote: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(2) > td:nth-child(7) > a:nth-child(1)',
        janeDocs: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(2) > td:nth-child(7) > a:nth-child(2)',
        janeCard: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(2) > td:nth-child(7) > a:nth-child(3)',
        johnName: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(3) > td:nth-child(2) > font > a',
        johnEnvelope: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(3) > td:nth-child(6) > a',
        johnNote: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(3) > td:nth-child(7) > a:nth-child(1)',
        johnDocs: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(3) > td:nth-child(7) > a:nth-child(2)',
        johnCard: 'body > form > table > tbody > tr > td > div > table > tbody > tr:nth-child(3) > td:nth-child(7) > a:nth-child(3)'
    }
};
