module.exports = {
    elements: {
        breadcrumb: '.breadcrumb',
        studentsTab: '#parameters > ul:nth-child(1) > li:nth-child(2) > a',
        generateBtn: '#parameters > ul:nth-child(1) > input:nth-child(3)',
        quarterLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(1)',
        quarterSelect: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(1) > td:nth-child(2) > select:nth-child(1)',
        gradeLabel: '#parameters > table:nth-child(2) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1)',
        gradeInput: '#dgrade',
        formatLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(2) > td:nth-child(1)',
        formatSelect: '#format',
        label1Label: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(3) > td:nth-child(1)',
        label1Input: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(3) > td:nth-child(2) > input:nth-child(1)',
        label2Label: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(4) > td:nth-child(1)',
        label2Input: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(4) > td:nth-child(2) > input:nth-child(1)',
        memoLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(1)',
        memoTextArea: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(5) > td:nth-child(2) > textarea:nth-child(1)',
        memoTextCounter: '#countdown',
        academicOptionsHeader: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(6)',
        displayLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(7) > td:nth-child(1)',
        displaySelect: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(7) > td:nth-child(2) > select:nth-child(1)',
        quarterGradesCheckbox: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(8) > td:nth-child(2) > input:nth-child(1)',
        quarterGradesLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(8) > td:nth-child(2) > font:nth-child(2)',
        semesterGradesCheckbox: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(9) > td:nth-child(2) > input:nth-child(1)',
        semesterGradesLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(9) > td:nth-child(2) > font:nth-child(2)',
        semesterFinalCheckbox: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(10) > td:nth-child(2) > input:nth-child(1)',
        semesterFinalLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(10) > td:nth-child(2) > font:nth-child(2)',
        yearlyAverageCheckbox: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(11) > td:nth-child(2) > input:nth-child(1)',
        yearlyAverageLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(11) > td:nth-child(2) > font:nth-child(2)',
        finalGradeCheckbox: 'input.cb:nth-child(2)',
        finalGradeLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(12) > td:nth-child(2) > font:nth-child(3)',
        fontSizeLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(13) > td:nth-child(1)',
        fontSizeSelect: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(13) > td:nth-child(2) > select:nth-child(1)',
        fontFamilyLabel: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(13) > td:nth-child(2) > font:nth-child(2)',
        fontFamilySelect: '.input-small',
        archivingOptionsHeader: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(14)',
        versionMgtBtn: 'input.btn:nth-child(1)',
        quarterInput: '#left > table:nth-child(1) > tbody:nth-child(2) > tr:nth-child(15) > td:nth-child(2) > input:nth-child(1)',
        studentDocumentsCheckbox: '#doit > input:nth-child(1)',
        studentDocumentsLabel: '#doit > font:nth-child(2)',
        electronicSignatureCheckbox: '#sigrequired',
        electronicSignatureLabel: '#required > font:nth-child(2)',
    }
};
