module.exports = {
    elements: {
        breadcrumb: 'body > ul.breadcrumb',
        currentTab: 'body > form:nth-child(3) > ul > li:nth-child(1) > a',
        allTab: 'body > form:nth-child(3) > ul > li:nth-child(2) > a',
        newTab: 'body > form:nth-child(3) > ul > li:nth-child(3) > a',
        searchInput: 'body > form:nth-child(3) > ul > input[type="input"]:nth-child(4)',
        searchBtn: 'body > form:nth-child(3) > ul > input.btn.btn-mini.btn-primary.pull-right',
        listAll: '#theMainForm > table > tbody > tr > td:nth-child(1) > a',
        a: '#theMainForm > table > tbody > tr > td:nth-child(2) > a',
        b: '#theMainForm > table > tbody > tr > td:nth-child(3) > a',
        c: '#theMainForm > table > tbody > tr > td:nth-child(4) > a',
        d: '#theMainForm > table > tbody > tr > td:nth-child(5) > a',
        e: '#theMainForm > table > tbody > tr > td:nth-child(6) > a',
        f: '#theMainForm > table > tbody > tr > td:nth-child(7) > a',
        g: '#theMainForm > table > tbody > tr > td:nth-child(8) > a',
        h: '#theMainForm > table > tbody > tr > td:nth-child(9) > a',
        i: '#theMainForm > table > tbody > tr > td:nth-child(10) > a',
        j: '#theMainForm > table > tbody > tr > td:nth-child(11) > a',
        k: '#theMainForm > table > tbody > tr > td:nth-child(12) > a',
        l: '#theMainForm > table > tbody > tr > td:nth-child(13) > a',
        m: '#theMainForm > table > tbody > tr > td:nth-child(14) > a',
        n: '#theMainForm > table > tbody > tr > td:nth-child(15) > a',
        o: '#theMainForm > table > tbody > tr > td:nth-child(16) > a',
        p: '#theMainForm > table > tbody > tr > td:nth-child(17) > a',
        q: '#theMainForm > table > tbody > tr > td:nth-child(18) > a',
        r: '#theMainForm > table > tbody > tr > td:nth-child(19) > a',
        s: '#theMainForm > table > tbody > tr > td:nth-child(20) > a',
        t: '#theMainForm > table > tbody > tr > td:nth-child(21) > a',
        u: '#theMainForm > table > tbody > tr > td:nth-child(22) > a',
        v: '#theMainForm > table > tbody > tr > td:nth-child(23) > a',
        w: '#theMainForm > table > tbody > tr > td:nth-child(24) > a',
        x: '#theMainForm > table > tbody > tr > td:nth-child(25) > a',
        y: '#theMainForm > table > tbody > tr > td:nth-child(26) > a',
        z: '#theMainForm > table > tbody > tr > td:nth-child(27) > a',
        familyCount: '#theMainForm > table > tbody > tr > td:nth-child(28)',
        checkbox: '#theMainForm > div > table > tbody > tr.se-bg-gray.se-bold > td.se-center.setChecked > a',
        familyCodeHeader: '#theMainForm > div > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(2)',
        familyNameHeader: '#theMainForm > div > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(3)',
        addressHeader: '#theMainForm > div > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(4)',
        familyPhoneHeader: '#theMainForm > div > table > tbody > tr.se-bg-gray.se-bold > td:nth-child(5)',
        testCheckbox: '#theMainForm > div > table > tbody > tr.se-bg-pink > td:nth-child(1) > input',
        testFamilyCode: '#theMainForm > div > table > tbody > tr.se-bg-pink > td:nth-child(2) > font > b > a',
        testFamilyName: '#theMainForm > div > table > tbody > tr.se-bg-pink > td.se-nowrap',
        testFamilyAddress: '#theMainForm > div > table > tbody > tr.se-bg-pink > td:nth-child(4)'
    }
};
