module.exports = {
    elements: {
        breadcrumb: '.breadcrumb',
        addBtn: '.btn',
        listAll: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > a',
        a: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2) > a',
        b: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3) > a',
        c: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(4) > a',
        d: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(5) > a',
        e: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(6) > a',
        f: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(7) > a',
        g: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(8) > a',
        h: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(9) > a',
        i: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(10) > a',
        j: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(11) > a',
        k: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(12) > a',
        l: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(13) > a',
        m: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(14) > a',
        n: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(15) > a',
        o: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(16) > a',
        p: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(17) > a',
        q: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(18) > a',
        r: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(19) > a',
        s: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(20) > a',
        t: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(21) > a',
        u: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(22) > a',
        v: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(23) > a',
        w: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(24) > a',
        x: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(25) > a',
        y: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(26) > a',
        z: 'body > table:nth-child(5) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(27) > a',
        checkboxHeader: '.table > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > a',
        studentCodeHeader: '.table > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(4)',
        nameHeader: '.table > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(5)',
        gradeHeader: '.table > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(6)',
        expireHeader: '.table > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(7)',
        daysHeader: '.table > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(8)'
    }
};
