module.exports = {
    elements: {
        breadcrumb: '.breadcrumb',
        updateBtn: '.btn',
        notationTitle: '.tab-content > table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2)',
        gradeHeader: '.table-striped > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2)',
        valueHeader: '.table-striped > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3)',
        aPlusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2)',
        aPlusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(3) > input:nth-child(1)',
        aLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2)',
        aValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(3) > input:nth-child(1)',
        aMinusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2)',
        aMinusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(3) > input:nth-child(1)',
        bPlusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2)',
        bPlusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(3) > input:nth-child(1)',
        bLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(2)',
        bValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(3) > input:nth-child(1)',
        bMinusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(7) > td:nth-child(2)',
        bMinusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(7) > td:nth-child(3) > input:nth-child(1)',
        cPlusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(8) > td:nth-child(2)',
        cPlusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(8) > td:nth-child(3) > input:nth-child(1)',
        cLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(2)',
        cValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(3) > input:nth-child(1)',
        cMinusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(10) > td:nth-child(2)',
        cMinusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(10) > td:nth-child(3) > input:nth-child(1)',
        dPlusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(11) > td:nth-child(2)',
        dPlusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(11) > td:nth-child(3) > input:nth-child(1)',
        dLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(12) > td:nth-child(2)',
        dValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(12) > td:nth-child(3) > input:nth-child(1)',
        dMinusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(13) > td:nth-child(2)',
        dMinusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(13) > td:nth-child(3) > input:nth-child(1)',
        fPlusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(14) > td:nth-child(2)',
        fPlusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(14) > td:nth-child(3) > input:nth-child(1)',
        fLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(15) > td:nth-child(2)',
        fValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(15) > td:nth-child(3) > input:nth-child(1)',
        fMinusLabel: '.table-striped > tbody:nth-child(1) > tr:nth-child(16) > td:nth-child(2)',
        fMinusValue: '.table-striped > tbody:nth-child(1) > tr:nth-child(16) > td:nth-child(3) > input:nth-child(1)'
    }
};
