module.exports = {
    elements: {
        breadcrumb: '.breadcrumb',
        numericHeader: '.se-bg-gray > td:nth-child(1)',
        upperHeader: '.se-bg-gray > td:nth-child(2)',
        lowerHeader: '.se-bg-gray > td:nth-child(3)',
        valueHeader: '.se-bg-gray > td:nth-child(4)',
        labelHeader: '.se-bg-gray > td:nth-child(5)',
        scale1Numeric: '#mainTable > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1)',
        scale1Upper: '#mainTable > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2)',
        scale1Lower: '#mainTable > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(3)',
        scale1Value: '#mainTable > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(4)',
        scale1Label: '#mainTable > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(5)',
        scale1EditBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(6) > button:nth-child(1)',
        scale1DeleteBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(7) > img:nth-child(1)',
        scale2Numeric: '#mainTable > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(1)',
        scale2Upper: '#mainTable > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2)',
        scale2Lower: '#mainTable > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(3)',
        scale2Value: '#mainTable > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(4)',
        scale2Label: '#mainTable > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(5)',
        scale2EditBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(6) > button:nth-child(1)',
        scale2DeleteBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(7) > img:nth-child(1)',
        scale3Numeric: '#mainTable > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(1)',
        scale3Upper: '#mainTable > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2)',
        scale3Lower: '#mainTable > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(3)',
        scale3Value: '#mainTable > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(4)',
        scale3Label: '#mainTable > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(5)',
        scale3EditBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(6) > button:nth-child(1)',
        scale3DeleteBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(7) > img:nth-child(1)',
        scale4Numeric: '#mainTable > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(1)',
        scale4Upper: '#mainTable > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2)',
        scale4Lower: '#mainTable > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(3)',
        scale4Value: '#mainTable > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(4)',
        scale4Label: '#mainTable > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(5)',
        scale4EditBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(6) > button:nth-child(1)',
        scale4DeleteBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(7) > img:nth-child(1)',
        scale5Numeric: '#mainTable > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(1)',
        scale5Upper: '#mainTable > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(2)',
        scale5Lower: '#mainTable > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(3)',
        scale5Value: '#mainTable > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(4)',
        scale5Label: '#mainTable > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(5)',
        scale5EditBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(6) > button:nth-child(1)',
        scale5DeleteBtn: '#mainTable > tbody:nth-child(1) > tr:nth-child(6) > td:nth-child(7) > img:nth-child(1)',
        newScaleNumeric: '#sequence',
        newScaleUpper: '#upper',
        newScaleLower: '#lower',
        newScaleValue: '#calcvalue',
        newScaleLabel: '#label',
        newScaleAddBtn: 'input.btn'
    }
};
