module.exports = {
    elements: {
        breadcrumb: 'body > ul.breadcrumb',
        backMonthBtn: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(1) > tbody > tr > td:nth-child(1) > a',
        forwardMonthBtn: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(1) > tbody > tr > td:nth-child(3) > a',
        dateHeader: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(1) > tbody > tr > td:nth-child(2)',
        sun: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(1)',
        mon: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(2)',
        tue: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(3)',
        wed: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(4)',
        thu: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(5)',
        fri: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(6)',
        sat: 'body > table:nth-child(3) > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(7)',
        periodLabel: 'body > table:nth-child(3) > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(1) > font',
        periodSelect: 'body > table:nth-child(3) > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(1) > td:nth-child(1) > b > b > select',
        classHeader: 'body > table:nth-child(3) > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(2) > td:nth-child(3)',
        sectionHeader: 'body > table:nth-child(3) > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(2) > td:nth-child(4)',
        presentHeader: 'body > table:nth-child(3) > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(2) > td:nth-child(5)',
        absentHeader: 'body > table:nth-child(3) > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(2) > td:nth-child(6)',
        tardyHeader: 'body > table:nth-child(3) > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(2) > td:nth-child(7)',
        totalHeader: 'body > table:nth-child(3) > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(2) > td:nth-child(8)',
        attendanceTitle: 'body > table:nth-child(4)',
        attendanceName: 'body > div.tab-content > table > tbody > tr:nth-child(1) > td:nth-child(1)',
        attendancePresent: 'body > div.tab-content > table > tbody > tr:nth-child(1) > td:nth-child(2)',
        attendanceTardy: 'body > div.tab-content > table > tbody > tr:nth-child(1) > td:nth-child(3)',
        attendanceExcused: 'body > div.tab-content > table > tbody > tr:nth-child(1) > td:nth-child(4)',
        attendanceUnExcused: 'body > div.tab-content > table > tbody > tr:nth-child(1) > td:nth-child(5)',
        attendanceNotes: 'body > div.tab-content > table > tbody > tr:nth-child(1) > td:nth-child(6)'
    },
};
