module.exports = {
    elements: {
        breadcrumb: 'body > ul.breadcrumb',
        studentAttendanceBtn: 'body > ul.nav.nav-tabs > input',
        backMonthBtn: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(1) > tbody > tr > td:nth-child(1) > a',
        forwardMonthBtn: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(1) > tbody > tr > td:nth-child(3) > a',
        dateHeader: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(1) > tbody > tr > td:nth-child(2)',
        sun: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(1)',
        mon: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(2)',
        tue: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(3)',
        wed: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(4)',
        thu: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(5)',
        fri: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(6)',
        sat: 'body > div.tab-content > table > tbody > tr > td:nth-child(1) > table:nth-child(2) > tbody > tr:nth-child(1) > td:nth-child(7)',
        gradesHeader: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > table > tbody > tr:nth-child(2)',
        kindergarten: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(2)',
        firstGrade: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(3)',
        secondGrade: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(4)',
        thirdGrade: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(5)',
        fourthGrade: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(6)',
        fifthGrade: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(7)',
        sixthGrade: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(8)',
        seventhGrade: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(9)',
        eigthGrade: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(10)',
        freshman: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(11)',
        sophomore: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(12)',
        junior: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(13)',
        senior: 'body > div.tab-content > table > tbody > tr > td:nth-child(2) > div > table > tbody > tr:nth-child(14)',
        gradeTitle: 'body > div.tab-content > form > table > tbody > tr > td:nth-child(1)',
        batchAttendanceBtn: 'body > div.tab-content > form > table > tbody > tr > td:nth-child(2) > input',
        checkboxHeader: 'body > div.tab-content > form > div > table > tbody > tr > td.setChecked > a > img',
        studentNameHeader: 'body > div.tab-content > form > div > table > tbody > tr > td:nth-child(2)'
    }
};
