module.exports = {
    elements: {
        breadcrumb: '.breadcrumb',
        updateBtn: '.btn',
        processingOptionsHeader: 'tr.se-bg:nth-child(1)',
        classesLabel: '.table > tbody:nth-child(1) > tr:nth-child(2) > td',
        classesSelect: '.table > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > select',
        transferGradeLabel: '.table > tbody:nth-child(1) > tr:nth-child(3) > td',
        transferGradeSelect: '.table > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2) > select',
        transferGradeText: '.se-italic',
        weightedLabel: '.table > tbody:nth-child(1) > tr:nth-child(4) > td',
        weightedCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > input',
        weightedText: '.table > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > a:nth-child(2)',
        displayOptionsHeader: 'tr.se-bg:nth-child(5)',
        noteLabel: '.table > tbody:nth-child(1) > tr:nth-child(6) > td',
        noteInput: '.input-xxlarge',
        generalOptionsHeader: 'tr.se-bg:nth-child(7)',
        fontSizeLabel: '.table > tbody:nth-child(1) > tr:nth-child(8) > td',
        fontSizeSelect: '#fs',
        fontFamilyLabel: '.table > tbody:nth-child(1) > tr:nth-child(9) > td',
        fontFamilySelect: '.table > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(2) > select',
        gradeDisplayLabel: '.table > tbody:nth-child(1) > tr:nth-child(10) > td',
        gradeDisplaySelect: '#displaygrade',
        courseCodeLabel: '.table > tbody:nth-child(1) > tr:nth-child(11) > td',
        courseCodeCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(11) > td:nth-child(2) > input',
        classRankingLabel: '.table > tbody:nth-child(1) > tr:nth-child(12) > td',
        classRankingCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(12) > td:nth-child(2) > input',
        gradeYearsLabel: '.table > tbody:nth-child(1) > tr:nth-child(13) > td',
        gradeYearsCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(13) > td:nth-child(2) > input',
        GPALabel: '.table > tbody:nth-child(1) > tr:nth-child(14) > td',
        GPACheckbox: '.table > tbody:nth-child(1) > tr:nth-child(14) > td:nth-child(2) > input',
        GPAScaleLabel: '.table > tbody:nth-child(1) > tr:nth-child(15) > td',
        GPAScaleCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(15) > td:nth-child(2) > input',
        SATScoresLabel: '.table > tbody:nth-child(1) > tr:nth-child(16) > td',
        SATScoresCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(16) > td:nth-child(2) > input',
        ACTScoresLabel: '.table > tbody:nth-child(1) > tr:nth-child(17) > td',
        ACTScoresCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(17) > td:nth-child(2) > input',
        customScoresLabel: '.table > tbody:nth-child(1) > tr:nth-child(18) > td',
        customScoresCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(18) > td:nth-child(2) > input',
        numericAverageLabel: '.table > tbody:nth-child(1) > tr:nth-child(19) > td',
        numericAverageCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(19) > td:nth-child(2) > input',
        workInProgressLabel: '.table > tbody:nth-child(1) > tr:nth-child(20) > td',
        workInProgressCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(20) > td:nth-child(2) > input',
        signatureLabel: '.table > tbody:nth-child(1) > tr:nth-child(21) > td',
        signatureCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(21) > td:nth-child(2) > input',
        officialLabel: '.table > tbody:nth-child(1) > tr:nth-child(22) > td',
        officialCheckbox: '.table > tbody:nth-child(1) > tr:nth-child(22) > td:nth-child(2) > input',
        formatLabel: '.se-top',
        templateARadio: 'td.se-font:nth-child(1) > input',
        templateBRadio: 'td.se-font:nth-child(2) > input',
        templateAImage: 'tr.se-center:nth-child(2) > td:nth-child(1) > img',
        templateBImage: 'tr.se-center:nth-child(2) > td:nth-child(2) > img',
        templateALabel: 'tr.se-font > td:nth-child(1)',
        templateBLabel: 'tr.se-font > td:nth-child(2)'
    }
};
