module.exports = {
    elements: {
        breadcrumb: '.breadcrumb',
        searchField: '#searchstring',
        searchBtn: '#searchbtn',
        generateBtn: '#genbtn',
        dropDownBtn: '.dropdown-toggle',
        graduationYearSelect: '#gyear',
        gradeSelect: '#curgradelevel',
        homeroomSelect: '#homeroomid',
        statusSelect: '#sstatus',
        typeSelect: '#stype',
        templateSelect: '#templateid',
        all: 'td.se-font-small:nth-child(1) > a:nth-child(1)',
        a: 'td.se-center:nth-child(2) > a',
        b: 'td.se-center:nth-child(3) > a',
        c: 'td.se-center:nth-child(4) > a',
        d: 'td.se-center:nth-child(5) > a',
        e: 'td.se-center:nth-child(6) > a',
        f: 'td.se-center:nth-child(7) > a',
        g: 'td.se-center:nth-child(8) > a',
        h: 'td.se-center:nth-child(9) > a',
        i: 'td.se-center:nth-child(10) > a',
        j: 'td.se-center:nth-child(11) > a',
        k: 'td.se-center:nth-child(12) > a',
        l: 'td.se-center:nth-child(13) > a',
        m: 'td.se-center:nth-child(14) > a',
        n: 'td.se-center:nth-child(15) > a',
        o: 'td.se-center:nth-child(16) > a',
        p: 'td.se-center:nth-child(17) > a',
        q: 'td.se-center:nth-child(18) > a',
        r: 'td.se-center:nth-child(19) > a',
        s: 'td.se-center:nth-child(20) > a',
        t: 'td.se-center:nth-child(21) > a',
        u: 'td.se-center:nth-child(22) > a',
        v: 'td.se-center:nth-child(23) > a',
        w: 'td.se-center:nth-child(24) > a',
        x: 'td.se-center:nth-child(25) > a',
        y: 'td.se-center:nth-child(26) > a',
        z: 'td.se-center:nth-child(27) > a',
        checkboxHeader: 'table.table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(1) > a:nth-child(1)',
        codeHeader: 'table.table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(2)',
        nameHeader: 'table.table:nth-child(1) > tbody:nth-child(1) > tr:nth-child(1) > td:nth-child(3)',
        gradYearHeader: 'td.se-right:nth-child(4)',
        numericHeader: 'td.se-right:nth-child(5)',
        gpaHeader: 'td.se-right:nth-child(6)',
        rankingHeader: 'td.se-right:nth-child(7)',
    }
};
