module.exports = {
    elements: {
        breadcrumb: 'body > ul.breadcrumb',
        browseTab: 'body > ul.nav.nav-tabs > li:nth-child(1) > a',
        plannerTab: 'body > ul.nav.nav-tabs > li:nth-child(2) > a',
        activitiesTab: 'body > ul.nav.nav-tabs > li:nth-child(3) > a',
        searchTab: 'body > ul.nav.nav-tabs > li:nth-child(4) > a',
        goBtn: 'body > form:nth-child(5) > table > tbody > tr > td > input.btn.btn-mini.btn-primary.pull-right',
        backDayBtn: 'body > form:nth-child(6) > table > tbody > tr > td:nth-child(1) > a',
        forwardDayBtn: 'body > form:nth-child(6) > table > tbody > tr > td.se-right > a',
        dayHeader: 'body > form:nth-child(6) > table > tbody > tr > td.se-font-title.se-nowrap.se-bold',
        //Planner Tab
        plannerDateInput: '#plannerdate',
        sixAm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(3)',
        sevenAm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(4)',
        eightAm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(5)',
        nineAm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(6)',
        tenAm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(7)',
        elevenAm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(8)',
        twelvePm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(9)',
        onePm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(10)',
        twoPm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(11)',
        threePm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(12)',
        fourPm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(13)',
        fivePm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(14)',
        sixPm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(15)',
        sevenPm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(16)',
        eightPm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(17)',
        ninePm: 'body > form:nth-child(6) > div > table > tbody > tr.se-bg-gray > td:nth-child(18)',
        //Activies Tab
        activitiesDateInput: '#actdate',
        //Search Tab
        sBreadcrumb: 'body > form > ul.breadcrumb',
        sBrowseTab: 'body > form > ul.nav.nav-tabs > li:nth-child(1) > a',
        sPlannerTab: 'body > form > ul.nav.nav-tabs > li:nth-child(2) > a',
        sActivitiesTab: 'body > form > ul.nav.nav-tabs > li:nth-child(3) > a',
        sSearchTab: 'body > form > ul.nav.nav-tabs > li:nth-child(4) > a',
        nameLabel: 'body > form > div > table > tbody > tr:nth-child(1) > td:nth-child(1)',
        nameInput: 'body > form > div > table > tbody > tr:nth-child(1) > td:nth-child(2) > input[type="text"]',
        descriptionLabel: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(1)',
        descriptionInput: 'body > form > div > table > tbody > tr:nth-child(2) > td:nth-child(2) > input[type="text"]',
        buildingLabel: 'body > form > div > table > tbody > tr:nth-child(3) > td:nth-child(1)',
        buildingInput: 'body > form > div > table > tbody > tr:nth-child(3) > td:nth-child(2) > select',
        roomLabel: 'body > form > div > table > tbody > tr:nth-child(4) > td:nth-child(1)',
        roomInput: 'body > form > div > table > tbody > tr:nth-child(4) > td:nth-child(2) > input',
        capacityLabel: 'body > form > div > table > tbody > tr:nth-child(5) > td:nth-child(1)',
        capacityInput: 'body > form > div > table > tbody > tr:nth-child(5) > td:nth-child(2) > input',
        ownerLabel: 'body > form > div > table > tbody > tr:nth-child(6) > td:nth-child(1)',
        ownerInput: '#ownerid'
    }
};
