module.exports = {
    elements: {
        breadcrumb: 'body > form > ul.breadcrumb',
        startDateLabel: 'body > form > table > tbody > tr:nth-child(1) > td.se-right.se-bold',
        startDateInput: '#startdate',
        endDateLabel: 'body > form > table > tbody > tr:nth-child(2) > td.se-right.se-bold',
        endDateInput: '#stopdate',
        eventsNewsCheckbox: 'body > form > table > tbody > tr:nth-child(3) > td.se-left > input[type="checkbox"]',
        eventsNewsLabel: 'body > form > table > tbody > tr:nth-child(3) > td.se-left',
        submitBtn: 'body > form > table > tbody > tr:nth-child(4) > td.se-left > input',
        currentTab: 'body > form > ul.nav.nav-tabs > li > a',
        saveBtn: 'body > form > ul.nav.nav-tabs > input[type="button"]:nth-child(3)',
        viewBtn: 'body > form > ul.nav.nav-tabs > input[type="button"]:nth-child(2)',
        titleLabel: 'body > form > div > table:nth-child(1) > tbody > tr > td:nth-child(1)',
        titleInput: 'body > form > div > table:nth-child(1) > tbody > tr > td:nth-child(2) > input[type="text"]',
        titleAlignmentLabel: 'body > form > div > table:nth-child(1) > tbody > tr > td:nth-child(3)',
        titleAlignmentSelect: 'body > form > div > table:nth-child(1) > tbody > tr > td:nth-child(3) > font > b > select',
        titleFontSizeLabel: 'body > form > div > table:nth-child(1) > tbody > tr > td:nth-child(4)',
        titleFontSizeSelect: 'body > form > div > table:nth-child(1) > tbody > tr > td:nth-child(4) > font > b > select',
        trailerLabel: 'body > form > div > table:nth-child(2) > tbody > tr > td:nth-child(1)',
        trailerInput: 'body > form > div > table:nth-child(2) > tbody > tr > td:nth-child(2) > input[type="text"]',
        trailerAlignmentLabel: 'body > form > div > table:nth-child(2) > tbody > tr > td:nth-child(3)',
        trailerAlignmentSelect: 'body > form > div > table:nth-child(2) > tbody > tr > td:nth-child(3) > font > b > select',
        trailerFontSizeLabel: 'body > form > div > table:nth-child(2) > tbody > tr > td:nth-child(4)',
        trailerFontSizeSelect: 'body > form > div > table:nth-child(2) > tbody > tr > td:nth-child(4) > font > b > select',
        schoolNameCheckbox: 'body > form > div > table:nth-child(3) > tbody > tr:nth-child(1) > td:nth-child(2) > input[type="checkbox"]',
        schoolMottoCheckbox: 'body > form > div > table:nth-child(3) > tbody > tr:nth-child(1) > td:nth-child(2) > font > b > input[type="checkbox"]',
        schoolAddressCheckbox: 'body > form > div > table:nth-child(3) > tbody > tr:nth-child(2) > td:nth-child(2) > input[type="checkbox"]',
        schoolPhoneCheckbox: 'body > form > div > table:nth-child(3) > tbody > tr:nth-child(2) > td:nth-child(2) > font > b > input[type="checkbox"]',
        eventsHeader: 'body > form > div > table:nth-child(4) > tbody > tr > td:nth-child(1)',
        eventsBoxCheckbox: 'body > form > div > table:nth-child(4) > tbody > tr > td:nth-child(2) > font > input[type="checkbox"]',
        eventsFontSizeSelect: 'body > form > div > table:nth-child(4) > tbody > tr > td:nth-child(2) > font > select',
        eventsDateHeader: 'body > form > div > table:nth-child(5) > tbody > tr > td:nth-child(2)',
        eventsClassHeader: 'body > form > div > table:nth-child(5) > tbody > tr > td:nth-child(3)',
        eventsEventsHeader: 'body > form > div > table:nth-child(5) > tbody > tr > td:nth-child(4)',
        newsHeader: 'body > form > div > table:nth-child(6) > tbody > tr > td:nth-child(1)',
        newsBoxCheckbox: 'body > form > div > table:nth-child(6) > tbody > tr > td:nth-child(2) > font > input[type="checkbox"]',
        newsFontSizeSelect: 'body > form > div > table:nth-child(6) > tbody > tr > td:nth-child(2) > font > select',
        newsDateHeader: 'body > form > div > table:nth-child(7) > tbody > tr:nth-child(1) > td:nth-child(2)',
        newsPHeader: 'body > form > div > table:nth-child(7) > tbody > tr:nth-child(1) > td:nth-child(3)',
        newsClassHeader: 'body > form > div > table:nth-child(7) > tbody > tr:nth-child(1) > td:nth-child(4)',
        newsSubjectHeader: 'body > form > div > table:nth-child(7) > tbody > tr:nth-child(1) > td:nth-child(5)'
    }
};
