module.exports = {
    elements: {
        breadcrumb: '.breadcrumb',
        updateBtn: '.btn',
        lessonPlanLabelsHeader: 'tr.se-bold:nth-child(1)',
        label1: '.table > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(1)',
        objectivesInput: '#label1',
        objectivesLabel: '.table > tbody:nth-child(1) > tr:nth-child(2) > td:nth-child(2) > span:nth-child(2)',
        label2: '.table > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(1)',
        resourcesInput: '#label2',
        resourcesLabel: '.table > tbody:nth-child(1) > tr:nth-child(3) > td:nth-child(2) > span:nth-child(2)',
        label3: '.table > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(1)',
        proceduresInput: '#label3',
        proceduresLabel: '.table > tbody:nth-child(1) > tr:nth-child(4) > td:nth-child(2) > span:nth-child(2)',
        label4: '.table > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(1)',
        evaluationInput: '#label4',
        evaluationLabel: '.table > tbody:nth-child(1) > tr:nth-child(5) > td:nth-child(2) > span:nth-child(2)',
        daysHeader: 'tr.se-bold:nth-child(7)',
        daysInstructions: '.table > tbody:nth-child(1) > tr:nth-child(8)',
        sundayCheckbox: '#chkSunday',
        sundayLabel: '.table > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(1) > label:nth-child(2)',
        mondayCheckbox: '#chkMonday',
        mondayLabel: '.table > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(1) > label:nth-child(4)',
        tuesdayCheckbox: '#chkTuesday',
        tuesdayLabel: '.table > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(1) > label:nth-child(6)',
        wednesdayCheckbox: '#chkWednesday',
        wednesdayLabel: '.table > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(1) > label:nth-child(8)',
        thursdayCheckbox: '#chkThursday',
        thursdayLabel: '.table > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(1) > label:nth-child(10)',
        fridayCheckbox: '#chkFriday',
        fridayLabel: '.table > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(1) > label:nth-child(12)',
        saturdayCheckbox: '#chkSaturday',
        saturdayLabel: '.table > tbody:nth-child(1) > tr:nth-child(9) > td:nth-child(1) > label:nth-child(14)'
    }
};
