module.exports = {
    elements: {
        breadcrumb: '.breadcrumb',
        currentTab: '.nav > li:nth-child(1) > a',
        previousTab: '.nav > li:nth-child(2) > a',
        newEmployeeBtn: '.btn',
        levelSelect: '.input-medium',
        typeSelect: '.small',
        all: '#All',
        a: '#A',
        b: '#B',
        c: '#C',
        d: '#D',
        e: '#E',
        f: '#F',
        g: '#G',
        h: '#H',
        i: '#I',
        j: '#J',
        k: '#K',
        l: '#L',
        m: '#M',
        n: '#N',
        o: '#O',
        p: '#P',
        q: '#Q',
        r: '#R',
        s: '#S',
        t: '#T',
        u: '#U',
        v: '#V',
        w: '#W',
        x: '#X',
        y: '#Y',
        z: '#Z',
        nameHeader: 'table.se-font > tbody:nth-child(1) > tr:nth-child(1) > th:nth-child(3)',
        levelHeader: 'table.se-font > tbody:nth-child(1) > tr:nth-child(1) > th:nth-child(4)',
        positionHeader: 'table.se-font > tbody:nth-child(1) > tr:nth-child(1) > th:nth-child(5)',
        managerHeader: 'table.se-font > tbody:nth-child(1) > tr:nth-child(1) > th:nth-child(6)'
    }
};
