var moment = require('moment');

module.exports = {
    tags: ['schoolTests', 'calendarMonthTest', 'calendarTests'],

    'Calendar Month Test': (client) => {

        var page = client.page.login();

        page.navigate()
            .schoolLogin();

        client.frame(1);
        client.page.menu()
            .assert.visible('@school')
            .click('@school')
            .assert.visible('@schoolCalendar')
            .click('@schoolCalendar')
        client.frame(null);

        client.frame(2);
        client.page.calendar()
            .waitForElementVisible('@breadcrumb', 5000)
            .assert.visible('@breadcrumb')
            .assert.containsText('@breadcrumb', 'School/Calendar/ Month')

            .assert.visible('@monthTab')
            .assert.containsText('@monthTab', 'Month')

            .assert.visible('@weekTab')
            .assert.containsText('@weekTab', 'Week')

            .assert.visible('@dayTab')
            .assert.containsText('@dayTab', 'Day')

            .assert.visible('@exportiCalBtn')
            .assert.attributeEquals('@exportiCalBtn', 'value', 'Export iCal')
            .assert.attributeEquals('@exportiCalBtn', 'onclick', `icalexport(${moment().subtract(1, 'days').format('MM, YYYY')}, 4)`)

            .assert.visible('@searchField')
            .assert.attributeEquals('@searchField', 'type', 'text')
            
            .assert.visible('@searchBtn')
            .assert.attributeEquals('@searchBtn', 'value', 'Search')
            .assert.attributeEquals('@searchBtn', 'type', 'submit')

            .assert.visible('@printBtn')
            .assert.attributeEquals('@printBtn', 'value', ' Print ')
            .assert.attributeEquals('@printBtn', 'onclick', 'doPrint()')

            .assert.visible('@meetingMakerBtn')
            .assert.attributeEquals('@meetingMakerBtn', 'value', 'Meeting Maker')
            .assert.attributeEquals('@meetingMakerBtn', 'onclick', 'meetingmaker()')

            .assert.visible('@todayBtn')
            .assert.attributeEquals('@todayBtn', 'value', 'Today')
            .assert.attributeEquals('@todayBtn', 'onclick', `goto(${moment().format('DD, YYYY')})`)

            .assert.visible('@leftArrowBtn')
            .assert.attributeEquals('@leftArrowBtn', 'value', '<')
            .assert.attributeEquals('@leftArrowBtn', 'onclick', `goto(${moment().subtract(1, 'days').format('DD, YYYY')})`)

            .assert.visible('@rightArrowBtn')
            .assert.attributeEquals('@rightArrowBtn', 'value', '>')
            .assert.attributeEquals('@rightArrowBtn', 'onclick', `goto(${moment().add(1, 'days').format('DD, YYYY')})`)

            .assert.visible('@monthSelector')
            .assert.containsText('@monthSelector', moment().format('MMMM'))

            .assert.visible('@yearSelector')
            .assert.containsText('@yearSelector', moment().format('YYYY'))

            .assert.visible('@monthYearHeader')
            .assert.containsText('@monthYearHeader', moment().format('MMMM YYYY'))

            .assert.visible('@categoryLabel')
            .assert.containsText('@categoryLabel', 'Category')

            .assert.visible('@categorySelector')

            .assert.visible('@janTab')
            .assert.containsText('@janTab', 'Jan')
            .click('@janTab')
            .assert.containsText('@monthYearHeader', `January ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(1); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(1, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@febTab')
            .assert.containsText('@febTab', 'Feb')
            .click('@febTab')
            .assert.containsText('@monthYearHeader', `February ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')            
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(2); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(2, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@marTab')
            .assert.containsText('@marTab', 'Mar')
            .click('@marTab')
            .assert.containsText('@monthYearHeader', `March ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(3); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(3, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@aprTab')
            .assert.containsText('@aprTab', 'Apr')
            .click('@aprTab')
            .assert.containsText('@monthYearHeader', `April ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(4); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(4, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@mayTab')
            .assert.containsText('@mayTab', 'May')
            .click('@mayTab')
            .assert.containsText('@monthYearHeader', `May ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(5); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(5, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@junTab')
            .assert.containsText('@junTab', 'Jun')
            .click('@junTab')
            .assert.containsText('@monthYearHeader', `June ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(6); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(6, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@julTab')
            .assert.containsText('@julTab', 'Jul')
            .click('@julTab')
            .assert.containsText('@monthYearHeader', `July ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(7); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(7, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@augTab')
            .assert.containsText('@augTab', 'Aug')
            .click('@augTab')
            .assert.containsText('@monthYearHeader', `August ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(8); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(8, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@sepTab')
            .assert.containsText('@sepTab', 'Sep')
            .click('@sepTab')
            .assert.containsText('@monthYearHeader', `September ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(9); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(9, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@octTab')
            .assert.containsText('@octTab', 'Oct')
            .click('@octTab')
            .assert.containsText('@monthYearHeader', `October ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(10); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(10, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@novTab')
            .assert.containsText('@novTab', 'Nov')
            .click('@novTab')
            .assert.containsText('@monthYearHeader', `November ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(11); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(11, ${moment().format('YYYY')},0);return false;`)

            .assert.visible('@decTab')
            .assert.containsText('@decTab', 'Dec')
            .click('@decTab')
            .assert.containsText('@monthYearHeader', `December ${moment().format('YYYY')}`)
            .assert.visible('@calendarBody')                        
            .assert.visible('@sun')
            .assert.containsText('@sun', 'Sun')
            .assert.visible('@mon')
            .assert.containsText('@mon', 'Mon')
            .assert.visible('@tue')
            .assert.containsText('@tue', 'Tue')
            .assert.visible('@wed')
            .assert.containsText('@wed', 'Wed')
            .assert.visible('@thu')
            .assert.containsText('@thu', 'Thu')
            .assert.visible('@fri')
            .assert.containsText('@fri', 'Fri')
            .assert.visible('@sat')
            .assert.containsText('@sat', 'Sat')
            .assert.visible('@birthdayBtn')
            .assert.attributeEquals('@birthdayBtn', 'onclick', 'birthdays(12); return false')
            .assert.visible('@listingBtn')
            .assert.attributeEquals('@listingBtn', 'onclick', `listing(12, ${moment().format('YYYY')},0);return false;`)

        client.frame(null)

        client.end();
    }
};
